Repository xtray85/space_station, pull requests merged in 2023-10, with the labels that each got.

#57 Пластыри
  Resources/Locale/ru-RU/ADT/Objects/specific/medstuff.ftl
  Resources/Prototypes/ADT/Entities/Objects/Specific/Medical/patch.yml
  Resources/Prototypes/ADT/tags.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/medical.yml
  Resources/Prototypes/Entities/Clothing/Belt/belts.yml
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/meta.json
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch0.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch1.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch10.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch11.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch12.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch13.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch14.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch15.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch16.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch17.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch18.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch19.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch2.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch20.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch3.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch4.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch5.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch6.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch7.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch8.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patch9.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patchpack.png
  Resources/Textures/ADT/Objects/Specific/Medical/patch.rsi/patchused.png
Labels: Changes: Sprites, Changes: Localization, No C#

#58 хиросима илюми 2
  Resources/Locale/ru-RU/ADT/Catalog/store/uplink.ftl
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Grenades/grenades.ftl
  Resources/Prototypes/ADT/Catalog/uplink.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Throwable/grenades.yml
  Resources/Textures/ADT/Objects/Weapons/Grenades/tritiumgrenad/effect.rsi/broken.png
  Resources/Textures/ADT/Objects/Weapons/Grenades/tritiumgrenad/effect.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Grenades/tritiumgrenad/effect.rsi/miner.png
  Resources/Textures/ADT/Objects/Weapons/Grenades/tritiumgrenad/effect.rsi/on.png
  Resources/Textures/ADT/Objects/Weapons/Grenades/tritiumgrenad/tritiumgrenades.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Grenades/tritiumgrenad/tritiumgrenades.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Grenades/tritiumgrenad/tritiumgrenades.rsi/primed.png
Labels: Changes: Sprites, Changes: Localization, No C#

#60 добавлена новая музыка в лобби
  Resources/Audio/Lobby/The_Wrong_Party.ogg
  Resources/Audio/Lobby/attributions.yml
  Resources/Prototypes/SoundCollections/lobby.yml
Labels: No C#

#63 Добавлены новын роли для киборгов
  Resources/Locale/ru-RU/job/job-names.ftl
  Resources/Prototypes/ADT/Roles/Jobs/Borgs/EngiBorg.yml
  Resources/Prototypes/ADT/Roles/Jobs/Borgs/JanitorBorg.yml
  Resources/Prototypes/ADT/Roles/Jobs/Borgs/MedicalBorg.yml
  Resources/Prototypes/ADT/Roles/Jobs/Borgs/ServiseBrog.yml
  Resources/Prototypes/ADT/Roles/Jobs/Borgs/SupplyBorg.yml
  Resources/Prototypes/Corvax/Maps/avrite.yml
  Resources/Prototypes/Corvax/Maps/delta.yml
  Resources/Prototypes/Maps/bagel.yml
  Resources/Prototypes/Maps/marathon.yml
  Resources/Prototypes/Maps/omega.yml
  Resources/Prototypes/Maps/origin.yml
  Resources/Prototypes/Maps/saltern.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/Roles/play_time_trackers.yml
Labels: Changes: Localization, No C#, Changes: Map

#64 белые хвостики + переводы белья
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Clothing/Underwear/underwear.ftl
  Resources/Textures/ADT/Mobs/Customization/fox_parts.rsi/tail_fox_wag_stripes_prime.png
  Resources/Textures/ADT/Mobs/Customization/fox_parts.rsi/tail_fox_wag_stripes_second.png
  Resources/Textures/ADT/Mobs/Customization/fox_parts.rsi/tail_fox_wag_stripes_third.png
Labels: Changes: Sprites, Changes: Localization, No C#

#65 Качественные революционеры
  Resources/Prototypes/Roles/Antags/revolutionary.yml
Labels: No C#

#68 "Честь отдают на сеновале"
  Resources/Audio/Effects/adminhelp3.ogg
  Resources/Locale/ru-RU/chat/sanitizer-replacements.ftl
Labels: Changes: Localization, No C#

#67 Добавлены цветные лампы трубки в крафты протолата
  Resources/Locale/ru-RU/ADT/Objects/Power/light.ftl
  Resources/Locale/ru-RU/ADT/research.ftl
  Resources/Prototypes/ADT/Entities/Objects/Power/lights.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Recipes/Lathes/misc.yml
  Resources/Prototypes/Research/civilianservices.yml
  Resources/Textures/ADT/Objects/Specific/light.rsi/icon.png
  Resources/Textures/ADT/Objects/Specific/light.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#70 Revert "белые хвостики + переводы белья"
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Clothing/Underwear/underwear.ftl
  Resources/Textures/ADT/Mobs/Customization/fox_parts.rsi/tail_fox_wag_stripes_prime.png
  Resources/Textures/ADT/Mobs/Customization/fox_parts.rsi/tail_fox_wag_stripes_second.png
  Resources/Textures/ADT/Mobs/Customization/fox_parts.rsi/tail_fox_wag_stripes_third.png
Labels: Changes: Sprites, Changes: Localization, No C#

#69 2 новых набора в хеллоуномат.
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Clothing/halloween.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Boxes/halloween_suit.yml
  Resources/Prototypes/ADT/Catalog/Fills/Crates/halloween.yml
  Resources/Prototypes/ADT/Catalog/VendingMachines/Inventories/halloweenomat.yml
  Resources/Prototypes/ADT/Entities/Clothing/Head/misc.yml
  Resources/Prototypes/ADT/Entities/Clothing/Masks/mask.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpsuit.yml
  Resources/Textures/ADT/Clothing/Head/Misc/hatchainsaw.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Misc/hatchainsaw.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Misc/hatchainsaw.rsi/meta.json
  Resources/Textures/ADT/Clothing/Mask/payday_chains.rsi/equipped-MASK.png
  Resources/Textures/ADT/Clothing/Mask/payday_chains.rsi/icon.png
  Resources/Textures/ADT/Clothing/Mask/payday_chains.rsi/meta.json
  Resources/Textures/ADT/Clothing/Mask/payday_dallas.rsi/equipped-MASK.png
  Resources/Textures/ADT/Clothing/Mask/payday_dallas.rsi/icon.png
  Resources/Textures/ADT/Clothing/Mask/payday_dallas.rsi/meta.json
  Resources/Textures/ADT/Clothing/Mask/payday_houston.rsi/equipped-MASK.png
  Resources/Textures/ADT/Clothing/Mask/payday_houston.rsi/icon.png
  Resources/Textures/ADT/Clothing/Mask/payday_houston.rsi/meta.json
  Resources/Textures/ADT/Clothing/Mask/payday_wolf.rsi/equipped-MASK.png
  Resources/Textures/ADT/Clothing/Mask/payday_wolf.rsi/icon.png
  Resources/Textures/ADT/Clothing/Mask/payday_wolf.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/Halloween/suit_hunterdemon.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/Halloween/suit_hunterdemon.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/Halloween/suit_hunterdemon.rsi/meta.json
  Resources/Textures/ADT/Objects/Storage/halloween_box.rsi/chainsaw.png
  Resources/Textures/ADT/Objects/Storage/halloween_box.rsi/meta.json
  Resources/Textures/ADT/Objects/Storage/halloween_box.rsi/payday.png
Labels: Changes: Sprites, Changes: Localization, No C#

#74 добавил 2 новые цели
  Resources/Locale/ru-RU/corvax/station-goal/station-goal-component.ftl
  Resources/Prototypes/Corvax/Objectives/goals.yml
Labels: Changes: Localization, No C#

#73 Мелкие правки.
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Clothing/Hands/gloves.ftl
  Resources/Locale/ru-RU/ADT/Objects/Fan/plushie_aidan.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Hands/gloves.yml
  Resources/ServerInfo/ADT/srp/KorporateZakonCritical.xml
  Resources/ServerInfo/ADT/srp/KorporateZakonMedium.xml
  Resources/ServerInfo/ADT/srp/KorporateZakonMinor.xml
  Resources/ServerInfo/ADT/srp/KorporateZakonSerious.xml
  Resources/Textures/ADT/Clothing/Hands/Gloves/brassknuckles_gloves.rsi/equipped-HAND.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/brassknuckles_gloves.rsi/icon.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/brassknuckles_gloves.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#71 батарейки и смэсы
  Resources/Locale/ru-RU/ADT/Objects/Device/Circuitboard.ftl
  Resources/Locale/ru-RU/ADT/Objects/Power/powercell.ftl
  Resources/Locale/ru-RU/ADT/research.ftl
  Resources/Prototypes/ADT/Entities/Objects/Device/Circuitboards/industrial.yml
  Resources/Prototypes/ADT/Entities/Objects/Power/powercell.yml
  Resources/Prototypes/ADT/Entities/Structures/Power/industrial.yml
  Resources/Prototypes/Catalog/Fills/Crates/salvage.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Procedural/salvage_rewards.yml
  Resources/Prototypes/Recipes/Lathes/electronics.yml
  Resources/Prototypes/Recipes/Lathes/powercells.yml
  Resources/Prototypes/Research/industrial.yml
  Resources/Textures/Objects/Misc/module.rsi/ind_smes_circuit.png
  Resources/Textures/Objects/Misc/module.rsi/meta.json
  Resources/Textures/Objects/Power/power_cells.rsi/bluespace.png
  Resources/Textures/Objects/Power/power_cells.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#72 корректировка цен у карго
  Resources/Prototypes/Catalog/Cargo/cargo_botany.yml
  Resources/Prototypes/Catalog/Cargo/cargo_engines.yml
  Resources/Prototypes/Catalog/Fills/Crates/botany.yml
Labels: No C#
