Repository xtray85/space_station, pull requests merged in 2023-12, with the labels that each got.

#169 Test RSI check
  .github/Schemas/mapfile.yml
  .github/Schemas/mapfile_requirements.txt
  .github/Schemas/mapfile_validators.py
  .github/Schemas/rga.yml
  .github/Schemas/rga_requirements.txt
  .github/Schemas/rga_validators.py
  .github/Schemas/rsi.json
  .github/Schemas/validate_rsis.py
  .github/rsi-schema.json
  .github/workflows/validate-rsis.yml
  Resources/Textures/ADT/Objects/Weapons/Guns/Revolvers/Unica.rsi/meta.json
Labels: No C#

#173 chicken fix
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Food/chicken_meat.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Hands/gloves.yml
  Resources/Prototypes/ADT/Entities/Clothing/Masks/mask.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpsuit.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/meat.yml
  Resources/Textures/ADT/Objects/Consumable/Food/chicken_meat.rsi/baked_slice.png
  Resources/Textures/ADT/Objects/Consumable/Food/chicken_meat.rsi/baked_stuffed_slice.png
  Resources/Textures/ADT/Objects/Consumable/Food/chicken_meat.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Food/chicken_meat.rsi/plate.png
Labels: Changes: Sprites, Changes: Localization, No C#

#175 пакетик для улик
  Resources/Locale/ru-RU/ADT/Objects/Misc/EvidanceBag.ftl
  Resources/Prototypes/ADT/Entities/Objects/Misc/EvidenceBag.yml
  Resources/Textures/ADT/Objects/Misc/Evidance.rsi/icon.png
  Resources/Textures/ADT/Objects/Misc/Evidance.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#179 Новые карты обломков
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/shark/entities/mobs/player/Shark.ftl
  Resources/Maps/Salvage/ADT/cargo_1.yml
  Resources/Maps/Salvage/ADT/cargo_2.yml
  Resources/Maps/Salvage/ADT/cargo_3.yml
  Resources/Maps/Salvage/ADT/cargo_4.yml
  Resources/Maps/Salvage/ADT/customs.yml
  Resources/Maps/Salvage/ADT/engi_1.yml
  Resources/Maps/Salvage/ADT/engi_2.yml
  Resources/Maps/Salvage/ADT/gravity.yml
  Resources/Maps/Salvage/ADT/medical_1.yml
  Resources/Maps/Salvage/ADT/medical_2.yml
  Resources/Maps/Salvage/ADT/medical_3.yml
  Resources/Maps/Salvage/ADT/medical_4.yml
  Resources/Maps/Salvage/ADT/midshut1.yml
  Resources/Maps/Salvage/ADT/most1.yml
  Resources/Maps/Salvage/ADT/pirate.yml
  Resources/Maps/Salvage/ADT/poligon.yml
  Resources/Maps/Salvage/ADT/rnd_1.yml
  Resources/Maps/Salvage/ADT/rnd_2.yml
  Resources/Maps/Salvage/ADT/rnd_3.yml
  Resources/Maps/Salvage/ADT/rnd_4.yml
  Resources/Maps/Salvage/ADT/salvage_1.yml
  Resources/Maps/Salvage/ADT/salvage_3.yml
  Resources/Maps/Salvage/ADT/salvage_4.yml
  Resources/Maps/Salvage/ADT/salvage_5.yml
  Resources/Maps/Salvage/ADT/salvage_6.yml
  Resources/Maps/Salvage/ADT/salvage_7.yml
  Resources/Maps/Salvage/ADT/salvage_EVA.yml
  Resources/Maps/Salvage/ADT/salvage_bridge.yml
  Resources/Maps/Salvage/ADT/sec_2.yml
  Resources/Maps/Salvage/ADT/sec_3.yml
  Resources/Maps/Salvage/ADT/sec_4.yml
  Resources/Maps/Salvage/ADT/service_1.yml
  Resources/Maps/Salvage/ADT/service_2.yml
  Resources/Maps/Salvage/ADT/service_botany.yml
  Resources/Maps/Salvage/ADT/syndy_4.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Rifels/mech_gun.yml
  Resources/Prototypes/Maps/salvage.yml
Labels: Changes: Localization, No C#, Changes: Map

#176 FixAntag
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
  Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
Labels: No C#

#180 Update16(Done)
  Content.Client/UserInterface/Systems/Bwoink/AHelpUIController.cs
  Resources/Locale/ru-RU/ADT/Clothing/Head/hats.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Mask/mask.ftl
  Resources/Locale/ru-RU/ADT/Clothing/OuterClothing/Misc/misc.ftl
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Smokeables/Cigars/case.ftl
  Resources/Locale/ru-RU/ADT/Objects/Mobs/animals.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Head/misc.yml
  Resources/Prototypes/ADT/Entities/Clothing/Masks/mask.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/FunOuterClothing.yml
  Resources/ServerInfo/Rules.txt
  Resources/Textures/ADT/Clothing/Head/Misc/ded_morozhat.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Misc/ded_morozhat.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Misc/ded_morozhat.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Misc/hat_roga.rsi/equipped-HELMET-linght.png
  Resources/Textures/ADT/Clothing/Head/Misc/hat_roga.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Misc/hat_roga.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Misc/hat_roga.rsi/meta.json
  Resources/Textures/ADT/Clothing/Mask/ded_morozsetboroda.rsi/equipped-MASK.png
  Resources/Textures/ADT/Clothing/Mask/ded_morozsetboroda.rsi/icon.png
  Resources/Textures/ADT/Clothing/Mask/ded_morozsetboroda.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Fun/ded_morozsuitouter.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Fun/ded_morozsuitouter.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Fun/ded_morozsuitouter.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization

#181 Мандарин и всё, что него касается
  Resources/Locale/ru-RU/ADT/newYear/mandarin.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/mandarin.yml
  Resources/Textures/ADT/Objects/Specific/Hydroponics/mandarin.rsi/dead.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/mandarin.rsi/harvest.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/mandarin.rsi/meta.json
  Resources/Textures/ADT/Objects/Specific/Hydroponics/mandarin.rsi/peel.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/mandarin.rsi/produce.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/mandarin.rsi/seed.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/mandarin.rsi/slice.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/mandarin.rsi/stage-1.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/mandarin.rsi/stage-2.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/mandarin.rsi/stage-3.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/mandarin.rsi/stage-4.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/mandarin.rsi/stage-5.png
  Resources/Textures/ADT/Objects/Specific/Hydroponics/mandarin.rsi/stage-6.png
Labels: Changes: Sprites, Changes: Localization, No C#

#186 исправление id мандарина
  Resources/Locale/ru-RU/ADT/newYear/mandarin.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/mandarin.yml
Labels: Changes: Localization, No C#

#184 Подарки на новый год
  Resources/Audio/ADT/Fun/bell.ogg
  Resources/Audio/ADT/Fun/c4NY_music.ogg
  Resources/Locale/ru-RU/ADT/Catalog/fills/Boxes/gift.ftl
  Resources/Locale/ru-RU/ADT/Fun/coal.ftl
  Resources/Locale/ru-RU/ADT/Fun/toyC4.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Boxes/gift.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/c4toy.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/coal.yml
  Resources/Textures/ADT/Objects/Fun/c4toy.rsi/icon.png
  Resources/Textures/ADT/Objects/Fun/c4toy.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Fun/c4toy.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Fun/c4toy.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/c4toyPackage.rsi/icon.png
  Resources/Textures/ADT/Objects/Fun/c4toyPackage.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Fun/c4toyPackage.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Fun/c4toyPackage.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/coal.rsi/icon.png
  Resources/Textures/ADT/Objects/Fun/coal.rsi/meta.json
  Resources/Textures/ADT/Objects/Storage/gift.rsi/icon.png
  Resources/Textures/ADT/Objects/Storage/gift.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Storage/gift.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Storage/gift.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#185 Emote panel
  Content.Client/ADT/EmotePanel/EmotePanelSystem.cs
  Content.Client/UserInterface/Systems/Radial/Controls/RadialContainer.xaml
  Content.Client/UserInterface/Systems/Radial/Controls/RadialContainer.xaml.cs
  Content.Client/UserInterface/Systems/Radial/Controls/RadialItem.xaml
  Content.Client/UserInterface/Systems/Radial/Controls/RadialItem.xaml.cs
  Content.Client/UserInterface/Systems/Radial/RadialUiController.cs
  Content.Server/ADT/EmotePanel/EmotePanelSystem.cs
  Content.Shared/ADT/EmotePanel/EmotePanelComponent.cs
  Content.Shared/Chat/Prototypes/EmotePrototype.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/en-US/actions/actions/emoting.ftl
  Resources/Locale/en-US/ui/radials.ftl
  Resources/Locale/ru-RU/ADT/Actions/types.ftl
  Resources/Locale/ru-RU/ADT/Interface/radialUi.ftl
  Resources/Prototypes/Actions/types.yml
  Resources/Prototypes/Entities/Mobs/Species/base.yml
  Resources/Prototypes/Voice/disease_emotes.yml
  Resources/Prototypes/Voice/speech_emotes.yml
  Resources/Textures/Interface/Actions/emotes.png
  Resources/Textures/Interface/Actions/meta.json
  Resources/Textures/Interface/Classic/SlotBackground.png
  Resources/Textures/Interface/Emotes/claps.png
  Resources/Textures/Interface/Emotes/coughs.png
  Resources/Textures/Interface/Emotes/crying.png
  Resources/Textures/Interface/Emotes/laugh.png
  Resources/Textures/Interface/Emotes/meta.json
  Resources/Textures/Interface/Emotes/salute.png
  Resources/Textures/Interface/Emotes/scream.png
  Resources/Textures/Interface/Emotes/sighn.png
  Resources/Textures/Interface/Emotes/snaps-fingers.png
  Resources/Textures/Interface/Emotes/whistle.png
  Resources/Textures/Interface/Emotes/yawns.png
  Resources/Textures/Interface/Modernized/SlotBackground.png
Labels: Changes: Localization, Changes: UI

#189 Минус акулы
  Resources/Prototypes/ADT/Shark/Species/Shark.yml
Labels: No C#

#196 Фикс RCS
  Resources/Prototypes/NES/Shuttles/Nes_shuttles.yml
  Resources/Textures/NES/Shuttle/OldRSY_thryster.rsi/thrust.png
  Resources/Textures/NES/Shuttle/RSY_thruster.rsi/thrust.png
Labels: Changes: Sprites, No C#

#198 Новогодние плакаты и старые прически
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Catalog/fills/Boxes/gift.ftl
  Resources/Locale/ru-RU/ADT/Catalog/fills/items/sparkler_pack.ftl
  Resources/Locale/ru-RU/ADT/Flavors/flavor-profiles.ftl
  Resources/Locale/ru-RU/ADT/Fun/toyC4.ftl
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Food/sawdustsoup.ftl
  Resources/Locale/ru-RU/ADT/Objects/Decoration/christmas_fireplace.ftl
  Resources/Locale/ru-RU/ADT/Objects/Decoration/new_year.ftl
  Resources/Locale/ru-RU/ADT/Objects/Misc/sparkler.ftl
  Resources/Locale/ru-RU/ADT/Objects/structuries/furniture/furniture.ftl
  Resources/Locale/ru-RU/accessories/human-hair.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
  Resources/Maps/Salvage/ADT/salvage_5.yml
  Resources/Prototypes/ADT/Catalog/Fills/Boxes/gift.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/sawdustsoup.yml
  Resources/Prototypes/ADT/Entities/Objects/Decoration/new_year.yml
  Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
  Resources/Prototypes/ADT/Flavors/flavors.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/posters.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/human_hair.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/soup.yml
  Resources/Prototypes/Entities/Objects/Decoration/flora.yml
  Resources/Textures/ADT/Objects/Consumable/Food/sawdustsoup.rsi/bowl.png
  Resources/Textures/ADT/Objects/Consumable/Food/sawdustsoup.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Food/sawdustsoup.rsi/sawdustsoup.png
  Resources/Textures/ADT/Objects/Decoration/donttalktoarty.rsi/donttalktoarty.png
  Resources/Textures/ADT/Objects/Decoration/donttalktoarty.rsi/meta.json
  Resources/Textures/ADT/Objects/Decoration/lustymoth.rsi/lustymoth.png
  Resources/Textures/ADT/Objects/Decoration/lustymoth.rsi/meta.json
  Resources/Textures/ADT/Objects/Decoration/new_year_present.rsi/blue.png
  Resources/Textures/ADT/Objects/Decoration/new_year_present.rsi/green.png
  Resources/Textures/ADT/Objects/Decoration/new_year_present.rsi/meta.json
  Resources/Textures/ADT/Objects/Decoration/new_year_present.rsi/purple.png
  Resources/Textures/ADT/Objects/Decoration/new_year_present.rsi/red.png
  Resources/Textures/ADT/Objects/Decoration/new_year_present.rsi/syndicate.png
  Resources/Textures/ADT/Objects/Decoration/panem.rsi/meta.json
  Resources/Textures/ADT/Objects/Decoration/panem.rsi/panem.png
  Resources/Textures/ADT/Objects/Decoration/papersplease.rsi/meta.json
  Resources/Textures/ADT/Objects/Decoration/papersplease.rsi/papersplease.png
  Resources/Textures/ADT/Objects/Decoration/plasmaman.rsi/meta.json
  Resources/Textures/ADT/Objects/Decoration/plasmaman.rsi/plasmaman.png
  Resources/Textures/ADT/Objects/Decoration/poster_new_year.rsi/meta.json
  Resources/Textures/ADT/Objects/Decoration/poster_new_year.rsi/new_year2.png
  Resources/Textures/ADT/Objects/Decoration/poster_new_year.rsi/new_year3.png
  Resources/Textures/ADT/Objects/Decoration/watchoutchem.rsi/chem.png
  Resources/Textures/ADT/Objects/Decoration/watchoutchem.rsi/meta.json
  Resources/Textures/ADT/Objects/Decoration/workunderway.rsi/meta.json
  Resources/Textures/ADT/Objects/Decoration/workunderway.rsi/workunderway.png
  Resources/Textures/ADT/Structures/Furniture/Armchair/armchair_blue.rsi/meta.json
  Resources/Textures/ADT/Structures/Furniture/Armchair/armchair_brown.rsi/meta.json
  Resources/Textures/ADT/Structures/Furniture/Armchair/armchair_white.rsi/meta.json
  Resources/Textures/Mobs/Customization/human_hair.rsi/classic_bedhead.png
  Resources/Textures/Mobs/Customization/human_hair.rsi/classic_business.png
  Resources/Textures/Mobs/Customization/human_hair.rsi/classic_business2.png
  Resources/Textures/Mobs/Customization/human_hair.rsi/classic_business3.png
  Resources/Textures/Mobs/Customization/human_hair.rsi/classic_business4.png
  Resources/Textures/Mobs/Customization/human_hair.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#201 Попытка 2
  Content.Server/Atmos/EntitySystems/AtmosphereSystem.HighPressureDelta.cs
  Content.Shared/CCVar/CCVars.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/ConfigPresets/Build/development.toml
  Resources/Prototypes/Entities/Mobs/Species/base.yml
  Resources/Prototypes/Entities/Mobs/base.yml
  Resources/Prototypes/NES/Nes_ammo.yml
  Resources/Prototypes/NES/Nes_furniture.yml
  Resources/Prototypes/NES/Shuttles/Nes_shuttles.yml
  Resources/Prototypes/Reagents/biological.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/shadowkin.yml
  Resources/Textures/NES/Railguns/railgun.rsi/beam.png
  Resources/Textures/NES/Railguns/railgun.rsi/emitter.png
  Resources/Textures/NES/Railguns/railgun.rsi/lock.png
  Resources/Textures/NES/Railguns/railgun.rsi/meta.json
  Resources/Textures/NES/Railguns/railgun.rsi/projectile.png
  Resources/Textures/NES/Railguns/railgun.rsi/underpowered.png
  Resources/Textures/NES/Railguns/railgun.rsi/unlock.png
Labels: Changes: Sprites

#199 Изменение спрайтов окон и шлюзов
  Resources/Textures/Clothing/OuterClothing/Hardsuits/syndiemedic.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Clothing/OuterClothing/Hardsuits/syndiemedic.rsi/icon.png
  Resources/Textures/Clothing/OuterClothing/Hardsuits/syndiemedic.rsi/inhand-left.png
  Resources/Textures/Clothing/OuterClothing/Hardsuits/syndiemedic.rsi/inhand-right.png
  Resources/Textures/Clothing/OuterClothing/Hardsuits/syndiemedic.rsi/meta.json
  Resources/Textures/Structures/Doors/Airlocks/Glass/syndicate.rsi/closed.png
  Resources/Textures/Structures/Doors/Airlocks/Glass/syndicate.rsi/closing.png
  Resources/Textures/Structures/Doors/Airlocks/Standard/syndicate.rsi/closed.png
  Resources/Textures/Structures/Doors/Airlocks/Standard/syndicate.rsi/closing.png
  Resources/Textures/Structures/Walls/solidrust.rsi/full.png
  Resources/Textures/Structures/Walls/solidrust.rsi/meta.json
  Resources/Textures/Structures/Walls/solidrust.rsi/solidrust0.png
  Resources/Textures/Structures/Walls/solidrust.rsi/solidrust1.png
  Resources/Textures/Structures/Walls/solidrust.rsi/solidrust2.png
  Resources/Textures/Structures/Walls/solidrust.rsi/solidrust3.png
  Resources/Textures/Structures/Walls/solidrust.rsi/solidrust4.png
  Resources/Textures/Structures/Walls/solidrust.rsi/solidrust5.png
  Resources/Textures/Structures/Walls/solidrust.rsi/solidrust6.png
  Resources/Textures/Structures/Walls/solidrust.rsi/solidrust7.png
  Resources/Textures/Structures/Windows/plasma_diagonal.rsi/meta.json
  Resources/Textures/Structures/Windows/plasma_diagonal.rsi/state0.png
  Resources/Textures/Structures/Windows/plasma_diagonal.rsi/state1.png
  Resources/Textures/Structures/Windows/reinforced_plasma_diagonal.rsi/meta.json
  Resources/Textures/Structures/Windows/reinforced_plasma_diagonal.rsi/state0.png
  Resources/Textures/Structures/Windows/reinforced_plasma_diagonal.rsi/state1.png
  Resources/Textures/Structures/Windows/reinforced_uranium_diagonal.rsi/meta.json
  Resources/Textures/Structures/Windows/reinforced_uranium_diagonal.rsi/state0.png
  Resources/Textures/Structures/Windows/reinforced_uranium_diagonal.rsi/state1.png
  Resources/Textures/Structures/Windows/reinforced_window_diagonal.rsi/meta.json
  Resources/Textures/Structures/Windows/reinforced_window_diagonal.rsi/state0.png
  Resources/Textures/Structures/Windows/reinforced_window_diagonal.rsi/state1.png
  Resources/Textures/Structures/Windows/uranium_window_diagonal.rsi/meta.json
  Resources/Textures/Structures/Windows/uranium_window_diagonal.rsi/state0.png
  Resources/Textures/Structures/Windows/uranium_window_diagonal.rsi/state1.png
  Resources/Textures/Structures/Windows/window_diagonal.rsi/meta.json
  Resources/Textures/Structures/Windows/window_diagonal.rsi/state0.png
  Resources/Textures/Structures/Windows/window_diagonal.rsi/state1.png
Labels: Changes: Sprites, No C#

#202 Updatee
  Content.Client/UserInterface/Systems/Chat/ChatUIController.cs
  Content.Client/UserInterface/Systems/Chat/Widgets/ChatBox.xaml.cs
  Resources/Locale/ru-RU/traits/traits.ftl
  Resources/Prototypes/Voice/speech_emotes.yml
Labels: Changes: Localization, Changes: UI

#204 Напиточное ДЛС к БАЛЬШОМУ НОВОГОДНЕМУ АПДЕЙТУ™
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Flavors/flavor-profiles.ftl
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Drinks/new_year.ftl
  Resources/Locale/ru-RU/ADT/Reagents/new_year.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Drinks/new_year.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/hypoallergen_chocolate.yml
  Resources/Prototypes/ADT/Flavors/flavors.yml
  Resources/Prototypes/ADT/Reagents/Consumable/Drink/new_year.yml
  Resources/Prototypes/ADT/Recipes/Construction/Graph/drinks.yml
  Resources/Prototypes/ADT/Recipes/Reactions/just_kekc_coctails_recipe.yml
  Resources/Prototypes/ADT/Recipes/Reactions/new_year.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
  Resources/Prototypes/Entities/Structures/Machines/grill.yml
  Resources/ServerInfo/ADT/NewCocktails.xml
  Resources/Textures/ADT/Objects/Consumable/Drinks/new_year.rsi/christmas_milkshake.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/new_year.rsi/hot_chocolate.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/new_year.rsi/hot_cocoa.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/new_year.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Drinks/new_year.rsi/sbiten_cinnamon_lemon.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/new_year.rsi/warm_tea_cinnamon_lemon.png
Labels: Changes: Sprites, Changes: Localization, No C#

#151 Принтер
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/paper/doc-printer.ftl
  Resources/Prototypes/ADT/Entities/Objects/Misc/printerdocument.yml
  Resources/Prototypes/Entities/Objects/Misc/paper.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Textures/ADT/Structures/Machines/printer.rsi/building.png
  Resources/Textures/ADT/Structures/Machines/printer.rsi/icon.png
  Resources/Textures/ADT/Structures/Machines/printer.rsi/idle.png
  Resources/Textures/ADT/Structures/Machines/printer.rsi/inserting.png
  Resources/Textures/ADT/Structures/Machines/printer.rsi/meta.json
  Resources/Textures/ADT/Structures/Machines/printer.rsi/panel.png
Labels: Changes: Sprites, Changes: Localization, No C#, Status: Needs Review

#207 Ежедневные костыли от асеровича
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpsuit.yml
  Resources/Prototypes/Catalog/Fills/Crates/fun.yml
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/pickaxe.yml
  Resources/Prototypes/Entities/Structures/Windows/mining.yml
  Resources/Prototypes/Entities/Structures/Windows/plasma.yml
  Resources/Prototypes/Entities/Structures/Windows/reinforced.yml
  Resources/Prototypes/Entities/Structures/Windows/ruranium.yml
  Resources/Prototypes/Entities/Structures/Windows/shuttle.yml
  Resources/Prototypes/Entities/Structures/Windows/uranium.yml
  Resources/Prototypes/Entities/Structures/Windows/window.yml
  Resources/Prototypes/NES/Nes_frostpunk.yml
  Resources/Prototypes/NES/Nes_furniture.yml
  Resources/Prototypes/NES/Nes_toys.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/shadowkin.yml
  Resources/Prototypes/SimpleStation14/Species/shadowkin.yml
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/casima_corsete.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/casima_corsete.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/casima_corsete.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/casima_corsete.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/casima_corsete.rsi/meta.json
  Resources/Textures/NES/Aerogel.rsi/Aerogel.png
  Resources/Textures/NES/Aerogel.rsi/RudaAerogel.png
  Resources/Textures/NES/Aerogel.rsi/RudaTitan.png
  Resources/Textures/NES/Aerogel.rsi/TitanPlastina.png
  Resources/Textures/NES/Aerogel.rsi/meta.json
  Resources/Textures/NES/Flags.rsi/FederationFlag.png
  Resources/Textures/NES/Flags.rsi/meta.json
  Resources/Textures/NES/Toys.rsi/Shadowkin.png
  Resources/Textures/NES/Toys.rsi/meta.json
  Resources/Textures/Parallaxes/NES/Frontier.png
  Resources/Textures/Parallaxes/NES/GreenParallax2.png
  Resources/Textures/Parallaxes/NES/MirStationParallaxBG.png
  Resources/Textures/Parallaxes/NES/PurpleParallax2.png
Labels: Changes: Sprites, No C#

#209 Update doc-printer.ftl
  Resources/Locale/ru-RU/ADT/paper/doc-printer.ftl
Labels: Changes: Localization, No C#

#210 Minor update
  Resources/Prototypes/ADT/Damage/ADTmodifiers.yml
  Resources/Prototypes/ADT/Drask/Mobs/Species/Drask.yml
  Resources/Prototypes/ADT/Entities/Objects/Specific/Medical/patch.yml
  Resources/Prototypes/ADT/Reagents/patch_medicine.yml
Labels: No C#

#212 добавлен майндшилд следователю сб
  Resources/Prototypes/ADT/Roles/Jobs/SecInvestigator/investigator.yml
Labels: No C#

#213 лифчик стал корсетом.
  Resources/Locale/ru-RU/ADT/Clothing/OuterClothing/Underwear/underwear.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Uniform/jumpsuits.ftl
  Resources/Prototypes/ADT/Catalog/VendingMachines/Inventories/newyearmat.yml
  Resources/Prototypes/ADT/Entities/Clothing/Underwear/Top.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpsuit.yml
Labels: Changes: Localization, No C#

#214 Minor update 2
  Resources/Prototypes/ADT/Drask/Mobs/Species/Drask.yml
  Resources/Prototypes/ADT/Entities/Objects/Specific/Medical/patch.yml
  Resources/Textures/ADT/Mobs/Drask/parts.rsi/torso_f.png
  Resources/Textures/ADT/Mobs/Drask/parts.rsi/torso_m.png
Labels: Changes: Sprites, No C#

#215 небольшие фиксы
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/interaction/interaction-popup-component.ftl
  Resources/Prototypes/NES/Nes_mobs.yml
  Resources/Textures/NES/Mobs/garfield.rsi/cat.png
  Resources/Textures/NES/Mobs/garfield.rsi/cat_dead.png
  Resources/Textures/NES/Mobs/garfield.rsi/cat_deadcollar.png
  Resources/Textures/NES/Mobs/garfield.rsi/cat_deadtag.png
  Resources/Textures/NES/Mobs/garfield.rsi/cat_rest.png
  Resources/Textures/NES/Mobs/garfield.rsi/cat_restcollar.png
  Resources/Textures/NES/Mobs/garfield.rsi/cat_resttag.png
  Resources/Textures/NES/Mobs/garfield.rsi/cat_sit.png
  Resources/Textures/NES/Mobs/garfield.rsi/catcollar.png
  Resources/Textures/NES/Mobs/garfield.rsi/cattag.png
  Resources/Textures/NES/Mobs/garfield.rsi/meta.json
  Resources/Textures/Parallaxes/NES/NebulaRed.png
Labels: Changes: Sprites, Changes: Localization, No C#

#216 Прослушка для ивента
  Resources/Locale/ru-RU/ADT/Objects/Misc/wiretapping.ftl
  Resources/Prototypes/ADT/Entities/Objects/Misc/wiretapping.yml
  Resources/Prototypes/ADT/Entities/Objects/Specific/Medical/patch.yml
  Resources/Textures/ADT/Objects/Misc/wiretapping.rsi/meta.json
  Resources/Textures/ADT/Objects/Misc/wiretapping.rsi/wiretapping.png
Labels: Changes: Sprites, Changes: Localization, No C#

#217 Тяжелый боец ОБР
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Content.Shared/CCVar/CCVars.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Clothing/OuterClothing/Armor/ert_heavy.ftl
  Resources/Locale/ru-RU/ADT/Clothing/halloween.ftl
  Resources/Locale/ru-RU/ADT/Fills/cargo.ftl
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Food/new_year_food.ftl
  Resources/Locale/ru-RU/corvax/station-goal/station-goal-component.ftl
  Resources/Locale/ru-RU/info/server-info.ftl
  Resources/Locale/ru-RU/server-info/info-links.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/objects/weapons/guns/smgs/smgs.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/player/humanoid.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
  Resources/Maps/NewYear/adtny_cluster.yml
  Resources/Prototypes/ADT/Catalog/Fills/Cargo/cargo_food.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/Hardsuits/heavy_ERT.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/new_year.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/ert_shield.yml
  Resources/Prototypes/Datasets/tips.yml
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Entities/Objects/Shields/shields.yml
  Resources/Prototypes/Maps/Pools/default.yml
  Resources/Prototypes/Maps/adt_ny_cluster.yml
  Resources/Prototypes/Roles/Jobs/Fun/emergencyresponseteam.yml
  Resources/Textures/ADT/Clothing/Head/Hardsuits/heavyERT.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/heavyERT.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/heavyERT.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hardsuits/heavyERT.rsi/off-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/heavyERT.rsi/on-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/heavyERT.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/heavyERT.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/heavyERT.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/heavyERT.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/heavyERT.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Food/new-year/chocogorilla.rsi/chocogorilla.png
  Resources/Textures/ADT/Objects/Consumable/Food/new-year/chocogorilla.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Food/new-year/newyearsnack.rsi/box1.png
  Resources/Textures/ADT/Objects/Consumable/Food/new-year/newyearsnack.rsi/box2.png
  Resources/Textures/ADT/Objects/Consumable/Food/new-year/newyearsnack.rsi/box3.png
  Resources/Textures/ADT/Objects/Weapons/Melee/ert_heavy_shield.rsi/ert-icon.png
  Resources/Textures/ADT/Objects/Weapons/Melee/ert_heavy_shield.rsi/ert-inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/ert_heavy_shield.rsi/ert-inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Melee/ert_heavy_shield.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, Changes: Map

#218 мелкие правки
  Resources/ServerInfo/ADT/srp/KorporateZakonCritical.xml
  Resources/ServerInfo/ADT/srp/KorporateZakonMedium.xml
  Resources/ServerInfo/ADT/srp/KorporateZakonSerious.xml
  Resources/ServerInfo/ADT/srp/KorporateZakonSuperHeavy.xml
Labels: No C#

#219 Звук для ивента
  Resources/Audio/ADT/Fun/Frostpunk.ogg
Labels: No C#

#220 Мандарин+
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/newYear/mandarin.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/mandarin.yml
  Resources/Textures/ADT/Objects/Specific/Hydroponics/mandarin.rsi/meta.json
  Resources/Textures/ADT/Objects/Specific/Hydroponics/mandarin.rsi/peeledprod.png
Labels: Changes: Sprites, Changes: Localization, No C#

#221 Мелкие фиксы
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/ADT/Novakid/Mobs/Species/novakid.yml
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
  Resources/Prototypes/Entities/Structures/Machines/artifact_analyzer.yml
  Resources/Prototypes/Entities/Structures/Power/apc.yml
  Resources/Prototypes/Entities/Structures/Power/smes.yml
  Resources/Prototypes/Entities/Structures/Power/substation.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/Roles/Jobs/Engineering/senior_engineer.yml
Labels: No C#

#222 Двигатели и ебеньград
  Content.Shared/CCVar/CCVars.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/en-US/ss14-ru/prototypes/adt/vulpkanin/entities/mobs/player/Vulpkanin.ftl
  Resources/Maps/Shuttles/cargo.yml
  Resources/Maps/Shuttles/mining.yml
  Resources/Prototypes/ADT/Vulpkanin/Entities/Mobs/Species/Vulpkanin.yml
  Resources/Prototypes/Entities/Structures/Shuttles/thrusters.yml
  Resources/Prototypes/NES/Nes_frostpunk.yml
  Resources/Prototypes/NES/Nes_toys.yml
  Resources/Prototypes/NES/Shuttles/Nes_shuttles.yml
  Resources/Prototypes/Parallaxes/NES_parallaxes.yml
  Resources/Textures/NES/Frostpunk/ParCore.rsi/ParReactor.png
  Resources/Textures/NES/Frostpunk/ParCore.rsi/meta.json
  Resources/Textures/NES/Frostpunk/ParGenik.rsi/HeatTransferPipes-2.png
  Resources/Textures/NES/Frostpunk/ParGenik.rsi/PotectiveGrilles-3.png
  Resources/Textures/NES/Frostpunk/ParGenik.rsi/box_1.png
  Resources/Textures/NES/Frostpunk/ParGenik.rsi/box_2.png
  Resources/Textures/NES/Frostpunk/ParGenik.rsi/meta.json
  Resources/Textures/NES/Frostpunk/ParGenik.rsi/portgen0.png
  Resources/Textures/NES/Frostpunk/ParGenik.rsi/portgen0on.png
  Resources/Textures/NES/Frostpunk/ParGenik.rsi/portgen_on_unlit.png
  Resources/Textures/NES/Shuttle/ZETA_thruster.rsi/base.png
  Resources/Textures/NES/Shuttle/ZETA_thruster.rsi/meta.json
  Resources/Textures/NES/Shuttle/ZETA_thruster.rsi/thrust.png
  Resources/Textures/NES/Shuttle/ZETA_thruster.rsi/thrust_burn_unshaded.png
  Resources/Textures/Parallaxes/NES/planet.png
  Resources/Textures/Parallaxes/NES/planet4.png
  Resources/Textures/Structures/Doors/Airlocks/Glass/mining.rsi/meta.json
  Resources/Textures/Structures/Doors/Airlocks/Glass/mining.rsi/open_unlit.png
  Resources/Textures/Structures/Doors/Airlocks/Standard/mining.rsi/meta.json
  Resources/Textures/Structures/Doors/Airlocks/Standard/mining.rsi/open_unlit.png
Labels: Changes: Sprites, Changes: Localization

#224 Фикс габарита карго-шаттла
  Resources/Maps/Shuttles/cargo.yml
  Resources/Maps/Shuttles/mining.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/new_year.yml
  Resources/ServerInfo/ADT/NewRecipes.xml
Labels: No C#

#226 Фиксы
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/softsuits.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/wintercoats.yml
  Resources/Prototypes/Entities/Clothing/Shoes/boots.yml
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Labels: No C#

#227 Мелкая обнова.
  Content.Client/UserInterface/Systems/Bwoink/AHelpUIController.cs
  Content.Server/Corvax/ChatFilter/ChatSystem.cs
  Resources/Audio/Effects/adminhelpbread4.ogg
  Resources/Locale/ru-RU/ADT/Objects/Fan/plushie_aidan.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_liexer.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_ma.png
Labels: Changes: Sprites, Changes: Localization

#228 EmotePanel gets 3 new emotes.
  Content.Server/ADT/EmotePanel/EmotePanelSystem.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/Sirena/Actions/emotes.yml
  Resources/Textures/Interface/Emotes/jump.png
  Resources/Textures/Interface/Emotes/somersaults.png
  Resources/Textures/Interface/Emotes/spin.png
Labels: Status: Needs Review

#231 Удалён неиспользуемый файл, вызывавший ошибку у некоторых пользователей.
  Resources/Prototypes/SimpleStation14/Shaders/shaders.yml
  Resources/Textures/SimpleStation14/Shaders/ethereal.swsl
Labels: No C#

#232 Изменил выбор режимов и вес режимов в секрете
  Resources/Prototypes/game_presets.yml
  Resources/Prototypes/secret_weights.yml
Labels: No C#

#233 Фиксы
  Content.Client/UserInterface/Systems/Bwoink/AHelpUIController.cs
  Resources/Locale/ru-RU/ADT/Clothing/boots.ftl
  Resources/Locale/ru-RU/ADT/Clothing/outerclothing.ftl
  Resources/Locale/ru-RU/ADT/Objects/Misc/misc.ftl
  Resources/Locale/ru-RU/ADT/Objects/specific/anomaly.ftl
  Resources/Locale/ru-RU/ADT/access/access.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/lixon/cc/VKF_Representative.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/vests.ftl
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/Sirena/Actions/emotes.yml
  Resources/ServerInfo/ADT/srp/SrpMedicIntern.xml
Labels: Changes: Localization

#238 Взрывозащита сумок и немного фиксов
  Content.Server/Explosion/Components/ExplosionResistanceComponent.cs
  Content.Server/Explosion/EntitySystems/ExplosionSystem.Processing.cs
  Content.Server/Explosion/EntitySystems/ExplosionSystem.cs
  Content.Server/Storage/EntitySystems/EntityStorageSystem.cs
  Content.Shared/Storage/Components/SharedEntityStorageComponent.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/en-US/explosions/explosion-resistance.ftl
  Resources/Prototypes/Catalog/Fills/Crates/salvage.yml
  Resources/Prototypes/Entities/Clothing/Back/backpacks.yml
  Resources/Prototypes/Entities/Clothing/Back/duffel.yml
  Resources/Prototypes/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/Entities/Clothing/base_clothing.yml
  Resources/Prototypes/Procedural/salvage_loot.yml
Labels: Changes: Localization

#240 Набор исправлений для КПБ.
  Content.Server/SimpleStation14/Radio/IntrinsicRadioKeySystem.cs
  Resources/Locale/ru-RU/SimpleStation14/Content/Silicons/siliconChargers.ftl
  Resources/Locale/ru-RU/SimpleStation14/prototypes/entities/mobs/Player/ipc.ftl
  Resources/Locale/ru-RU/SimpleStation14/prototypes/entities/structures/machines/silicon_chargers.ftl
  Resources/Prototypes/Entities/Objects/Tools/cable_coils.yml
  Resources/Prototypes/SimpleStation14/Damage/containers.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/ipc.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/silicon_base.yml
  Resources/Prototypes/SimpleStation14/Entities/Structures/Machines/silicon_chargers.yml
Labels: Changes: Localization

#239 Небольшие подарки агентам
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Catalog/fills/syndicate.ftl
  Resources/Locale/ru-RU/ADT/Catalog/store/uplink.ftl
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/Guns.ftl
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Melee/melee.ftl
  Resources/Locale/ru-RU/ADT/Objects/specific/medstuff.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Syndicate.yml
  Resources/Prototypes/ADT/Catalog/uplink.yml
  Resources/Prototypes/ADT/Entities/Objects/Specific/Medical/Syndicate.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Revolvers/Syndicate.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/Syndicate.yml
Labels: Changes: Localization, No C#

#242 Лазган со сменной батареей
  Content.Server/GameTicking/Rules/Components/NukeopsRuleComponent.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/Guns.ftl
  Resources/Locale/ru-RU/prototypes/catalog/cargo/cargo-armory.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/crates/armory.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Cargo/cargo_armory.yml
  Resources/Prototypes/ADT/Catalog/Fills/Crates/armory.yml
  Resources/Prototypes/ADT/Entities/Objects/Power/powercell.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Ammunition/Magazines/pistol.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Ammunition/Magazines/rifle_ext.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Battery/battery_gun.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Projectiles/hitscan.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Rifels/rifles.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Recipes/Lathes/security.yml
  Resources/Prototypes/Research/arsenal.yml
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pmm_mag.rsi/base.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pmm_mag.rsi/mag-1.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pmm_mag.rsi/mag-2.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pmm_mag.rsi/mag-3.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pmm_mag.rsi/mag-4.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pmm_mag.rsi/mag-5.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pmm_mag.rsi/mag-6.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pmm_mag.rsi/mag-7.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pmm_mag.rsi/mag-8.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pmm_mag.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pmm_mag.rsi/practice.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pmm_mag.rsi/rubber.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Rifle/ar12_mag.rsi/base.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Rifle/ar12_mag.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Rifle/ar12_mag.rsi/mag-1.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Rifle/ar12_mag.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Rifle/ar12_mag.rsi/practice.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/Rifle/ar12_mag.rsi/rubber.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/lasgunbattery.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/lasgunbattery.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/salr36.rsi/base.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/salr36.rsi/equipped-BACKPACK.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/salr36.rsi/equipped-SUITSTORAGE.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/salr36.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/salr36.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/salr36.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/salr36.rsi/mag-0.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/salr36.rsi/mag-1.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/salr36.rsi/mag-2.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/salr36.rsi/mag-3.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/salr36.rsi/mag-4.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/salr36.rsi/mag-unshaded-0.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/salr36.rsi/mag-unshaded-1.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/salr36.rsi/mag-unshaded-2.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/salr36.rsi/mag-unshaded-3.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/salr36.rsi/mag-unshaded-4.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/salr36.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Guns/Projectiles/bluelaser.rsi/beam.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Projectiles/bluelaser.rsi/impact_laser.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Projectiles/bluelaser.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Guns/Projectiles/bluelaser.rsi/muzzle_laser.png
Labels: Changes: Sprites, Changes: Localization

#243 Нерф трости дробовика
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Revolvers/Syndicate.yml
Labels: No C#

#245 Добавил дюратканевый дуфель баг
  Resources/Locale/ru-RU/ADT/Clothing/Back/Backpack.ftl
  Resources/Locale/ru-RU/corvax/barsign/barsign-component.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Back/Duffel.yml
  Resources/Prototypes/ADT/Recipes/Construction/Graph/Clothing.yml
  Resources/Prototypes/ADT/Recipes/Construction/Graph/clothing/durathead.yml
  Resources/Prototypes/Entities/Structures/Wallmounts/Signs/bar_sign.yml
  Resources/Prototypes/bar_signs.yml
  Resources/Textures/ADT/Clothing/Back/Duffel_Durathead.rsi/equipped-BACKPACK.png
  Resources/Textures/ADT/Clothing/Back/Duffel_Durathead.rsi/icon.png
  Resources/Textures/ADT/Clothing/Back/Duffel_Durathead.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Back/Duffel_Durathead.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Back/Duffel_Durathead.rsi/meta.json
  Resources/Textures/Structures/Wallmounts/barsign.rsi/meta.json
  Resources/Textures/Structures/Wallmounts/barsign.rsi/monkeytime.png
Labels: Changes: Sprites, Changes: Localization, No C#

#247 fix error
  Resources/Maps/Salvage/ADT/poligon.yml
  Resources/Maps/Shuttles/escape_pod_security.yml
  Resources/Prototypes/ADT/Entities/Clothing/Shoes/Boots.yml
  Resources/Prototypes/Corvax/Maps/Pools/corvax.yml
  Resources/Prototypes/Corvax/Maps/Pools/default.yml
  Resources/Prototypes/Corvax/Maps/avrite.yml
  Resources/Prototypes/Corvax/Maps/ishimura.yml
  Resources/Prototypes/Entities/Clothing/Shoes/boots.yml
  Resources/Prototypes/Maps/salvage.yml
Labels: No C#, Changes: Map

#246 Шаттлы и джей джей
  Content.Server/GameTicking/Rules/Components/NukeopsRuleComponent.cs
  Content.Server/Shuttles/Components/ShuttleComponent.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/communications/communications-console-component.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/objectives/traitor.ftl
  Resources/Maps/Shuttles/SYND_Karneline.yml
  Resources/Maps/centcomm.yml
  Resources/Prototypes/ADT/KD/Cargo/GravityForCargo.yml
  Resources/Prototypes/Entities/Structures/Machines/gravity_generator.yml
  Resources/Prototypes/Entities/Structures/Windows/rplasma.yml
  Resources/Prototypes/NES/Nes_armor.yml
  Resources/Prototypes/NES/Nes_clotching.yml
  Resources/Prototypes/NES/Nes_frostpunk.yml
  Resources/Prototypes/NES/Nes_furniture.yml
  Resources/Prototypes/NES/Nes_gears.yml
  Resources/Prototypes/NES/Nes_generator.yml
  Resources/Prototypes/NES/Nes_mobs.yml
  Resources/Prototypes/NES/Shuttles/Nes_shuttles.yml
  Resources/Prototypes/Objectives/objectiveGroups.yml
  Resources/Prototypes/Objectives/traitor.yml
  Resources/Textures/NES/GraviCore.rsi/GraviCore.png
  Resources/Textures/NES/GraviCore.rsi/meta.json
  Resources/Textures/NES/Melee/DV_e_cutlass.rsi/e_cutlass.png
  Resources/Textures/NES/Melee/DV_e_cutlass.rsi/e_cutlass_blade.png
  Resources/Textures/NES/Melee/DV_e_cutlass.rsi/icon.png
  Resources/Textures/NES/Melee/DV_e_cutlass.rsi/inhand-left-blade.png
  Resources/Textures/NES/Melee/DV_e_cutlass.rsi/inhand-left.png
  Resources/Textures/NES/Melee/DV_e_cutlass.rsi/inhand-right-blade.png
  Resources/Textures/NES/Melee/DV_e_cutlass.rsi/inhand-right.png
  Resources/Textures/NES/Melee/DV_e_cutlass.rsi/meta.json
  Resources/Textures/NES/Mobs/djay.rsi/djay.png
  Resources/Textures/NES/Mobs/djay.rsi/djay_ded.png
  Resources/Textures/NES/Mobs/djay.rsi/meta.json
  Resources/Textures/NES/Mobs/djay.rsi/syndie-djay.png
  Resources/Textures/NES/Mobs/djay.rsi/syndie-djay_ded.png
  Resources/Textures/NES/Railguns/mini_railgun.rsi/beam.png
  Resources/Textures/NES/Railguns/mini_railgun.rsi/emitter.png
  Resources/Textures/NES/Railguns/mini_railgun.rsi/lock.png
  Resources/Textures/NES/Railguns/mini_railgun.rsi/meta.json
  Resources/Textures/NES/Railguns/mini_railgun.rsi/projectile.png
  Resources/Textures/NES/Railguns/mini_railgun.rsi/underpowered.png
  Resources/Textures/NES/Railguns/mini_railgun.rsi/unlock.png
  Resources/Textures/NES/Spacesuits/Pirates_HardsuitArmor.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/NES/Spacesuits/Pirates_HardsuitArmor.rsi/icon.png
  Resources/Textures/NES/Spacesuits/Pirates_HardsuitArmor.rsi/inhand-left.png
  Resources/Textures/NES/Spacesuits/Pirates_HardsuitArmor.rsi/inhand-right.png
  Resources/Textures/NES/Spacesuits/Pirates_HardsuitArmor.rsi/meta.json
  Resources/Textures/NES/Spacesuits/Pirates_HardsuitHelmet.rsi/icon-flash.png
  Resources/Textures/NES/Spacesuits/Pirates_HardsuitHelmet.rsi/icon.png
  Resources/Textures/NES/Spacesuits/Pirates_HardsuitHelmet.rsi/meta.json
  Resources/Textures/NES/Spacesuits/Pirates_HardsuitHelmet.rsi/off-equipped-HELMET.png
  Resources/Textures/NES/Spacesuits/Pirates_HardsuitHelmet.rsi/off-inhand-left.png
  Resources/Textures/NES/Spacesuits/Pirates_HardsuitHelmet.rsi/off-inhand-right.png
  Resources/Textures/NES/Spacesuits/Pirates_HardsuitHelmet.rsi/on-equipped-HELMET.png
  Resources/Textures/NES/Spacesuits/Pirates_HardsuitHelmet.rsi/on-inhand-left.png
  Resources/Textures/NES/Spacesuits/Pirates_HardsuitHelmet.rsi/on-inhand-right.png
  Resources/Textures/NES/button.rsi/dead.png
  Resources/Textures/NES/button.rsi/meta.json
  Resources/Textures/NES/button.rsi/off.png
  Resources/Textures/NES/button.rsi/on.png
Labels: Changes: Sprites, Changes: Localization, Changes: Map

#248 monochromacy was added
  Content.Client/SimpleStation14/Overlays/Shaders/MonochromacyOverlay.cs
  Content.Client/SimpleStation14/Overlays/Systems/MonochromacySystem.cs
  Content.Shared/SimpleStation14/Traits/Components/MonochromacyComponent.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/traits/disabilities.ftl
  Resources/Prototypes/SimpleStation14/Traits/disabilities.yml
Labels: Changes: Localization

#253 Хачапури.
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Food/khacapuri.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/khachapuri.yml
  Resources/Prototypes/ADT/Recipes/Cooking/khachapuri_recipe.yml
  Resources/ServerInfo/ADT/NewRecipes.xml
  Resources/Textures/ADT/Objects/Consumable/Food/khachapuri.rsi/icon.png
  Resources/Textures/ADT/Objects/Consumable/Food/khachapuri.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#255 Локализация
  Resources/Locale/ru-RU/ame/components/ame-controller-component.ftl
  Resources/Locale/ru-RU/atmos/gas-analyzer-component.ftl
  Resources/Locale/ru-RU/components/power-monitoring-component.ftl
Labels: Changes: Localization, No C#

#256 Переводы
  Resources/Locale/ru-RU/ADT/Clothing/Eyes/hud.ftl
  Resources/Locale/ru-RU/ADT/Clothing/boots.ftl
  Resources/Locale/ru-RU/ADT/Luna/WeddingContentBouquets.ftl
  Resources/Locale/ru-RU/ADT/Luna/WeddingContentDresses.ftl
  Resources/Locale/ru-RU/ADT/Objects/structuries/storage/canisters/gas-canisters.ftl
  Resources/Locale/ru-RU/ADT/escape-menu/ui/options-menu.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/clothing/head/hats/ilisuim.ftl
  Resources/Prototypes/Entities/Clothing/Shoes/boots.yml
  Resources/ServerInfo/Guidebook/Survival.xml
  Resources/ServerInfo/Rules.txt
Labels: Changes: Localization, No C#

#258 Изменение шанса режимов
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/secret_weights.yml
Labels: No C#

#259 Химия
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/Recipes/Reactions/chemicals.yml
  Resources/Prototypes/Recipes/Reactions/medicine.yml
Labels: No C#

#260 Credits and music lobby
  Content.Client/Credits/CreditsWindow.xaml.cs
  Resources/Audio/Lobby/attributions.yml
  Resources/Audio/Lobby/space_oddity.ogg
  Resources/Credits/ADTeam.txt
  Resources/Locale/ru-RU/credits/credits-window.ftl
  Resources/Prototypes/Entities/Structures/Power/smes.yml
  Resources/Prototypes/Entities/Structures/Power/substation.yml
  Resources/Prototypes/SoundCollections/lobby.yml
Labels: Changes: Localization, Changes: UI

#261 Всякая всячина.
  Resources/Audio/ADT/Items/Toys/soundshark.ogg
  Resources/Locale/ru-RU/ADT/Clothing/Uniform/turtleneck.ftl
  Resources/Locale/ru-RU/ADT/Fun/ADTtoys.ftl
  Resources/Locale/ru-RU/ADT/Objects/structuries/furniture/furniture.ftl
  Resources/Locale/ru-RU/reagents/meta/fun.ftl
  Resources/Locale/ru-RU/reagents/meta/medicine.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpskirt.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpsuit.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/ADT/Recipes/Lathes/clothing.yml
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Entities/Objects/Materials/Sheets/metal.yml
  Resources/Prototypes/InventoryTemplates/human_inventory_template.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/shark_inhand-left.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/shark_inhand-right.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/shark_mini_pink.png
Labels: Changes: Sprites, Changes: Localization, No C#

#262 Игрушки.
  Resources/Locale/ru-RU/ADT/Fun/ADTtoys.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_jungar.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_migel.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_teo.png
Labels: Changes: Sprites, Changes: Localization, No C#

#264 Переводы и стража для Нового Года
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Catalog/fills/syndicate.ftl
  Resources/Locale/ru-RU/ADT/Catalog/store/uplink.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Head/hats.ftl
  Resources/Locale/ru-RU/ADT/Clothing/outerclothing.ftl
  Resources/Locale/ru-RU/ADT/Objects/Fan/darts.ftl
  Resources/Locale/ru-RU/ADT/Objects/Mobs/animals.ftl
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Grenades/grenades.ftl
  Resources/Locale/ru-RU/ADT/Objects/specific/medstuff.ftl
  Resources/Locale/ru-RU/ADT/Objects/structuries/machines/chemistry_machines.ftl
  Resources/Locale/ru-RU/prototypes/catalog/cargo/cargo-cargo.ftl
  Resources/Locale/ru-RU/prototypes/catalog/cargo/cargo-engineering.ftl
  Resources/Locale/ru-RU/prototypes/catalog/cargo/cargo-livestock.ftl
  Resources/Locale/ru-RU/prototypes/catalog/cargo/cargo-materials.ftl
  Resources/Locale/ru-RU/prototypes/catalog/cargo/cargo-medical.ftl
  Resources/Locale/ru-RU/prototypes/catalog/cargo/cargo-security.ftl
  Resources/Locale/ru-RU/prototypes/catalog/cargo/cargo-service.ftl
  Resources/Locale/ru-RU/prototypes/catalog/fills/crates/cargo-crates.ftl
  Resources/Locale/ru-RU/prototypes/catalog/fills/crates/engineering-crates.ftl
  Resources/Locale/ru-RU/prototypes/catalog/fills/crates/livestock-crates.ftl
  Resources/Locale/ru-RU/prototypes/catalog/fills/crates/materials-crates.ftl
  Resources/Locale/ru-RU/prototypes/catalog/fills/crates/medical-crates.ftl
  Resources/Locale/ru-RU/prototypes/catalog/fills/crates/security-crates.ftl
  Resources/Locale/ru-RU/prototypes/catalog/fills/crates/service-crates.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/boxes/medical.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/decoration/crystals.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Cargo/cargo_armory.yml
  Resources/Prototypes/ADT/Entities/Mobs/guards_of_newyear.yml
  Resources/Prototypes/ADT/Entities/Objects/Specific/Medical/patch.yml
  Resources/Prototypes/Catalog/Cargo/cargo_engineering.yml
  Resources/Textures/ADT/Mobs/Animals/newyeargigarat.rsi/dead.png
  Resources/Textures/ADT/Mobs/Animals/newyeargigarat.rsi/icon.png
  Resources/Textures/ADT/Mobs/Animals/newyeargigarat.rsi/meta.json
  Resources/Textures/ADT/Mobs/Animals/newyeargigarat.rsi/newyeargigarat.png
  Resources/Textures/ADT/Mobs/Animals/newyeargorilla.rsi/dead.png
  Resources/Textures/ADT/Mobs/Animals/newyeargorilla.rsi/icon.png
  Resources/Textures/ADT/Mobs/Animals/newyeargorilla.rsi/meta.json
  Resources/Textures/ADT/Mobs/Animals/newyeargorilla.rsi/newyeargorilla.png
  Resources/Textures/Structures/Doors/Airlocks/Glass/centcomm.rsi/meta.json
  Resources/Textures/Structures/Doors/Airlocks/Glass/centcomm.rsi/open_unlit.png
  Resources/Textures/Structures/Doors/Airlocks/Standard/centcomm.rsi/meta.json
  Resources/Textures/Structures/Doors/Airlocks/Standard/centcomm.rsi/open_unlit.png
Labels: Changes: Sprites, Changes: Localization, No C#
