Repository xtray85/space_station, pull requests merged in 2023-11, with the labels that each got.

#76 фикс мобов для ивента
  Resources/Locale/ru-RU/ADT/Clothing/halloween.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Boxes/halloween_suit.yml
  Resources/Prototypes/ADT/Catalog/VendingMachines/Inventories/halloweenomat.yml
  Resources/Prototypes/ADT/Entities/Clothing/Masks/mask.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/halloween.yml
  Resources/Prototypes/ADT/Entities/Mobs/anomally_abomination.yml
  Resources/Prototypes/ADT/Entities/Structures/Specific/anomalies.yml
  Resources/Textures/ADT/Clothing/Mask/michael_myersmask.rsi/equipped-MASK.png
  Resources/Textures/ADT/Clothing/Mask/michael_myersmask.rsi/icon.png
  Resources/Textures/ADT/Clothing/Mask/michael_myersmask.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/Halloween/michael_suit.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/Halloween/michael_suit.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/Halloween/michael_suit.rsi/meta.json
  Resources/Textures/ADT/Objects/Storage/halloween_box.rsi/meta.json
  Resources/Textures/ADT/Objects/Storage/halloween_box.rsi/michael.png
Labels: Changes: Sprites, Changes: Localization, No C#

#77 Update2
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/ADT/Tajaran/Entities/Mobs/Species/Tajaran.yml
  Resources/Prototypes/ADT/Vulpkanin/Entities/Mobs/Species/Vulpkanin.yml
  Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
  Resources/Prototypes/Entities/Mobs/Species/slime.yml
  Resources/ServerInfo/ADT/srp/KorporateZakonSerious.xml
  Resources/ServerInfo/ADT/srp/KorporateZakonSuperHeavy.xml
  Resources/ServerInfo/ADT/srp/SrpLawyer.xml
  Resources/ServerInfo/ADT/srp/SrpLawyerIIA.xml
  Resources/ServerInfo/ADT/srp/SrpLawyerLawyers.xml
  Resources/ServerInfo/ADT/srp/SrpLawyerMagistrat.xml
Labels: No C#

#78 Кровоостанавливающая пудра,Сульфадиазин серебра,Пластыри
  Resources/Locale/ru-RU/ADT/Reagents/patch_medicine.ftl
  Resources/Prototypes/ADT/Entities/Objects/Specific/Medical/patch.yml
  Resources/Prototypes/ADT/Reagents/patch_medicine.yml
  Resources/Prototypes/ADT/Recipes/Reactions/patch_medicine_recipe.yml
  Resources/Prototypes/Catalog/Fills/Lockers/medical.yml
Labels: Changes: Localization, No C#, Status: Needs Review

#79 Респрайт слаймов
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Clothing/halloween.ftl
  Resources/Locale/ru-RU/ADT/Objects/Fan/plushie_aidan.ftl
  Resources/Locale/ru-RU/ADT/Objects/structuries/decoration/wedding_arc.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/ADT/Entities/Structures/Decorations/wedding_arc.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_timrika.png
  Resources/Textures/ADT/Structures/Decoration/wedding_ark.rsi/arc.png
  Resources/Textures/ADT/Structures/Decoration/wedding_ark.rsi/meta.json
  Resources/Textures/Mobs/Aliens/slimes.rsi/blue_adult_slime.png
  Resources/Textures/Mobs/Aliens/slimes.rsi/blue_adult_slime_dead.png
  Resources/Textures/Mobs/Aliens/slimes.rsi/green_adult_slime.png
  Resources/Textures/Mobs/Aliens/slimes.rsi/green_adult_slime_dead.png
  Resources/Textures/Mobs/Aliens/slimes.rsi/meta.json
  Resources/Textures/Mobs/Aliens/slimes.rsi/yellow_adult_slime.png
  Resources/Textures/Mobs/Aliens/slimes.rsi/yellow_adult_slime_dead.png
Labels: Changes: Sprites, Changes: Localization, No C#

#81 Фиксы от 4.11
  Content.Server/Chat/Managers/ChatSanitizationManager.cs
  Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Fills/cargo.ftl
  Resources/Locale/ru-RU/ADT/Objects/Device/Circuitboard.ftl
  Resources/Locale/ru-RU/ADT/Objects/Device/igniter.ftl
  Resources/Locale/ru-RU/ADT/Objects/Fan/darts.ftl
  Resources/Locale/ru-RU/ADT/Objects/Misc/consumable.ftl
  Resources/Locale/ru-RU/ADT/Objects/Misc/mindshield_implant.ftl
  Resources/Locale/ru-RU/prototypes/catalog/cargo/cargo-vending.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/kd/entites/storage/RingStorage.ftl
  Resources/Locale/ru-RU/xenoarchaeology/artifact-hints.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Shoes/Boots.yml
  Resources/Prototypes/ADT/Tajaran/Entities/Mobs/Species/Tajaran.yml
  Resources/Prototypes/ADT/Vulpkanin/Entities/Mobs/Species/Vulpkanin.yml
  Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
  Resources/Prototypes/Entities/Mobs/Species/slime.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
Labels: Changes: Localization

#84 Новые цели синдиката
  Resources/Prototypes/ADT/Objectives/traitor.yml
Labels: No C#

#88 фикс вместительностей некоторых хранилищ
  Resources/Prototypes/ADT/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/ADT/Entities/Objects/Specific/Medical/defib.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/telescopic_baton.yml
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/backpack.yml
Labels: No C#

#89 Борги теперь имеются правильный набор законов
  Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
  Resources/Prototypes/Entities/Mobs/Cyborgs/borg_chassis.yml
Labels: No C#

#90 Исправления и дополнения на Таяров
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Markings/tajaranmarkings.ftl
  Resources/Prototypes/ADT/Tajaran/Entities/Mobs/Customization/Markings/Tajaran.yml
  Resources/Prototypes/ADT/Tajaran/Species/Tajaran.yml
  Resources/Textures/Mobs/Customization/Tajaran/tajaran_overlay.rsi/meta.json
  Resources/Textures/Mobs/Customization/Tajaran/tajaran_overlay.rsi/points.png
  Resources/Textures/Mobs/Customization/Tajaran/tajaran_parts.rsi/gradient_LHand.png
  Resources/Textures/Mobs/Customization/Tajaran/tajaran_parts.rsi/gradient_LLeg.png
  Resources/Textures/Mobs/Customization/Tajaran/tajaran_parts.rsi/gradient_RHand.png
  Resources/Textures/Mobs/Customization/Tajaran/tajaran_parts.rsi/gradient_RLeg.png
  Resources/Textures/Mobs/Customization/Tajaran/tajaran_parts.rsi/meta.json
  Resources/Textures/Mobs/Customization/Tajaran/tajaran_parts.rsi/points.png
  Resources/Textures/Mobs/Species/CatSkin/parts.rsi/l_leg.png
  Resources/Textures/Mobs/Species/CatSkin/parts.rsi/r_foot.png
  Resources/Textures/Mobs/Species/CatSkin/parts.rsi/r_leg.png
Labels: Changes: Sprites, Changes: Localization, No C#

#95 Звукогенераторы блят
  Resources/Audio/ADT/SoundGen/budilnik.ogg
  Resources/Audio/ADT/SoundGen/destruction_1.ogg
  Resources/Audio/ADT/SoundGen/destruction_2.ogg
  Resources/Audio/ADT/SoundGen/destruction_3.ogg
  Resources/Audio/ADT/SoundGen/dungeon_ambient_scary.ogg
  Resources/Audio/ADT/SoundGen/factory_ambient.ogg
  Resources/Audio/ADT/SoundGen/hit.ogg
  Resources/Audio/ADT/SoundGen/moving_objects_ambient_scary.ogg
  Resources/Audio/ADT/SoundGen/pianino_chord_sudden.ogg
  Resources/Audio/ADT/SoundGen/reverse_dissolve_scary.ogg
  Resources/Audio/ADT/SoundGen/shaft_water.ogg
  Resources/Audio/ADT/SoundGen/short_ambient_scary.ogg
  Resources/Prototypes/ADT/SoundGen/soundgenerators.yml
  Resources/Textures/ADT/Objects/Misc/soundgen.rsi/icon.png
  Resources/Textures/ADT/Objects/Misc/soundgen.rsi/meta.json
Labels: Changes: Sprites, No C#

#96 микро-микро дополнение, почему бы и нет.
  Resources/Locale/ru-RU/reagents/meta/consumable/drink/drinks.ftl
  Resources/Textures/Clothing/OuterClothing/Suits/rad.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Clothing/OuterClothing/Suits/rad.rsi/inhand-left.png
  Resources/Textures/Clothing/OuterClothing/Suits/rad.rsi/inhand-right.png
Labels: Changes: Sprites, Changes: Localization, No C#

#97 Update-3
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Clothing/Hands/gloves.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Head/hats.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Neck/cloak.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Neck/scarf.ftl
  Resources/Locale/ru-RU/ADT/Clothing/OuterClothing/furcoat.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Uniform/jumpsuits.ftl
  Resources/Locale/ru-RU/ADT/Clothing/boots.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Hands/gloves.yml
  Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/hats.yml
  Resources/Prototypes/ADT/Entities/Clothing/Neck/manties_chaplain.yml
  Resources/Prototypes/ADT/Entities/Clothing/Neck/scarfs.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/FunOuterClothing.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/rasy_chaplain.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpskirt.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/chapel.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/chefdrobe.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/janidrobe.yml
  Resources/Prototypes/radio_channels.yml
  Resources/Textures/ADT/Clothing/Hands/Gloves/blackdams_gloves.rsi/equipped-HAND.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/blackdams_gloves.rsi/icon.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/blackdams_gloves.rsi/meta.json
  Resources/Textures/ADT/Clothing/Hands/Gloves/janitor_groves.rsi/equipped-HAND.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/janitor_groves.rsi/icon.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/janitor_groves.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/janitor_groves.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/janitor_groves.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hats/hat_povar.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/hat_povar.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/hat_povar.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Head/Hats/hat_povar.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Head/Hats/hat_povar.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hats/hat_zakolka.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/hat_zakolka.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/hat_zakolka.rsi/meta.json
  Resources/Textures/ADT/Clothing/Neck/Cloaks/manties_chaplain.rsi/equipped-NECK.png
  Resources/Textures/ADT/Clothing/Neck/Cloaks/manties_chaplain.rsi/icon.png
  Resources/Textures/ADT/Clothing/Neck/Cloaks/manties_chaplain.rsi/meta.json
  Resources/Textures/ADT/Clothing/Neck/chefpovarfio.rsi/equipped-NECK.png
  Resources/Textures/ADT/Clothing/Neck/chefpovarfio.rsi/icon.png
  Resources/Textures/ADT/Clothing/Neck/chefpovarfio.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Suits/chefpovar_outer.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Suits/chefpovar_outer.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Suits/chefpovar_outer.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Suits/rasy_chaplain.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Suits/rasy_chaplain.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Suits/rasy_chaplain.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Suits/rasy_chaplain.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Suits/rasy_chaplain.rsi/meta.json
  Resources/Textures/ADT/Clothing/Shoes/Boots/golden_heels.rsi/equipped-FEET-Tajaran.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/golden_heels.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/shortdressblackgold.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/shortdressblackgold.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/shortdressblackgold.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/captain.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/captain.rsi/icon.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/chaplain.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/chaplain.rsi/icon.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/hop.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/hop.rsi/icon.png
Labels: Changes: Sprites, Changes: Localization, No C#

#98 Sound
  .github/rsi-schema.json
  Resources/Audio/ADT/Friskis/blast.ogg
  Resources/Audio/ADT/Friskis/pomehi.ogg
  Resources/Audio/ADT/Friskis/trevoga.ogg
  Resources/Audio/ADT/Friskis/trevoga2.ogg
  Resources/Audio/Lobby/The_Wrong_Party.ogg
  Resources/Audio/Lobby/attributions.yml
  Resources/Audio/Lobby/friday_night.ogg
  Resources/Prototypes/SoundCollections/lobby.yml
Labels: No C#

#100 Маленький фикс вместительности
  Resources/Prototypes/ADT/Entities/Objects/Misc/mini_fire_extinguisher.yml
  Resources/Prototypes/ADT/Entities/Objects/Specific/Medical/patch.yml
Labels: No C#

#101 Ящик плюшевых игрушек админов
  Resources/Locale/ru-RU/ADT/Fun/ADTtoys.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Crates/fun.yml
Labels: Changes: Localization, No C#

#104 Мелкое дополнение для Ниан
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/Mobs/animals.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Underwear/Bottom.yml
  Resources/Prototypes/ADT/Entities/Clothing/Underwear/Socks.yml
  Resources/Prototypes/ADT/Entities/Clothing/Underwear/Top.yml
Labels: Changes: Localization, No C#

#105 убрал гарант конопли,смэс лучше заряжается и лучше отдает
  Resources/Prototypes/ADT/Entities/Structures/Power/industrial.yml
  Resources/Prototypes/Catalog/Fills/Crates/botany.yml
Labels: No C#

#106 Update4
  Content.Client/Chat/UI/SpeechBubble.cs
  Content.Client/UserInterface/Systems/Chat/ChatUIController.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/medical/healing.ftl
Labels: Changes: Localization

#107 Фикс LOOC чата.
  Content.Client/Chat/UI/SpeechBubble.cs
  Content.Client/Options/UI/Tabs/GraphicsTab.xaml
  Content.Client/Options/UI/Tabs/GraphicsTab.xaml.cs
  Content.Shared/CCVar/CCVars.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/escape-menu/ui/options-menu.ftl
Labels: Changes: Localization, Changes: UI

#108 Фиксы для Dev
  Content.Server/Corvax/ChatFilter/ChatSystem.cs
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/clothing/masks/mask.ftl
  Resources/Prototypes/ADT/Entities/Clothing/FriskisSet/raven.yml
  Resources/Prototypes/ADT/Entities/Clothing/Masks/mask.yml
  Resources/Prototypes/ADT/Novakid/Customization/Markings/novakid.yml
  Resources/Prototypes/ADT/Novakid/Mobs/Species/novakid.yml
  Resources/Prototypes/Reagents/gases.yml
  Resources/Textures/ADT/Clothing/Mask/raven.rsi/meta.json
  Resources/Textures/ADT/Clothing/Mask/raven.rsi/up-equipped-MASK.png
Labels: DO NOT MERGE, Changes: Sprites, Changes: Localization

#110 настолько маленькие изменения, что даже описывать их смысла нет.
  Resources/Prototypes/ADT/Tajaran/Species/Tajaran.yml
  Resources/Textures/Mobs/Customization/Tajaran/tajaran_head.rsi/mane_head.png
  Resources/Textures/Mobs/Customization/Tajaran/tajaran_tail.rsi/wingler_1.png
Labels: Changes: Sprites, No C#

#111 update5
  Resources/Locale/ru-RU/ADT/Clothing/Head/hats.ftl
  Resources/Locale/ru-RU/ADT/Clothing/OuterClothing/Armor/blueshield_armor.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Uniform/jumpsuits.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
  Resources/Prototypes/ADT/Entities/Clothing/Head/hardsuit-helmets.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/hunger_games.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpsuit.yml
  Resources/Textures/ADT/Clothing/Head/Helmets/helmet_capitols.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Helmets/helmet_capitols.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Helmets/helmet_capitols.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Helmets/helmet_capitols.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Helmets/helmet_capitols.rsi/off-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Helmets/helmet_capitols.rsi/on-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/OuterClothing/Armor/armor_capitols.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Armor/armor_capitols.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Armor/armor_capitols.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/jumpsuit_capitols.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/jumpsuit_capitols.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/jumpsuit_capitols.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#109 Мелкие штуки и фиксы.
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/clothing/masks/mask.ftl
  Resources/Prototypes/ADT/Entities/Clothing/FriskisSet/raven.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/investigator_sjp.yml
  Resources/Prototypes/ADT/Novakid/Mobs/Player/novakid.yml
  Resources/Prototypes/ADT/Novakid/Species/novakid.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/satchel.yml
  Resources/Textures/ADT/Clothing/Hands/Gloves/raven_groves.rsi/equipped-HAND-unshaded.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/raven_groves.rsi/equipped-HAND.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/raven_groves.rsi/icon.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/raven_groves.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hats/raven_hat.rsi/equipped-HELMET-unshaded.png
  Resources/Textures/ADT/Clothing/Head/Hats/raven_hat.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/raven_hat.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/raven_hat.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Jackets/raven_overcoat.rsi/equipped-OUTERCLOTHING-unshaded.png
  Resources/Textures/ADT/Clothing/OuterClothing/Jackets/raven_overcoat.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Jackets/raven_overcoat.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Jackets/raven_overcoat.rsi/meta.json
  Resources/Textures/ADT/Clothing/Shoes/Boots/raven_shoes.rsi/equipped-FEET-unshaded.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/raven_shoes.rsi/equipped-FEET.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/raven_shoes.rsi/icon.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/raven_shoes.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/raven_suit.rsi/equipped-INNERCLOTHING-unshaded.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/raven_suit.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/raven_suit.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/raven_suit.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#112 Респрайты и мелкие фиксы
  Resources/Prototypes/ADT/Catalog/VendingMachines/Inventories/PrazatClothes.yml
  Resources/Textures/Clothing/Head/Hats/beret_brigmedic.rsi/equipped-HELMET-hamster.png
  Resources/Textures/Clothing/Head/Hats/beret_brigmedic.rsi/equipped-HELMET.png
  Resources/Textures/Clothing/Head/Hats/beret_brigmedic.rsi/icon.png
  Resources/Textures/Clothing/Head/Hats/beret_brigmedic.rsi/inhand-left.png
  Resources/Textures/Clothing/Head/Hats/beret_brigmedic.rsi/inhand-right.png
  Resources/Textures/Corvax/Clothing/Head/Hats/beret_security_medic.rsi/equipped-HELMET.png
  Resources/Textures/Corvax/Clothing/Head/Hats/beret_security_medic.rsi/icon.png
  Resources/Textures/Corvax/Clothing/Head/Hats/beret_security_medic.rsi/inhand-left.png
  Resources/Textures/Corvax/Clothing/Head/Hats/beret_security_medic.rsi/inhand-right.png
Labels: Changes: Sprites, No C#

#114 Разблокировка и доработка Новакидов. МЕРДЖИТЬ ТОЛЬКО 14 ЧИСЛА !
  Content.Shared/CCVar/CCVars.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Novakid/species.ftl
  Resources/Prototypes/ADT/Novakid/Body/Organs/novakid.yml
  Resources/Prototypes/ADT/Novakid/Body/Prototypes/novakid.yml
  Resources/Prototypes/ADT/Novakid/Customization/Markings/novakid.yml
  Resources/Prototypes/ADT/Novakid/Species/novakid.yml
  Resources/Prototypes/Entities/Objects/Shields/shields.yml
  Resources/Textures/ADT/Mobs/Novakid/custom.rsi/G_a.png
  Resources/Textures/ADT/Mobs/Novakid/custom.rsi/K.png
  Resources/Textures/ADT/Mobs/Novakid/custom.rsi/cone_a.png
  Resources/Textures/ADT/Mobs/Novakid/custom.rsi/connect_a.png
  Resources/Textures/ADT/Mobs/Novakid/custom.rsi/dot_a.png
  Resources/Textures/ADT/Mobs/Novakid/custom.rsi/dotline_a.png
  Resources/Textures/ADT/Mobs/Novakid/custom.rsi/eyes_a.png
  Resources/Textures/ADT/Mobs/Novakid/custom.rsi/house.png
  Resources/Textures/ADT/Mobs/Novakid/custom.rsi/lima-a.png
  Resources/Textures/ADT/Mobs/Novakid/custom.rsi/linedot_a.png
  Resources/Textures/ADT/Mobs/Novakid/custom.rsi/meta.json
  Resources/Textures/ADT/Mobs/Novakid/custom.rsi/omega_a.png
  Resources/Textures/ADT/Mobs/Novakid/custom.rsi/plus.png
  Resources/Textures/ADT/Mobs/Novakid/custom.rsi/rose.png
  Resources/Textures/ADT/Mobs/Novakid/custom.rsi/shatter_a.png
  Resources/Textures/ADT/Mobs/Novakid/custom.rsi/star_a.png
  Resources/Textures/ADT/Mobs/Novakid/custom.rsi/two-a.png
Labels: Changes: Sprites, Changes: Localization

#115 Мелкая обнова, новый анимированный плакат и респрайт ботаники.
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
  Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
  Resources/Textures/ADT/Objects/Decoration/dontsitdown.rsi/dontsitdown.png
  Resources/Textures/ADT/Objects/Decoration/dontsitdown.rsi/meta.json
  Resources/Textures/Clothing/Head/Bandanas/botany.rsi/equipped-HELMET-hamster.png
  Resources/Textures/Clothing/Head/Bandanas/botany.rsi/equipped-HELMET.png
  Resources/Textures/Clothing/Head/Bandanas/botany.rsi/icon.png
  Resources/Textures/Objects/Specific/Hydroponics/Equipment/plant_bag.rsi/equipped-BELT.png
  Resources/Textures/Objects/Specific/Hydroponics/Equipment/plant_bag.rsi/icon.png
  Resources/Textures/Objects/Specific/Hydroponics/Equipment/plant_bag.rsi/inhand-left.png
  Resources/Textures/Objects/Specific/Hydroponics/Equipment/plant_bag.rsi/inhand-right.png
  Resources/Textures/Objects/Tools/Hydroponics/clippers.rsi/icon.png
  Resources/Textures/Objects/Tools/Hydroponics/clippers.rsi/inhand-left.png
  Resources/Textures/Objects/Tools/Hydroponics/clippers.rsi/inhand-right.png
  Resources/Textures/Objects/Tools/Hydroponics/hatchet.rsi/icon.png
  Resources/Textures/Objects/Tools/Hydroponics/hatchet.rsi/inhand-left.png
  Resources/Textures/Objects/Tools/Hydroponics/hatchet.rsi/inhand-right.png
  Resources/Textures/Objects/Tools/Hydroponics/hoe.rsi/icon.png
  Resources/Textures/Objects/Tools/Hydroponics/hoe.rsi/inhand-left.png
  Resources/Textures/Objects/Tools/Hydroponics/hoe.rsi/inhand-right.png
  Resources/Textures/Objects/Tools/Hydroponics/scythe.rsi/equipped-BACKPACK.png
  Resources/Textures/Objects/Tools/Hydroponics/scythe.rsi/icon.png
  Resources/Textures/Objects/Tools/Hydroponics/scythe.rsi/inhand-left.png
  Resources/Textures/Objects/Tools/Hydroponics/scythe.rsi/inhand-right.png
  Resources/Textures/Objects/Tools/Hydroponics/spade.rsi/equipped-BELT.png
  Resources/Textures/Objects/Tools/Hydroponics/spade.rsi/icon.png
  Resources/Textures/Objects/Tools/Hydroponics/spade.rsi/inhand-left.png
  Resources/Textures/Objects/Tools/Hydroponics/spade.rsi/inhand-right.png
  Resources/Textures/Objects/Tools/Hydroponics/sprays.rsi/deathspray.png
  Resources/Textures/Objects/Tools/Hydroponics/sprays.rsi/inhand-left.png
  Resources/Textures/Objects/Tools/Hydroponics/sprays.rsi/inhand-right.png
  Resources/Textures/Objects/Tools/Hydroponics/sprays.rsi/nolabelspray.png
  Resources/Textures/Objects/Tools/Hydroponics/sprays.rsi/pestspray.png
  Resources/Textures/Objects/Tools/Hydroponics/sprays.rsi/plantbgone-inhand-left.png
  Resources/Textures/Objects/Tools/Hydroponics/sprays.rsi/plantbgone-inhand-right.png
  Resources/Textures/Objects/Tools/Hydroponics/sprays.rsi/plantbgone.png
  Resources/Textures/Objects/Tools/Hydroponics/sprays.rsi/weedspray.png
Labels: Changes: Sprites, Changes: Localization, No C#

#116 Фиксы контента ко дню рождения проекта
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
  Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
  Resources/Prototypes/Catalog/Fills/Boxes/general.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/posters.yml
  Resources/Prototypes/Entities/Structures/Machines/cloning_machine.yml
  Resources/Prototypes/Entities/Structures/Machines/medical_scanner.yml
  Resources/Textures/ADT/Clothing/Head/Hats/bluebirthdaycap.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/graybirthdaycap.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/ntbirthdaycap.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/pinkbirthdaycap.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/syndiebirthdaycap.rsi/icon.png
  Resources/Textures/Structures/Wallmounts/posters.rsi/meta.json
  Resources/Textures/Structures/Wallmounts/posters.rsi/poster_adtlustardeco_contraband.png
Labels: Changes: Sprites, Changes: Localization, No C#

#117 новакидная плазма
  Resources/Prototypes/Reagents/gases.yml
Labels: No C#

#118 HotFix отображения лиц Новакидов
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/ADT/Novakid/Customization/Markings/novakid.yml
  Resources/Prototypes/ADT/Novakid/Species/novakid.yml
Labels: No C#

#119 изменение размеров лазера капитана
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
Labels: No C#

#120 Мелкий фикс
  Content.Client/UserInterface/Systems/Chat/ChatUIController.cs
  Resources/Locale/ru-RU/ADT/Objects/Fan/plushie_aidan.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Crates/fun.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_ellis.png
Labels: Changes: Sprites, Changes: Localization

#122 добавлены спавнеры должностей
  Resources/Prototypes/ADT/Entities/Markers/Spawners/job.yml
  Resources/Textures/ADT/Markers/job.rsi/green.png
  Resources/Textures/ADT/Markers/job.rsi/iaa.png
  Resources/Textures/ADT/Markers/job.rsi/investigator.png
  Resources/Textures/ADT/Markers/job.rsi/magistrat.png
  Resources/Textures/ADT/Markers/job.rsi/meta.json
  Resources/Textures/ADT/Markers/job.rsi/urist.png
Labels: Changes: Sprites, No C#

#135 высыпание из сумок
  Resources/Prototypes/Entities/Objects/Specific/Chemistry/chem_bag.yml
  Resources/Prototypes/Entities/Objects/Specific/Hydroponics/tools.yml
Labels: No C#

#134 фикс вместительности смэса
  Resources/Prototypes/ADT/Entities/Structures/Power/industrial.yml
Labels: No C#

#124 Жилет шахида
  Resources/Locale/ru-RU/ADT/Clothing/OuterClothing/Armor/blueshield_armor.ftl
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/clothing_shahid.yml
  Resources/Textures/ADT/Clothing/OuterClothing/Fun/ShahidBelt.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Fun/ShahidBelt.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Fun/ShahidBelt.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Fun/ShahidBelt.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Fun/ShahidBelt.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#138 изменение яркости ламп
  Resources/Prototypes/ADT/Entities/Objects/Power/lights.yml
Labels: No C#

#139 фикс аномального голода у мышей
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Labels: No C#

#140 дионы больше не обр
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
Labels: No C#

#142 Печень Вульпканина
  Resources/Locale/ru-RU/ss14-ru/prototypes/body/organs/animal/animal.ftl
  Resources/Prototypes/ADT/Vulpkanin/Body/Organs/Vulpkanin.yml
  Resources/Prototypes/ADT/Vulpkanin/Body/Prototypes/Vulpkanin.yml
Labels: Changes: Localization, No C#

#143 Локализация requisition digi-board и clipboard
  Resources/Locale/ru-RU/ADT/Objects/Device/Circuitboard.ftl
Labels: Changes: Localization, No C#

#144 No fuel grief
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/Fan/plushie_aidan.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/posters.yml
  Resources/Prototypes/Entities/Structures/Storage/Tanks/tanks.yml
  Resources/Textures/ADT/Objects/Decoration/pizzatime.rsi/meta.json
  Resources/Textures/ADT/Objects/Decoration/pizzatime.rsi/pizzatime.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_azalia.png
Labels: Changes: Sprites, Changes: Localization, No C#

#137 Мелкие исправления новакидов
  Resources/Audio/ADT/ERT/ert_firesquad.ogg
  Resources/Audio/ADT/ERT/ert_heavy.ogg
  Resources/Audio/ADT/ERT/ert_no.ogg
  Resources/Audio/ADT/ERT/ert_send.ogg
  Resources/Audio/ADT/ERT/ert_yes.ogg
  Resources/Audio/ADT/ERT/protection_send.ogg
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/ADT/Novakid/Mobs/Species/novakid.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml
Labels: No C#, Status: Needs Review

#145 Фикс развала на множество органов у тараканов и молей.
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Labels: No C#

#146 FN-fal и фиксы
  Resources/Audio/ADT/Weapons/fnfal/FN-FAL_shoot1.ogg
  Resources/Audio/ADT/Weapons/fnfal/FN-FAL_shoot2.ogg
  Resources/Audio/ADT/Weapons/fnfal/FN-FAL_shoot3.ogg
  Resources/Audio/ADT/Weapons/fnfal/FN-FAL_shoot4.ogg
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/Guns.ftl
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Rifels/fmfal.yml
  Resources/Prototypes/tags.yml
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/fn_fal_mag.rsi/base.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/fn_fal_mag.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/fn_fal_mag.rsi/mag-1.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/Magazine/fn_fal_mag.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/fn_fal.rsi/base.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/fn_fal.rsi/bolt-open.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/fn_fal.rsi/equipped-BACKPACK.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/fn_fal.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/fn_fal.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/fn_fal.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/fn_fal.rsi/mag-0.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/fn_fal.rsi/meta.json
  Resources/Textures/Clothing/Back/Duffels/medical.rsi/equipped-BACKPACK.png
  Resources/Textures/Clothing/Back/Duffels/medical.rsi/icon.png
  Resources/Textures/Clothing/Back/Duffels/medical.rsi/inhand-left.png
  Resources/Textures/Clothing/Back/Duffels/medical.rsi/inhand-right.png
  Resources/Textures/Clothing/Back/Duffels/mime.rsi/equipped-BACKPACK.png
  Resources/Textures/Clothing/Back/Duffels/mime.rsi/icon.png
  Resources/Textures/Clothing/Back/Duffels/mime.rsi/inhand-left.png
  Resources/Textures/Clothing/Back/Duffels/mime.rsi/inhand-right.png
Labels: Changes: Sprites, Changes: Localization, No C#

#150 Обновка
  Resources/Locale/ru-RU/ADT/Objects/Fan/plushie_aidan.ftl
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/Guns.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Rifels/abakan.yml
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_sofy.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/aksy.rsi/base.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/aksy.rsi/bolt-open.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/aksy.rsi/equipped-BACKPACK.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/aksy.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/aksy.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/aksy.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/aksy.rsi/mag-0.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/aksy.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/aksy_iohana.rsi/base.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/aksy_iohana.rsi/bolt-open.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/aksy_iohana.rsi/equipped-BACKPACK.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/aksy_iohana.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/aksy_iohana.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/aksy_iohana.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/aksy_iohana.rsi/mag-0.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Rifels/aksy_iohana.rsi/meta.json
  Resources/Textures/Objects/Devices/pda.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#152 Драск
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Drask/species.ftl
  Resources/Prototypes/ADT/Drask/Body/Organs/Drask.yml
  Resources/Prototypes/ADT/Drask/Body/Parts/Drask.yml
  Resources/Prototypes/ADT/Drask/Body/Prototypes/Drask.yml
  Resources/Prototypes/ADT/Drask/Customization/Markings/Drask.yml
  Resources/Prototypes/ADT/Drask/Mobs/Player/Drask.yml
  Resources/Prototypes/ADT/Drask/Mobs/Species/Drask.yml
  Resources/Prototypes/ADT/Drask/Names/name_drask.yml
  Resources/Prototypes/ADT/Drask/Species/drask.yml
  Resources/Textures/ADT/Mobs/Drask/custom.rsi/l_arm.png
  Resources/Textures/ADT/Mobs/Drask/custom.rsi/meta.json
  Resources/Textures/ADT/Mobs/Drask/custom.rsi/r_arm.png
  Resources/Textures/ADT/Mobs/Drask/organs.rsi/eyes.png
  Resources/Textures/ADT/Mobs/Drask/organs.rsi/heart_on.png
  Resources/Textures/ADT/Mobs/Drask/organs.rsi/innards.png
  Resources/Textures/ADT/Mobs/Drask/organs.rsi/kidneys.png
  Resources/Textures/ADT/Mobs/Drask/organs.rsi/lungs.png
  Resources/Textures/ADT/Mobs/Drask/organs.rsi/meta.json
  Resources/Textures/ADT/Mobs/Drask/parts.rsi/eyes.png
  Resources/Textures/ADT/Mobs/Drask/parts.rsi/full.png
  Resources/Textures/ADT/Mobs/Drask/parts.rsi/head_f.png
  Resources/Textures/ADT/Mobs/Drask/parts.rsi/head_m.png
  Resources/Textures/ADT/Mobs/Drask/parts.rsi/l_arm.png
  Resources/Textures/ADT/Mobs/Drask/parts.rsi/l_foot.png
  Resources/Textures/ADT/Mobs/Drask/parts.rsi/l_hand.png
  Resources/Textures/ADT/Mobs/Drask/parts.rsi/l_leg.png
  Resources/Textures/ADT/Mobs/Drask/parts.rsi/meta.json
  Resources/Textures/ADT/Mobs/Drask/parts.rsi/r_arm.png
  Resources/Textures/ADT/Mobs/Drask/parts.rsi/r_foot.png
  Resources/Textures/ADT/Mobs/Drask/parts.rsi/r_hand.png
  Resources/Textures/ADT/Mobs/Drask/parts.rsi/r_leg.png
  Resources/Textures/ADT/Mobs/Drask/parts.rsi/torso_f.png
  Resources/Textures/ADT/Mobs/Drask/parts.rsi/torso_m.png
Labels: Changes: Sprites, Changes: Localization, No C#

#153 hotfix
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/ADT/Vulpkanin/Species/Vulpkanin.yml
  Resources/Prototypes/Entities/Objects/Vehicles/buckleable.yml
Labels: No C#

#155 drask audio update
  Resources/Audio/ADT/Drask/draskcough.ogg
  Resources/Audio/ADT/Drask/draskscream.ogg
  Resources/Audio/ADT/Drask/drasksneeze.ogg
  Resources/Audio/ADT/Drask/drasktalk.ogg
  Resources/Prototypes/ADT/Drask/Mobs/Species/Drask.yml
Labels: No C#

#157 NamingSystem update
  Content.Shared/Humanoid/NamingSystem.cs
  Content.Shared/Humanoid/Prototypes/SpeciesPrototype.cs
  Resources/Locale/en-US/species/namepreset.ftl
  Resources/Locale/ru-RU/species/namepreset.ftl
  Resources/Prototypes/ADT/Drask/Names/name_drask.yml
  Resources/Prototypes/ADT/Drask/Species/drask.yml
Labels: Changes: Localization

#159 Fix spam message
  Content.Client/UserInterface/Systems/Chat/Widgets/ChatBox.xaml.cs
Labels: Changes: UI

#160 Close Client
  Content.Client/UserInterface/Systems/Chat/Widgets/ChatBox.xaml.cs
Labels: Changes: UI

#158 Рандомизатор имён Вульпканов
  Resources/Prototypes/ADT/Entities/Objects/Misc/CratesCase.yml
  Resources/Prototypes/ADT/Vulpkanin/Names/first_female_vulp.yml
  Resources/Prototypes/ADT/Vulpkanin/Names/first_male_vulp.yml
  Resources/Prototypes/ADT/Vulpkanin/Names/last_vulp.yml
Labels: No C#

#165 Добавил новые доступы и шлюзы с ними
  Resources/Locale/ru-RU/ADT/access/access.ftl
  Resources/Prototypes/ADT/Access/BlueShield.yml
  Resources/Prototypes/ADT/Access/Investigator.yml
  Resources/Prototypes/ADT/Access/LawDepartament.yml
  Resources/Prototypes/ADT/Entities/Structures/Doors/access.yml
  Resources/Prototypes/ADT/Roles/Jobs/Magistrate/Magistrate.yml
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/OfficerBlueSheld.yml
  Resources/Prototypes/ADT/Roles/Jobs/SecInvestigator/investigator.yml
  Resources/Prototypes/Access/misc.yml
  Resources/Prototypes/Corvax/Roles/Jobs/Command/iaa.yml
Labels: Changes: Localization, No C#

#167 добавление штампа следователя
  Resources/Locale/ru-RU/ADT/paper/stamp-component.ftl
  Resources/Locale/ru-RU/ADT/paper/stamprubber.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Back/backpacks.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/paper.yml
  Resources/Textures/ADT/Objects/Misc/bureaucracy.rsi/meta.json
  Resources/Textures/ADT/Objects/Misc/bureaucracy.rsi/stamp-investigator.png
  Resources/Textures/Objects/Misc/bureaucracy.rsi/meta.json
  Resources/Textures/Objects/Misc/bureaucracy.rsi/paper_stamp-investigator.png
Labels: Changes: Sprites, Changes: Localization, No C#

#170 Апдейт правил
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Smokeables/Cigars/case.ftl
  Resources/Locale/ru-RU/ADT/Objects/Device/Circuitboard.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Smokeables/Cigars/case.yml
  Resources/Prototypes/ADT/Entities/Objects/Device/Circuitboards/pacman_hard.yml
  Resources/Prototypes/Catalog/Fills/Lockers/security.yml
  Resources/ServerInfo/Rules.txt
  Resources/Textures/ADT/Objects/Consumable/Smokeables/Cigars/case.rsi/cigar1.png
  Resources/Textures/ADT/Objects/Consumable/Smokeables/Cigars/case.rsi/cigar2.png
  Resources/Textures/ADT/Objects/Consumable/Smokeables/Cigars/case.rsi/cigar3.png
  Resources/Textures/ADT/Objects/Consumable/Smokeables/Cigars/case.rsi/cigar4.png
  Resources/Textures/ADT/Objects/Consumable/Smokeables/Cigars/case.rsi/cigar5.png
  Resources/Textures/ADT/Objects/Consumable/Smokeables/Cigars/case.rsi/cigar6.png
  Resources/Textures/ADT/Objects/Consumable/Smokeables/Cigars/case.rsi/cigar7.png
  Resources/Textures/ADT/Objects/Consumable/Smokeables/Cigars/case.rsi/cigar8.png
  Resources/Textures/ADT/Objects/Consumable/Smokeables/Cigars/case.rsi/closed.png
  Resources/Textures/ADT/Objects/Consumable/Smokeables/Cigars/case.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Consumable/Smokeables/Cigars/case.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Consumable/Smokeables/Cigars/case.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Smokeables/Cigars/case.rsi/open.png
  Resources/Textures/Corvax/Clothing/OuterClothing/Coats/warden_alt.rsi/broken.png
  Resources/Textures/Corvax/Clothing/OuterClothing/Coats/warden_alt.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#
