Repository xtray85/space_station, pull requests merged in 2024-05, with the labels that each got.

#650 сет Лапки
  Resources/Textures/ADT/Clothing/Shoes/Boots/lapkeeset_boots.rsi/equipped-FEET.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/lapkeeset_boots.rsi/icon.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/lapkeeset_boots.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/lapkeeset_boots.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/lapkeeset_boots.rsi/meta.json
Labels: Changes: Sprites, No C#

#659 Дополнение к SecretBook
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/prototypes/entities/secretbooks/secretbooks.ftl
  Resources/Prototypes/ADT/Entities/Objects/Misc/SrpOperatorCenCommBook.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/books.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/investigator_sjp.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/medical_books.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/new_recipes_book.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/secretbook.yml
  Resources/Prototypes/ADT/Recipes/Construction/Graph/secretbook.yml
  Resources/Prototypes/ADT/tags.yml
  Resources/Textures/ADT/Objects/Misc/books.rsi/chem-book.png
  Resources/Textures/ADT/Objects/Misc/books.rsi/meta.json
  Resources/Textures/ADT/Objects/Misc/books.rsi/new-cocktail-book.png
  Resources/Textures/ADT/Objects/Misc/books.rsi/new-recipe-book.png
  Resources/Textures/ADT/Objects/Misc/books.rsi/srp-operatorcentcomm-book.png
  Resources/Textures/ADT/Objects/Misc/chem_book.rsi/meta.json
  Resources/Textures/ADT/Objects/Misc/new_cocktail_book.rsi/meta.json
  Resources/Textures/ADT/Objects/Misc/new_recipe_book.rsi/meta.json
  Resources/Textures/ADT/Objects/Misc/srp_operatorcentcomm_book.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#661 Малые правки Harvester'а
  Resources/Locale/ru-RU/ADT/bluespace_harvester/bluespace_harvester.ftl
  Resources/Prototypes/Entities/Markers/Spawners/Random/bluespace_harvester.yml
Labels: Changes: Localization, No C#

#662 Moth speech
  Content.Server/Speech/EntitySystems/MothAccentSystem.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/traits/neutral.ftl
  Resources/Prototypes/ADT/Traits/neutral.yml
Labels: Changes: Localization

#665 mech tags + immortal headrev + shield nerf
  Content.Client/Revolutionary/UI/DeconvertedEui.cs
  Content.Client/Revolutionary/UI/DeconvertedMenu.xaml
  Content.Client/Revolutionary/UI/DeconvertedMenu.xaml.cs
  Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
  Resources/Prototypes/ADT/tags.yml
  Resources/Prototypes/Entities/Objects/Shields/shields.yml
  Resources/Prototypes/Entities/Objects/Specific/Mech/mecha_equipment.yml
  Resources/Prototypes/Entities/Objects/Specific/Mech/mechs.yml
Labels: Changes: UI

#663 Цель ЦК harvester
  Resources/Locale/ru-RU/corvax/station-goal/station-goal-component.ftl
  Resources/Prototypes/Corvax/Objectives/goals.yml
Labels: Changes: Localization, No C#

#595 (МЕРДЖИТЬ) Переводики и фиксы переводов
  Resources/Locale/ru-RU/ADT/borgs/borgs.ftl
  Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
  Resources/Locale/ru-RU/guidebook/guides.ftl
  Resources/Locale/ru-RU/prototypes/catalog/fills/crates/fun-crates.ftl
  Resources/Locale/ru-RU/reagents/meta/physical-desc.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/robotics/borg_modules.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/shuttles/thrusters.ftl
Labels: Changes: Localization, No C#

#668 ion rifle + head rev fix
  Content.IntegrationTests/Tests/Administration/Logs/AddTests.cs
  Content.IntegrationTests/Tests/Chemistry/TryAllReactionsTest.cs
  Content.Server/ADT/SecretTrans/SecretTransComponent.cs
  Content.Server/ADT/SecretTrans/SecretTransSystem.cs
  Content.Server/Emp/EmpOnCollideComponent.cs
  Content.Server/Emp/EmpSystem.cs
  Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
  Resources/Audio/Weapons/Guns/Gunshots/ionrifle.ogg
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/Guns.ftl
  Resources/Locale/ru-RU/research/technologies.ftl
  Resources/Locale/ru-RU/store/uplink-catalog.ftl
  Resources/Maps/Nonstations/nukieplanet.yml
  Resources/Prototypes/ADT/Entities/Mobs/nukiecarp.yml
  Resources/Prototypes/ADT/Entities/Structures/catwalks.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Effects/lightning.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Recipes/Lathes/security.yml
  Resources/Prototypes/Research/arsenal.yml
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/ion_rifle.rsi/base.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/ion_rifle.rsi/equipped-BACKPACK.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/ion_rifle.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/ion_rifle.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/ion_rifle.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/ion_rifle.rsi/mag-unshaded-0.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/ion_rifle.rsi/mag-unshaded-1.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/ion_rifle.rsi/mag-unshaded-2.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/ion_rifle.rsi/mag-unshaded-3.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/ion_rifle.rsi/mag-unshaded-4.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/ion_rifle.rsi/meta.json
  Resources/Textures/ADT/Structures/Windows/plastitanium_window.rsi/full.png
  Resources/Textures/ADT/Structures/Windows/plastitanium_window.rsi/meta.json
  Resources/Textures/ADT/Structures/Windows/plastitanium_window.rsi/ptwindow0.png
  Resources/Textures/ADT/Structures/Windows/plastitanium_window.rsi/ptwindow1.png
  Resources/Textures/ADT/Structures/Windows/plastitanium_window.rsi/ptwindow2.png
  Resources/Textures/ADT/Structures/Windows/plastitanium_window.rsi/ptwindow3.png
  Resources/Textures/ADT/Structures/Windows/plastitanium_window.rsi/ptwindow4.png
  Resources/Textures/ADT/Structures/Windows/plastitanium_window.rsi/ptwindow5.png
  Resources/Textures/ADT/Structures/Windows/plastitanium_window.rsi/ptwindow6.png
  Resources/Textures/ADT/Structures/Windows/plastitanium_window.rsi/ptwindow7.png
  Resources/Textures/ADT/Structures/catwalk.rsi/darkiron.png
  Resources/Textures/ADT/Structures/catwalk.rsi/iron.png
  Resources/Textures/ADT/Structures/catwalk.rsi/meta.json
  Resources/Textures/ADT/Structures/catwalk.rsi/platiumiron.png
  Resources/Textures/ADT/Structures/catwalk.rsi/smoothiron.png
  Resources/Textures/ADT/Structures/catwalk.rsi/titamiumiron.png
  Resources/Textures/ADT/Structures/catwalk.rsi/whiteiron.png
Labels: Changes: Sprites, Changes: Localization

#669 Space spider
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/Entities/Mobs/NPCs/space.yml
Labels: No C#

#670 Типо... Поменял что-то у боргов с RobotTalk на BorgTalk..
  Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
  Resources/Prototypes/Entities/Mobs/Cyborgs/borg_chassis.yml
  Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml
  Resources/Prototypes/Entities/Mobs/Player/silicon.yml
Labels: No C#

#671 Стандартизация Jobs
  Resources/Prototypes/ADT/Entities/Clothing/Back/backpacks.yml
  Resources/Prototypes/ADT/Entities/Clothing/Ears/headsets.yml
  Resources/Prototypes/ADT/Entities/Markers/Spawners/job.yml
  Resources/Prototypes/ADT/Entities/Mobs/player/humanoid.yml
  Resources/Prototypes/ADT/Entities/Objects/Device/pda.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/identification_cards.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/paper.yml
  Resources/Prototypes/ADT/Roboticist/pda.yml
  Resources/Prototypes/ADT/Roboticist/spawner.yml
  Resources/Prototypes/ADT/Roles/Jobs/Borgs/SecurityBorg.yml
  Resources/Prototypes/ADT/Roles/Jobs/Command/Magistrate.yml
  Resources/Prototypes/ADT/Roles/Jobs/Command/OfficerBlueSheld.yml
  Resources/Prototypes/ADT/Roles/Jobs/Magistrate/Headset_Magistrate.yml
  Resources/Prototypes/ADT/Roles/Jobs/Magistrate/RubberStampMagistrat.yml
  Resources/Prototypes/ADT/Roles/Jobs/Medical/pathologist.yml
  Resources/Prototypes/ADT/Roles/Jobs/Medical/pathologist/pathologist_pda.yml
  Resources/Prototypes/ADT/Roles/Jobs/Medical/virusolog.yml
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/backpack.yml
  Resources/Prototypes/ADT/Roles/Jobs/Science/Roboticist.yml
  Resources/Prototypes/ADT/Roles/Jobs/SecInvestigator/investigator_pda.yml
  Resources/Prototypes/ADT/Roles/Jobs/Security/investigator.yml
  Resources/Prototypes/ADT/Roles/Jobs/USSP/ArmyOfficer.yml
  Resources/Prototypes/ADT/Roles/Jobs/USSP/ArmyPrivate.yml
  Resources/Prototypes/ADT/Roles/Jobs/USSP/ussp_army.yml
  Resources/Prototypes/ADT/Roles/play_time_trackers.yml
  Resources/Prototypes/ADT/StartingGear/USSP/Medic.yml
  Resources/Prototypes/ADT/StartingGear/USSP/OBS5.yml
  Resources/Prototypes/ADT/StartingGear/USSP/OBS7.yml
  Resources/Prototypes/ADT/StartingGear/USSP/Pilot.yml
  Resources/Prototypes/ADT/StartingGear/USSP/Spetszan.yml
  Resources/Prototypes/ADT/StartingGear/USSP/SpetszanLMG.yml
  Resources/Prototypes/ADT/StatusEffects/job.yml
  Resources/Prototypes/Roles/play_time_trackers.yml
Labels: No C#

#672 моль может кушать виноград
  Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
Labels: No C#

#673 теперь в Парашкаф в вещмешке парамеда не будет 500 кредитов
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/ADT/Entities/Clothing/Back/duffels.yml
Labels: No C#

#675 статуя нюкера
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/structures/statues.ftl
  Resources/Prototypes/ADT/Entities/Structures/Decorations/statues.yml
  Resources/Textures/ADT/Structures/Decoration/statues.rsi/icon.png
  Resources/Textures/ADT/Structures/Decoration/statues.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#676 Исправлен баг с книжечками ОЦК и другими
  Resources/Prototypes/ADT/Entities/Objects/Misc/books.yml
Labels: No C#

#677 капюшон для куртки
  Resources/Prototypes/Entities/Clothing/OuterClothing/wintercoats.yml
Labels: No C#

#679 микро-макро добавка замены "??" на "вопросительно смотрит".
  Content.Server/Chat/Managers/ChatSanitizationManager.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/en-US/chat/sanitizer-replacements.ftl
  Resources/Locale/ru-RU/ADT/sanitizer-apathy-replacements.ftl
  Resources/Locale/ru-RU/chat/sanitizer-replacements.ftl
Labels: Changes: Localization

#682 гооол
  Resources/Prototypes/lobbyscreens.yml
  Resources/Textures/LobbyScreens/goal1.png
  Resources/Textures/LobbyScreens/goal1.png.yml
Labels: No C#

#642 vending machines requiring money
  Content.Client/VendingMachines/UI/VendingMachineMenu.xaml
  Content.Client/VendingMachines/UI/VendingMachineMenu.xaml.cs
  Content.Client/VendingMachines/VendingMachineBoundUserInterface.cs
  Content.IntegrationTests/Tests/CargoTest.cs
  Content.IntegrationTests/Tests/VendingMachineRestockTest.cs
  Content.Server/VendingMachines/VendingMachineSystem.cs
  Content.Shared/VendingMachines/SharedVendingMachineSystem.cs
  Content.Shared/VendingMachines/VendingMachineComponent.cs
  Content.Shared/VendingMachines/VendingMachineInterfaceState.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/en-US/vending-machines/vending-machine-component.ftl
  Resources/Locale/ru-RU/vending-machines/vending-machine-component.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
  Resources/Prototypes/ADT/Catalog/Fills/Backpacks/StarterGear/satchel.yml
  Resources/Prototypes/ADT/Catalog/Fills/Cargo/cargo_food.yml
  Resources/Prototypes/ADT/Catalog/Fills/Cargo/cargo_fun.yml
  Resources/Prototypes/ADT/Catalog/Fills/Cargo/cargo_service.yml
  Resources/Prototypes/Catalog/Cargo/cargo_emergency.yml
  Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/satchel.yml
  Resources/Prototypes/Entities/Clothing/Back/backpacks.yml
  Resources/Prototypes/Entities/Clothing/Eyes/base_clothingeyes.yml
  Resources/Prototypes/Entities/Clothing/Hands/base_clothinghands.yml
  Resources/Prototypes/Entities/Clothing/Head/base_clothinghead.yml
  Resources/Prototypes/Entities/Clothing/Neck/base_clothingneck.yml
  Resources/Prototypes/Entities/Clothing/Shoes/base_clothingshoes.yml
  Resources/Prototypes/Entities/Clothing/Uniforms/base_clothinguniforms.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_cans.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_cups.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
  Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/packs.yml
  Resources/Prototypes/Entities/Objects/Devices/radio.yml
  Resources/Prototypes/Entities/Objects/Fun/whistles.yml
  Resources/Prototypes/Entities/Objects/Misc/fluff_lights.yml
  Resources/Prototypes/Entities/Objects/Misc/handcuffs.yml
  Resources/Prototypes/Entities/Objects/Misc/space_cash.yml
  Resources/Prototypes/Entities/Objects/Specific/Medical/healing.yml
  Resources/Prototypes/Entities/Objects/Specific/Salvage/ore_bag.yml
  Resources/Prototypes/Entities/Objects/Tools/flare.yml
  Resources/Prototypes/Entities/Objects/Tools/gps.yml
  Resources/Prototypes/Entities/Objects/Tools/lighters.yml
  Resources/Prototypes/Entities/Objects/Weapons/Bombs/plastic.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/antimateriel.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/caseless_rifle.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/light_rifle.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/magnum.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/pistol.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/rifle.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/shotgun.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/pka.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/pickaxe.yml
  Resources/Prototypes/Entities/Objects/Weapons/Throwable/clusterbang.yml
  Resources/Prototypes/Entities/Objects/Weapons/Throwable/grenades.yml
  Resources/Prototypes/Entities/Objects/Weapons/security.yml
  Resources/Prototypes/Entities/Objects/base_item.yml
Labels: Changes: Localization, Changes: UI

#689 Revert "vending machines requiring money"
  Content.Client/VendingMachines/UI/VendingMachineMenu.xaml
  Content.Client/VendingMachines/UI/VendingMachineMenu.xaml.cs
  Content.Client/VendingMachines/VendingMachineBoundUserInterface.cs
  Content.IntegrationTests/Tests/CargoTest.cs
  Content.IntegrationTests/Tests/VendingMachineRestockTest.cs
  Content.Server/VendingMachines/VendingMachineSystem.cs
  Content.Shared/VendingMachines/SharedVendingMachineSystem.cs
  Content.Shared/VendingMachines/VendingMachineComponent.cs
  Content.Shared/VendingMachines/VendingMachineInterfaceState.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/en-US/vending-machines/vending-machine-component.ftl
  Resources/Locale/ru-RU/vending-machines/vending-machine-component.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
  Resources/Prototypes/ADT/Catalog/Fills/Backpacks/StarterGear/satchel.yml
  Resources/Prototypes/ADT/Catalog/Fills/Cargo/cargo_food.yml
  Resources/Prototypes/ADT/Catalog/Fills/Cargo/cargo_fun.yml
  Resources/Prototypes/ADT/Catalog/Fills/Cargo/cargo_service.yml
  Resources/Prototypes/Catalog/Cargo/cargo_emergency.yml
  Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/satchel.yml
  Resources/Prototypes/Entities/Clothing/Back/backpacks.yml
  Resources/Prototypes/Entities/Clothing/Eyes/base_clothingeyes.yml
  Resources/Prototypes/Entities/Clothing/Hands/base_clothinghands.yml
  Resources/Prototypes/Entities/Clothing/Head/base_clothinghead.yml
  Resources/Prototypes/Entities/Clothing/Neck/base_clothingneck.yml
  Resources/Prototypes/Entities/Clothing/Shoes/base_clothingshoes.yml
  Resources/Prototypes/Entities/Clothing/Uniforms/base_clothinguniforms.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_cans.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_cups.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
  Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/packs.yml
  Resources/Prototypes/Entities/Objects/Devices/radio.yml
  Resources/Prototypes/Entities/Objects/Fun/whistles.yml
  Resources/Prototypes/Entities/Objects/Misc/fluff_lights.yml
  Resources/Prototypes/Entities/Objects/Misc/handcuffs.yml
  Resources/Prototypes/Entities/Objects/Misc/space_cash.yml
  Resources/Prototypes/Entities/Objects/Specific/Medical/healing.yml
  Resources/Prototypes/Entities/Objects/Specific/Salvage/ore_bag.yml
  Resources/Prototypes/Entities/Objects/Tools/flare.yml
  Resources/Prototypes/Entities/Objects/Tools/gps.yml
  Resources/Prototypes/Entities/Objects/Tools/lighters.yml
  Resources/Prototypes/Entities/Objects/Weapons/Bombs/plastic.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/antimateriel.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/caseless_rifle.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/light_rifle.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/magnum.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/pistol.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/rifle.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Boxes/shotgun.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/pka.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/pickaxe.yml
  Resources/Prototypes/Entities/Objects/Weapons/Throwable/clusterbang.yml
  Resources/Prototypes/Entities/Objects/Weapons/Throwable/grenades.yml
  Resources/Prototypes/Entities/Objects/Weapons/security.yml
  Resources/Prototypes/Entities/Objects/base_item.yml
Labels: Changes: Localization, Changes: UI

#701 Create Directory.Build.props
  Directory.Build.props
Labels: No C#

#707 Временное решение проблем с github actions.
  .github/workflows/build-test-debug.yml
  .github/workflows/test-packaging.yml
  .github/workflows/yaml-linter.yml
  global.json
Labels: No C#, Status: Needs Review

#708 TryAllReactionsTest fix
  Resources/Prototypes/ADT/Recipes/Reactions/medicine.yml
Labels: No C#, Status: Needs Review

#688 Слизнекотики, трай 3 (УРААААААААААА)
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/ADT/Entities/Mobs/SlugCats/slugcat.yml
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/creek-rest.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/creek.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/dead-creek.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/dead-holy.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/dead-monk.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/dead-sonfariel.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/dead-spear-master.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/dead-technician.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/holy-rest.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/holy.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/icon-creek.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/icon-holy.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/icon-monk.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/icon-sonfariel.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/icon-spear-master.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/icon-technician.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/meta.json
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/monk-rest.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/monk.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/sonfariel-rest.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/sonfariel.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/spear-master-rest.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/spear-master.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/technician-rest.png
  Resources/Textures/ADT/Mobs/Animals/slug-cat.rsi/technician.png
Labels: Changes: Sprites, No C#

#522 Поправил баг с неусвоением пищи у пеплоходцев
  Resources/Prototypes/ADT/Lavaland/NPCs/AshWalker/AshWalker.yml
  Resources/Prototypes/ADT/Lavaland/NPCs/BaseHumLavalandMob.yml
Labels: No C#

#620 Bonespear resprite
  Resources/Changelog/ChangelogADT.yml
  Resources/Textures/Objects/Weapons/Melee/bone_spear.rsi/equipped-BACKPACK.png
  Resources/Textures/Objects/Weapons/Melee/bone_spear.rsi/inhand-left.png
  Resources/Textures/Objects/Weapons/Melee/bone_spear.rsi/inhand-right.png
  Resources/Textures/Objects/Weapons/Melee/bone_spear.rsi/meta.json
  Resources/Textures/Objects/Weapons/Melee/bone_spear.rsi/spear.png
  Resources/Textures/Objects/Weapons/Melee/bone_spear.rsi/spear1.png
  Resources/Textures/Objects/Weapons/Melee/bone_spear.rsi/wielded-inhand-left.png
  Resources/Textures/Objects/Weapons/Melee/bone_spear.rsi/wielded-inhand-right.png
Labels: Changes: Sprites, No C#, Status: Needs Review

#709 Кнопки радиального меню стали больше
  Content.Client/UserInterface/Systems/Radial/Controls/RadialContainer.xaml.cs
Labels: Changes: UI, Status: Needs Review

#717 remove_gamma_armory
  Resources/Maps/gammaarmory.yml
Labels: No C#, Changes: Map

#710 Удаление мобам "Мерзости" c экспедиции возможности сна
  Resources/Prototypes/ADT/Entities/Mobs/anomally_abomination.yml
Labels: No C#

#723 новый костюм горничной
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Clothing/Uniform/jumpsuits.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpskirt.yml
  Resources/Prototypes/Catalog/Fills/Crates/service.yml
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/janimaid.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/janimaid.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/janimaid.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/janimaid.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/janimaid.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/janimaid.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#727 Фикс красных кристаллов
  Resources/Prototypes/Entities/Markers/Spawners/Random/crystal.yml
Labels: No C#

#722 Fix build tests
  Resources/Prototypes/Entities/Clothing/OuterClothing/wintercoats.yml
  Resources/Prototypes/NES/Entities/Objects/Clotches/clotches.yml
  Resources/Prototypes/NES/Entities/Objects/Clotches/hardsuits.yml
  Resources/Prototypes/NES/Entities/Objects/Weapons/Pukalki/salvages.yml
  Resources/Prototypes/NES/Traits/disabilities.yml
Labels: No C#

#726 роль юриста на картах
  Resources/Prototypes/ADT/Maps/ADTMaps/atlas.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/avrite.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/box.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/cluster.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/delta.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/europa.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/fland.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/meta.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/origin.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/packed.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/saltern.yml
Labels: No C#

#728 ERT роль Майор РХБЗЗ
  Resources/Locale/ru-RU/ADT/ghost/roles/ghost-role.ftl
  Resources/Prototypes/ADT/Datasets/Names/cburn_names.yml
  Resources/Prototypes/ADT/Entities/Mobs/player/humanoid.yml
  Resources/Prototypes/ADT/StartingGear/ERT/ERT_leader.yml
Labels: Changes: Localization, No C#

#724 [ЗАКАЗ] Даем бензопиле новую жизнь
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/store/uplink-catalog.ftl
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/chainsaw.yml
Labels: Changes: Localization, No C#

#725 Новая антаг вещь
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Catalog/store/uplink.ftl
  Resources/Locale/ru-RU/ADT/Objects/Misc/consumable.ftl
  Resources/Prototypes/ADT/Catalog/uplink.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/knife.yml
Labels: Changes: Localization, No C#

#736 Изменения МЩ и Изменения глав
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/ADT/Catalog/Fills/Backpacks/StarterGear/duffelbag.yml
  Resources/Prototypes/ADT/Catalog/Fills/Backpacks/StarterGear/satchel.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
Labels: No C#
