Repository xtray85/space_station, pull requests merged in 2024-03, with the labels that each got.

#441 Canfix
  Resources/Textures/ADT/Objects/Consumable/Drinks/nostop.rsi/icon_open.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/nostop.rsi/meta.json
Labels: Changes: Sprites, No C#

#442 Юпитер-6
  Content.Server/ADT/StationEvents/Components/TraderSpawnRuleComponent.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Trader/trader.ftl
  Resources/Maps/Shuttles/trader.yml
  Resources/Maps/traderpost.yml
  Resources/Prototypes/ADT/Entities/Mobs/player/trader.yml
  Resources/Prototypes/ADT/StartingGear/trader.yml
  Resources/Prototypes/ADT/Tallrobot/base.yml
  Resources/Prototypes/ADT/tags.yml
  Resources/Prototypes/GameRules/events.yml
Labels: Changes: Localization, Changes: Map

#446 Убираю киборгу Сб спешилл
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/base.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/sec_cyborg.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/species.yml
  Resources/Textures/ADT/Mobs/Silicon/Cyborg/parts.rsi/meta.json
Labels: No C#

#448 Перевод-морти
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/animals.ftl
Labels: Changes: Localization, No C#

#450 Перевод промышленного переработчика руды с его платой машинной
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/machine/production.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/IndustrialOreProcessor_machine.ftl
Labels: Changes: Localization, No C#

#449 недостающая канистра виски
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/specific/jugs.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Drinks/DrinkJugs.yml
  Resources/Prototypes/Catalog/ReagentDispensers/beverage.yml
Labels: Changes: Localization, No C#

#451 Вульпикс
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Food/vulpix.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/vulpix.yml
  Resources/Prototypes/ADT/Recipes/Cooking/vulpix_recipe.yml
  Resources/ServerInfo/ADT/NewRecipes.xml
  Resources/Textures/ADT/Objects/Consumable/Food/vulpix.rsi/icon.png
  Resources/Textures/ADT/Objects/Consumable/Food/vulpix.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#452 Перевод Супер тех диска. Перевод магнетической реакции артефакта
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/research/disk.ftl
  Resources/Locale/ru-RU/xenoarchaeology/artifact-hints.ftl
Labels: Changes: Localization, No C#

#453 Добавил антагониста (генокрада) в Guidebook - Antagonist
  Resources/ServerInfo/Guidebook/Antagonist/Antagonists.xml
Labels: No C#

#454 Плащ Аарона(именная вещь Пангари)
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/coats.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/tools/lighters.ftl
  Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml
  Resources/Textures/Clothing/OuterClothing/Coats/coat_aaron.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Clothing/OuterClothing/Coats/coat_aaron.rsi/icon.png
  Resources/Textures/Clothing/OuterClothing/Coats/coat_aaron.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#459 Мелкие фиксы (добавил приписку ADT и исправил опечатку)
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/coats.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/tools/lighters.ftl
  Resources/Prototypes/Entities/Clothing/OuterClothing/coats.yml
Labels: Changes: Localization, No C#

#461 Перевод технологий РНД
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/shoes/magboots.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/swapper.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/tiles.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/power/powercells.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/chemistry/cryosyringe.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/salvage/ore_bag.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/battery/battery_guns.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/power/generation/tesla.ftl
Labels: Changes: Localization, No C#

#456 Фикс курицы и переводов кувшинов
  Resources/Locale/ru-RU/ADT/Clothing/Uniform/jumpsuits.ftl
  Resources/Locale/ru-RU/ADT/Clothing/boots.ftl
  Resources/Locale/ru-RU/ADT/Clothing/outerclothing.ftl
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/Guns.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/coats.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/chemical-containers.ftl
  Resources/Prototypes/ADT/Body/Parts/chicken.yml
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Labels: Changes: Localization, No C#

#457 одежда торговцев
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Trader/trader.ftl
  Resources/Maps/traderpost.yml
  Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/hats.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/coats.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpsuit.yml
  Resources/Prototypes/ADT/Entities/Mobs/player/trader.yml
  Resources/Prototypes/ADT/Entities/Structures/Decorations/banners.yml
  Resources/Prototypes/ADT/StartingGear/trader.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Textures/ADT/Clothing/Ears/Headsets/trader.rsi/equipped-EARS.png
  Resources/Textures/ADT/Clothing/Ears/Headsets/trader.rsi/icon.png
  Resources/Textures/ADT/Clothing/Ears/Headsets/trader.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hats/trader.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/trader.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/trader.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/bomber_tsf.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/bomber_tsf.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/bomber_tsf.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/bomber_tsf.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/bomber_tsf.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/trader.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/trader.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/trader.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/trader.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/trader.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpsuit/trader.rsi/meta.json
  Resources/Textures/ADT/Objects/Misc/trader_id.rsi/idtrader_tsf.png
  Resources/Textures/ADT/Objects/Misc/trader_id.rsi/meta.json
  Resources/Textures/ADT/Objects/Misc/trader_id.rsi/tsf.png
  Resources/Textures/ADT/Objects/Misc/trader_pda.rsi/id_overlay.png
  Resources/Textures/ADT/Objects/Misc/trader_pda.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Misc/trader_pda.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Misc/trader_pda.rsi/light_overlay.png
  Resources/Textures/ADT/Objects/Misc/trader_pda.rsi/meta.json
  Resources/Textures/ADT/Objects/Misc/trader_pda.rsi/pda-tradertsf.png
  Resources/Textures/ADT/Structures/Decoration/tsf_banner.rsi/humanflag.png
  Resources/Textures/ADT/Structures/Decoration/tsf_banner.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#, Changes: Map

#460 Ещё переводы
  Resources/Locale/ru-RU/ADT/Objects/specific/anomaly.ftl
  Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/objects/fun/toys.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/hands/gloves.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/misc.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/hardsuits.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/misc.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/shoes/boots.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/shoes/misc.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/cartridges.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/holoprojectors.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/whistle.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/PotatoAIChip.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/kudzu.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/tiles.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/bombs/ied.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/battery/battery_guns.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/furniture/beds.ftl
  Resources/Locale/ru-RU/station-events/events/bureaucratic-error.ftl
  Resources/Locale/ru-RU/voting/managers/vote-manager.ftl
Labels: Changes: Localization, No C#

#458 Апдейт от нечего делать
  Resources/Changelog/ChangelogADT.yml
  Resources/Maps/Dungeon/bunker.yml
  Resources/Maps/Dungeon/medicine.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/suits.yml
  Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Prototypes/Procedural/Themes/medicine.yml
  Resources/Prototypes/Procedural/biome_templates.yml
  Resources/Prototypes/Procedural/dungeon_configs.yml
  Resources/Prototypes/Procedural/salvage_factions.yml
  Resources/Prototypes/Procedural/salvage_mods.yml
Labels: No C#

#466 Переводы, переводы, и ещё раз переводы
  Resources/Locale/en-US/ss14-ru/prototypes/adt/vulpkanin/entities/mobs/player/Vulpkanin.ftl
  Resources/Locale/ru-RU/ADT/Objects/Device/Circuitboard.ftl
  Resources/Locale/ru-RU/ADT/Projectilles/magnum.ftl
  Resources/Locale/ru-RU/ADT/borgs/borgs.ftl
  Resources/Locale/ru-RU/SimpleStation14/body/ipc-organs.ftl
  Resources/Locale/ru-RU/SimpleStation14/body/ipc-parts.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/vulpkanin/entities/mobs/player/Vulpkanin.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/hands/gloves.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/pets.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/player/reptilian.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/dwarf.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/machine/production.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/ammunition/magazines/magnum.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/ammunition/magazines/pistol.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/ammunition/magazines/rifle.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/ammunition/speedloaders/magnum.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/power/chargers.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/storage/closets/closets.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/signs.ftl
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/OfficerBlueSheld.yml
Labels: Changes: Localization, No C#

#462 Починка рыбы
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Food/fish.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/meat.yml
Labels: Changes: Localization, No C#

#464 Уристыы
  .vscode/settings.json
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/moth/entities/mobs/player/moth.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/moth/entities/mobs/species/moth.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/player/demon.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/player/diona.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/player/drask.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/player/gingerbread.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/player/kobalt.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/player/moth.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/player/novakid.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/player/ursus.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/demon.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/diona.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/drask.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/gingerbread.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/human.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/kobalt.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/moth.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/novakid.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/reptilian.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/ursus.ftl
  Resources/Locale/ru-RU/station-events/events/vent-critters.ftl
Labels: Changes: Localization, No C#

#467 Персонализейшен оружия
  Content.Shared/Weapons/Ranged/Components/GunComponent.cs
  Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.Interactions.cs
  Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/other.ftl
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/equipment.yml
Labels: Changes: Localization

#469 не то чтобы smol ГЕНОКРАД АПДЕЙТ™
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSystem.Abilities.cs
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSystem.cs
  Content.Server/Store/Systems/StoreSystem.cs
  Content.Server/Traitor/Uplink/UplinkSystem.cs
  Content.Shared/ADT/Changeling/Components/ChangelingComponent.cs
  Content.Shared/ADT/Changeling/SharedChangeling.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Actions/action_changeling.ftl
  Resources/Locale/ru-RU/game-ticking/preset-changeling.ftl
  Resources/Prototypes/ADT/changeling/changeling.yml
  Resources/Prototypes/ADT/changeling/ling_catalog.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/armblade.yml
  Resources/Textures/Interface/Actions/actions_ling.rsi/epinephrine_overdose.png
  Resources/Textures/Interface/Actions/actions_ling.rsi/fleshmend.png
  Resources/Textures/Interface/Actions/actions_ling.rsi/meta.json
  Resources/Textures/Interface/Actions/actions_ling.rsi/refresh_dna.png
Labels: Changes: Sprites, Changes: Localization

#465 чаёчек
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Drinks/cup_tea.ftl
  Resources/Locale/ru-RU/ADT/Reagents/meta/drinks/cup_tea.ftl
  Resources/Locale/ru-RU/reagents/meta/consumable/drink/drinks.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Drinks/cup_tea.yml
  Resources/Prototypes/ADT/Reagents/Consumable/Drink/cup_tea.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/coffee.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_cups.yml
  Resources/Prototypes/Reagents/Consumable/Drink/drinks.yml
  Resources/Textures/ADT/Objects/Consumable/Drinks/chamomile-tea.rsi/icon-0.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/chamomile-tea.rsi/icon-1.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/chamomile-tea.rsi/icon-2.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/chamomile-tea.rsi/icon-3.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/chamomile-tea.rsi/icon-4.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/chamomile-tea.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Drinks/glass_chamomile.rsi/icon.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/glass_chamomile.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Drinks/glass_karkade.rsi/icon.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/glass_karkade.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Drinks/glass_lemon.rsi/icon.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/glass_lemon.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Drinks/karkade-tea.rsi/icon-0.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/karkade-tea.rsi/icon-1.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/karkade-tea.rsi/icon-2.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/karkade-tea.rsi/icon-3.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/karkade-tea.rsi/icon-4.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/karkade-tea.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Drinks/lemon-tea.rsi/icon-0.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/lemon-tea.rsi/icon-1.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/lemon-tea.rsi/icon-2.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/lemon-tea.rsi/icon-3.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/lemon-tea.rsi/icon-4.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/lemon-tea.rsi/meta.json
  Resources/Textures/Objects/Consumable/Drinks/ice_tea_can.rsi/icon.png
Labels: Changes: Sprites, Changes: Localization, No C#

#470 фикс диенты унатхов, фелинидов и ниан
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/croissant.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/fried_egg.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/hypoallergen_chocolate.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/khachapuri.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/meat.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/oktoberfest.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/sashimisafe.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/sausage.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/shawerma.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/snacks.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/vulpix.yml
  Resources/Prototypes/Body/Organs/moth.yml
  Resources/Prototypes/Body/Organs/reptilian.yml
  Resources/Prototypes/Corvax/Entities/Objects/Consumable/Food/soup.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/bread.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/Baked/misc.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/burger.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/ingredients.yml
  Resources/Prototypes/tags.yml
Labels: No C#

#473 перевод вещей аплинка
  Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/boxes/syndicate.ftl
  Resources/Locale/ru-RU/store/uplink-catalog.ftl
Labels: Changes: Localization, No C#

#475 страйкбольные пульки и привод
  Resources/Audio/Weapons/Guns/Gunshots/airsoft.ogg
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/Guns.ftl
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/bibis.yml
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/airsoft_bibis.rsi/base-spent.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/airsoft_bibis.rsi/base.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Ammunition/airsoft_bibis.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#472 локализация кассет и деинструкторизация
  Resources/Audio/BoomBox/HotlineMoges/hotline_crystals.ogg
  Resources/Audio/BoomBox/HotlineMoges/hotline_daisuke.ogg
  Resources/Audio/BoomBox/HotlineMoges/hotline_hydrogen.ogg
  Resources/Audio/BoomBox/HotlineMoges/hotline_itssafe.ogg
  Resources/Audio/BoomBox/HotlineMoges/hotline_moges.ogg
  Resources/Audio/BoomBox/HotlineMoges/hotline_mogesdisco.ogg
  Resources/Audio/BoomBox/HotlineMoges/hotline_musik.ogg
  Resources/Audio/BoomBox/HotlineMoges/hotline_paris.ogg
  Resources/Audio/BoomBox/USSP/14minute.ogg
  Resources/Audio/BoomBox/USSP/alliancearmy.ogg
  Resources/Audio/BoomBox/USSP/iftomorrow.ogg
  Resources/Audio/BoomBox/USSP/ourlocomotive.ogg
  Resources/Audio/BoomBox/USSP/sacredwar.ogg
  Resources/Audio/BoomBox/USSP/tapokalert3.ogg
  Resources/Audio/BoomBox/USSP/usspanthem.ogg
  Resources/Audio/BoomBox/USSP/wearmyofthepeople.ogg
  Resources/Audio/BoomBox/barotrauma_aliensyndicate.ogg
  Resources/Audio/BoomBox/barotrauma_embrasetheabyss.ogg
  Resources/Audio/BoomBox/highfleettancalelek.ogg
  Resources/Locale/ru-RU/ADT/Fills/cargo.ftl
  Resources/Locale/ru-RU/ADT/boombox/boombox.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Cargo/cargo_fun.yml
  Resources/Prototypes/ADT/Catalog/Fills/Crates/fun.yml
  Resources/Prototypes/ADT/Entities/Objects/Device/boombox.yml
  Resources/Prototypes/Catalog/Fills/Crates/cargo.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/maintenance.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/salvage.yml
Labels: Changes: Localization, No C#

#478 Убрал файлы-дублёры уристов арканы и ниана
  Resources/Locale/en-US/ss14-ru/prototypes/entities/mobs/player/demon.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/entities/mobs/species/demon.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/demon/mobs/player/demon.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/demon/mobs/species/demon.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/moth/entities/mobs/player/moth.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/moth/entities/mobs/species/moth.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/demon.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/drask.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/gingerbread.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/kobalt.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/ursus.ftl
Labels: Changes: Localization, No C#

#477 переводы,увеличил кол-во предметов в гидророб на +1
  Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/boxes/general.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/eyes/glasses.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/hats.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/neck/stoles.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpskirts.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpsuits.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/decoration/urna.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/hydroponics/seeds.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/medical/healing.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/tools/lighters.ftl
  Resources/Prototypes/Catalog/VendingMachines/Inventories/hydrobe.yml
Labels: Changes: Localization, No C#

#481 перевод заказов в форум-транслетер
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/clothing/uniforms/Jumpsuit.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/masks/masks.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/shoes/specific.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpsuits.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/machine/production.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/battery/battery_guns.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/furniture/chairs.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/shuttles/thrusters.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/shotgun_cabinet.ftl
Labels: Changes: Localization, No C#

#483 добавил к айди пепла ADT
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/objects/misc/radioash.ftl
  Resources/Prototypes/Entities/Objects/Misc/radioash.yml
Labels: Changes: Localization, No C#

#480 A small correction, resprite ID card Detective`s.
  Resources/Textures/Objects/Misc/id_cards.rsi/iddetective.png
Labels: Changes: Sprites, No C#

#485 Перевод категорий товаров в консоли заказов карго [Перевод]
  Resources/Locale/en-US/ss14-ru/prototypes/adt/entities/clothing/uniforms/Jumpsuit.ftl
  Resources/Locale/ru-RU/ADT/Clothing/OuterClothing/Underwear/underwear.ftl
  Resources/Locale/ru-RU/ADT/Objects/Power/light.ftl
  Resources/Locale/ru-RU/administration/smites.ftl
  Resources/Locale/ru-RU/prototypes/catalog/cargo/cargoproduct-categories.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/clothing/neck/NecklaceWith.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/clothing/shoes/Boots.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/clothing/uniforms/Jumpskirt.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/clothing/uniforms/Jumpsuit.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/objects/specific/ADTchemistrybottles.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/objects/weapons/melee/bouquets.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/backpacks/duffelbag.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/animals.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/machine/production.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/syndicate_gadgets/reinforcement_teleporter.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/koboldcube.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/rehydrateable.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/robotics/borg_modules.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/ammunition/explosives.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/lathe.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/bar_sign.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
  Resources/Locale/ru-RU/tesla/tesla.ftl
  Resources/Locale/ru-RU/vending-machines/vending-machine.ftl
Labels: Changes: Localization, No C#

#484 перевод спавнеров и других многих вещей
  Resources/Audio/BoomBox/TenebreRossoSangue-mono.ogg
  Resources/Locale/ru-RU/ADT/boombox/boombox.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/clothing/head/hats/hats.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/roles/jobs/magistrate/Magistrate.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/roles/jobs/magistrate/RubberStampMagistrat.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/roles/jobs/officerblueshield/OfficerBlueSheld.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/hats.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/markers/spawners/mobs.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Crates/fun.yml
  Resources/Prototypes/ADT/Entities/Objects/Device/boombox.yml
Labels: Changes: Localization, No C#

#486 Добавили со Шрёдькой кружку СССП
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Drinks/ussp_mup.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Drinks/ussp_mug.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/dinnerware.yml
  Resources/Textures/ADT/Objects/Consumable/Drinks/ussp_cup.rsi/icon-0.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/ussp_cup.rsi/icon-1.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/ussp_cup.rsi/icon-2.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/ussp_cup.rsi/icon-3.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/ussp_cup.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#489 qol прыжковых ботинок.
  Content.Server/ADT/Jumpboots/JumpbootsSystem.cs
  Content.Shared/ADT/Jumpboots/JumpbootsComponent.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Catalog/store/uplink.ftl
  Resources/Prototypes/ADT/Actions/jumpboots.yml
  Resources/Prototypes/ADT/Catalog/uplink.yml
  Resources/Prototypes/ADT/Entities/Clothing/Shoes/Boots.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/salvage.yml
  Resources/Textures/ADT/Clothing/Shoes/Boots/jumpboots.rsi/equipped-FEET.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/jumpboots.rsi/icon.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/jumpboots.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/jumpboots.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/jumpboots.rsi/meta.json
  Resources/Textures/ADT/Clothing/Shoes/Boots/jumpboots_syndie.rsi/equipped-FEET.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/jumpboots_syndie.rsi/icon-on.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/jumpboots_syndie.rsi/icon.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/jumpboots_syndie.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/jumpboots_syndie.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/jumpboots_syndie.rsi/meta.json
  Resources/Textures/ADT/Clothing/Shoes/Boots/jumpboots_syndie.rsi/on-equipped-FEET.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/jumpboots_syndie.rsi/on-inhand-left.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/jumpboots_syndie.rsi/on-inhand-right.png
Labels: Changes: Sprites, Changes: Localization

#490 [Перевод] Реплики торговых автоматов
  Resources/Locale/ru-RU/advertisements/vending/ammo.ftl
  Resources/Locale/ru-RU/advertisements/vending/atmosdrobe.ftl
  Resources/Locale/ru-RU/advertisements/vending/bardrobe.ftl
  Resources/Locale/ru-RU/advertisements/vending/boozeomat.ftl
  Resources/Locale/ru-RU/advertisements/vending/cargodrobe.ftl
  Resources/Locale/ru-RU/advertisements/vending/chang.ftl
  Resources/Locale/ru-RU/advertisements/vending/chefdrobe.ftl
  Resources/Locale/ru-RU/advertisements/vending/chefvend.ftl
  Resources/Locale/ru-RU/advertisements/vending/chemdrobe.ftl
  Resources/Locale/ru-RU/advertisements/vending/cigs.ftl
  Resources/Locale/ru-RU/advertisements/vending/clothesmate.ftl
  Resources/Locale/ru-RU/advertisements/vending/coffee.ftl
  Resources/Locale/ru-RU/advertisements/vending/cola.ftl
  Resources/Locale/ru-RU/advertisements/vending/condiments.ftl
  Resources/Locale/ru-RU/advertisements/vending/curadrobe.ftl
  Resources/Locale/ru-RU/advertisements/vending/detdrobe.ftl
  Resources/Locale/ru-RU/advertisements/vending/dinnerware.ftl
  Resources/Locale/ru-RU/advertisements/vending/discount.ftl
  Resources/Locale/ru-RU/advertisements/vending/donut.ftl
  Resources/Locale/ru-RU/advertisements/vending/engidrobe.ftl
  Resources/Locale/ru-RU/advertisements/vending/games.ftl
  Resources/Locale/ru-RU/advertisements/vending/genedrobe.ftl
  Resources/Locale/ru-RU/advertisements/vending/happyhonk.ftl
  Resources/Locale/ru-RU/advertisements/vending/hydrobe.ftl
  Resources/Locale/ru-RU/advertisements/vending/janidrobe.ftl
  Resources/Locale/ru-RU/advertisements/vending/lawdrobe.ftl
  Resources/Locale/ru-RU/advertisements/vending/magivend.ftl
  Resources/Locale/ru-RU/advertisements/vending/medidrobe.ftl
  Resources/Locale/ru-RU/advertisements/vending/megaseed.ftl
  Resources/Locale/ru-RU/advertisements/vending/nanomed.ftl
  Resources/Locale/ru-RU/advertisements/vending/nutrimax.ftl
  Resources/Locale/ru-RU/advertisements/vending/robodrobe.ftl
  Resources/Locale/ru-RU/advertisements/vending/scidrobe.ftl
  Resources/Locale/ru-RU/advertisements/vending/secdrobe.ftl
  Resources/Locale/ru-RU/advertisements/vending/sectech.ftl
  Resources/Locale/ru-RU/advertisements/vending/smartfridge.ftl
  Resources/Locale/ru-RU/advertisements/vending/snack.ftl
  Resources/Locale/ru-RU/advertisements/vending/sovietsoda.ftl
  Resources/Locale/ru-RU/advertisements/vending/syndiedrobe.ftl
  Resources/Locale/ru-RU/advertisements/vending/theater.ftl
  Resources/Locale/ru-RU/advertisements/vending/vendomat.ftl
  Resources/Locale/ru-RU/advertisements/vending/virodrobe.ftl
Labels: Changes: Localization, No C#

#492 перевод GuideBook
  Resources/ServerInfo/Guidebook/Cargo/Cargo.xml
  Resources/ServerInfo/Guidebook/Cargo/CargoBounties.xml
  Resources/ServerInfo/Guidebook/Engineering/AccessConfigurator.xml
  Resources/ServerInfo/Guidebook/Engineering/AirlockSecurity.xml
  Resources/ServerInfo/Guidebook/Engineering/NetworkConfigurator.xml
  Resources/ServerInfo/Guidebook/Engineering/Networking.xml
  Resources/ServerInfo/Guidebook/Engineering/PortableGenerator.xml
  Resources/ServerInfo/Guidebook/Engineering/TEG.xml
  Resources/ServerInfo/Guidebook/Science/Technologies.xml
  Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
Labels: No C#

#493 Мини-апдейт
  Content.Client/ADT/SlimeHair/SlimeHairBoundUserInterface.cs
  Content.Client/ADT/SlimeHair/SlimeHairWindow.xaml
  Content.Client/ADT/SlimeHair/SlimeHairWindow.xaml.cs
  Content.Server/ADT/Changeling/EntitySystems/ChangelingEggSystem.cs
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSlugSystem.Abilities.cs
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSlugSystem.cs
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSystem.Abilities.cs
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSystem.cs
  Content.Server/ADT/ComponentalActions/EntitySystems/ComponentalActions.Abilities.cs
  Content.Server/ADT/ComponentalActions/EntitySystems/ComponentalActions.cs
  Content.Server/ADT/Language/LanguageSystem.cs
  Content.Server/ADT/SlimeHair/SlimeHairComponent.cs
  Content.Server/ADT/SlimeHair/SlimeHairSystem.Abilities.cs
  Content.Server/ADT/SlimeHair/SlimeHairSystem.cs
  Content.Server/Chemistry/ReagentEffects/LingEggs.cs
  Content.Server/Medical/DefibrillatorSystem.cs
  Content.Shared/ADT/Changeling/Components/ChangelingComponent.cs
  Content.Shared/ADT/Changeling/Components/LingEggsHolder.cs
  Content.Shared/ADT/Changeling/Components/LingSlugComponent.cs
  Content.Shared/ADT/ComponentalActions/Components/InvisibilityActComponent.cs
  Content.Shared/ADT/ComponentalActions/Components/StasisHealActComponent.cs
  Content.Shared/ADT/ComponentalActions/SharedComponentalActions.cs
  Content.Shared/ADT/Language/Components/CommonLangUnknown.cs
  Content.Shared/ADT/SlimeHair/SharedSlimeHairSystem.cs
  Content.Shared/Stealth/Components/StealthComponent.cs
  Resources/Audio/ADT/slime-hair.ogg
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/componental-actions.ftl
  Resources/Locale/ru-RU/ADT/slime-hair.ftl
  Resources/Locale/ru-RU/game-ticking/preset-changeling.ftl
  Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
  Resources/Locale/ru-RU/medical/components/defibrillator.ftl
  Resources/Locale/ru-RU/reagents/meta/toxins.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/animals.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/meals.ftl
  Resources/Locale/ru-RU/traits/traits.ftl
  Resources/Prototypes/ADT/Actions/componental_actions.yml
  Resources/Prototypes/ADT/Actions/language.yml
  Resources/Prototypes/ADT/Actions/slime.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Prototypes/ADT/changeling/changeling.yml
  Resources/Prototypes/ADT/changeling/mobs.yml
  Resources/Prototypes/ADT/ling_unturnable.yml
  Resources/Prototypes/Actions/types.yml
  Resources/Prototypes/Catalog/Fills/Crates/salvage.yml
  Resources/Prototypes/Entities/Mobs/Species/slime.yml
  Resources/Prototypes/Traits/disabilities.yml
  Resources/Textures/ADT/Actions/slime-hair.rsi/hair.png
  Resources/Textures/ADT/Actions/slime-hair.rsi/meta.json
  Resources/Textures/ADT/Objects/Specific/genо_larva_white.rsi/icon.png
  Resources/Textures/ADT/Objects/Specific/genо_larva_white.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Specific/genо_larva_white.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Specific/genо_larva_white.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, Changes: UI

#497 выполнил небольшие просьбы в баг-репорт
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Drinks/cup_and_teapot.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/BoneKnife.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/Swords.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_flasks.yml
Labels: No C#

#498 Галлюцинации
  Content.Client/ADT/ChangelingEggsSystem.cs
  Content.Server/ADT/Changeling/EntitySystems/ChangelingEggSystem.cs
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSlugSystem.Abilities.cs
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSlugSystem.cs
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSystem.Abilities.cs
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSystem.cs
  Content.Server/ADT/Changeling/EntitySystems/LingHallucinationSystem.cs
  Content.Server/ADT/Changeling/EntitySystems/LingHallucinationsSystem.cs
  Content.Server/ADT/NarcoticEffects/HallucinationSystem.cs
  Content.Server/ADT/NarcoticEffects/NarcoHallucinationsSystem.cs
  Content.Server/Chemistry/ReagentEffects/StatusEffects/GenericStatusEffect.cs
  Content.Server/Objectives/Components/AbsorbDnaConditionComponent.cs
  Content.Server/Objectives/Components/PickRandomDnaComponent.cs
  Content.Server/Objectives/Components/PickRandomHeadDnaComponent.cs
  Content.Server/Objectives/Components/StealPersonalityConditionComponent.cs
  Content.Server/Objectives/Components/TargetObjectiveComponent.cs
  Content.Server/Objectives/Systems/AbsorbDnaConditionSystem.cs
  Content.Server/Objectives/Systems/StealPersonalityConditionSystem.cs
  Content.Server/Objectives/Systems/TargetObjectiveSystem.cs
  Content.Shared/ADT/Changeling/Components/ChangelingComponent.cs
  Content.Shared/ADT/Changeling/Components/LingEggsHolder.cs
  Content.Shared/ADT/Changeling/Components/LingHallucinationComponent.cs
  Content.Shared/ADT/Changeling/Components/LingHallucinationsComponent.cs
  Content.Shared/ADT/Changeling/Components/LingSlugComponent.cs
  Content.Shared/ADT/NarcoticEffect/Components/HallucinationComponent.cs
  Content.Shared/ADT/NarcoticEffect/Components/NarcoHallucinationsComponent.cs
  Content.Shared/Eye/VisibilityFlags.cs
  Resources/Audio/ADT/ling-drug-mob.ogg
  Resources/Audio/ADT/ling-drugs.ogg
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/hallucinations.ftl
  Resources/Locale/ru-RU/ADT/ling-objectives.ftl
  Resources/Locale/ru-RU/game-ticking/preset-changeling.ftl
  Resources/Prototypes/ADT/Alerts/alerts.yml
  Resources/Prototypes/ADT/Narcotic.yml
  Resources/Prototypes/ADT/Reagents/medicine.yml
  Resources/Prototypes/ADT/changeling/mobs.yml
  Resources/Prototypes/ADT/changeling/objectives_changeling.yml
  Resources/Prototypes/ADT/status_effects.yml
  Resources/Prototypes/Entities/Mobs/Species/base.yml
  Resources/Prototypes/Entities/Mobs/Species/slime.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/armblade.yml
  Resources/Prototypes/Objectives/objectiveGroups.yml
  Resources/Prototypes/Reagents/medicine.yml
  Resources/Prototypes/Reagents/narcotics.yml
  Resources/Prototypes/Reagents/toxins.yml
  Resources/Textures/Interface/Alerts/ling/egg.png
Labels: Changes: Localization

#503 [Перевод] перевод интерфейса консоли криминальных записей отдела СБ
  Resources/Locale/ru-RU/criminal records/criminal-records.ftl
Labels: Changes: Localization, No C#

#507 Очистка ДНК генокрада
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSlugSystem.Abilities.cs
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSyntEggSystem.cs
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSystem.Abilities.cs
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSystem.cs
  Content.Server/ADT/Changeling/EntitySystems/DNARefresh.cs
  Content.Server/Chemistry/ReagentEffects/LingEggs.cs
  Content.Shared/ADT/Changeling/Components/ChangelingComponent.cs
  Content.Shared/ADT/Changeling/Components/SyntLingEggsHolder.cs
  Content.Shared/Alert/AlertType.cs
  Resources/Locale/ru-RU/ADT/alerts.ftl
  Resources/Prototypes/ADT/Alerts/alerts.yml
  Resources/Textures/Interface/Alerts/ling-refresh.png
Labels: Changes: Localization

#499 Ashtray
  Resources/Locale/ru-RU/ADT/Lavaland/ashwalker.ftl
  Resources/Prototypes/ADT/Damage/ADTmodifiers.yml
  Resources/Prototypes/ADT/Lavaland/NPCs/AshWalker/AshWalker.yml
  Resources/Prototypes/ADT/Lavaland/NPCs/AshWalker/AshWalkerEquipment.yml
  Resources/Prototypes/ADT/Lavaland/NPCs/BaseHumLavalandMob.yml
  Resources/Textures/ADT/Mobs/Lavaland/ashwalker.rsi/ash.png
  Resources/Textures/ADT/Mobs/Lavaland/ashwalker.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#506 перевоооодыыы
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/eyes/hud.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/helmets.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/armor.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/machine/production.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/syndicate_gadgets/singularity_beacon.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/materials/materials.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/anomaly_equipment.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/walls/walls.ftl
  Resources/Prototypes/Entities/Structures/Walls/walls.yml
Labels: Changes: Localization, No C#

#509 Перевёл доп. закон киборга СБ (емагнутого), отредачил опечатку в законах боргов, добавил перевод ПП станнера
  Resources/Locale/ru-RU/ADT/Objects/Mobs/cyborg_sec.ftl
  Resources/Locale/ru-RU/station-laws/laws.ftl
  Resources/Locale/ru-RU/weapons/guns/disablerSMG.ftl
Labels: Changes: Localization, No C#

#510 Исправил наитупейший баг одного из прошлых ПРов.
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSystem.Abilities.cs
  Content.Server/ADT/Changeling/EntitySystems/LingHallucinationSystem.cs
  Content.Server/ADT/Changeling/EntitySystems/LingHallucinationsSystem.cs
  Content.Shared/ADT/Changeling/Components/ChangelingComponent.cs
  Content.Shared/ADT/Changeling/Components/LingHallucinationComponent.cs
  Content.Shared/ADT/Changeling/Components/LingHallucinationsComponent.cs
  Content.Shared/Eye/VisibilityFlags.cs
  Resources/Locale/ru-RU/ADT/Actions/action_changeling.ftl
  Resources/Prototypes/ADT/Narcotic.yml
  Resources/Prototypes/ADT/changeling/ling_catalog.yml
  Resources/Prototypes/ADT/changeling/mobs.yml
  Resources/Prototypes/Entities/Mobs/Species/slime.yml
Labels: Changes: Localization

#513 Fix and new ghost-role
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/ghost/roles/ghost-role.ftl
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/sec_cyborg.yml
  Resources/Prototypes/ADT/Entities/Mobs/player/humanoid.yml
  Resources/Prototypes/ADT/Entities/Objects/Device/Misc/translator_implants.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
  Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
Labels: Changes: Localization, No C#

#512 Одел иконки действий в форму. Кринжа будет меньше
  Resources/Textures/Interface/Actions/actions_ling.rsi/lesser_form.png
  Resources/Textures/Interface/Actions/actions_ling.rsi/regenerate.png
  Resources/Textures/Interface/Actions/actions_ling.rsi/transform.png
Labels: Changes: Sprites, No C#

#514 добавил наркотик космозин
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Reagents/effects/narcotic_effects.ftl
  Resources/Locale/ru-RU/reagents/meta/narcotics.ftl
  Resources/Prototypes/Reagents/narcotics.yml
  Resources/Prototypes/Recipes/Reactions/medicine.yml
Labels: Changes: Localization, No C#

#515 Компонент выбора языков (общегалактический и двоичный) для пИИ
  Resources/Prototypes/Entities/Objects/Fun/pai.yml
Labels: No C#

#517 Предобновный апдейт
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSystem.Abilities.cs
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSystem.cs
  Content.Server/ADT/Changeling/EntitySystems/LingHallucinationsSystem.cs
  Content.Shared/ADT/Changeling/Components/ChangelingComponent.cs
  Content.Shared/ADT/Changeling/SharedChangeling.cs
  Resources/Audio/ADT/resonant.ogg
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Actions/action_changeling.ftl
  Resources/Locale/ru-RU/ADT/hallucinations.ftl
  Resources/Locale/ru-RU/game-ticking/preset-changeling.ftl
  Resources/Prototypes/ADT/Narcotic.yml
  Resources/Prototypes/ADT/changeling/changeling.yml
  Resources/Prototypes/ADT/changeling/ling_catalog.yml
  Resources/Textures/ADT/Mobs/hallucinations.rsi/dead.png
  Resources/Textures/ADT/Mobs/hallucinations.rsi/medical.png
  Resources/Textures/ADT/Mobs/hallucinations.rsi/meta.json
  Resources/Textures/ADT/Mobs/hallucinations.rsi/musician.png
  Resources/Textures/ADT/Mobs/hallucinations.rsi/nukeop.png
  Resources/Textures/ADT/Mobs/hallucinations.rsi/yeti.png
  Resources/Textures/Interface/Actions/actions_ling.rsi/meta.json
  Resources/Textures/Interface/Actions/actions_ling.rsi/resonant_shriek.png
Labels: Changes: Sprites, Changes: Localization

#516 машины для ивента
  Resources/Audio/ADT/Rimworld/rimworld_badalert.ogg
  Resources/Audio/ADT/Rimworld/rimworld_ilikeithere.ogg
  Resources/Audio/ADT/Rimworld/rimworld_movingon.ogg
  Resources/Audio/ADT/Rimworld/rimworld_raidalert.ogg
  Resources/Audio/ADT/Rimworld/rimworld_raidmusic1.ogg
  Resources/Audio/ADT/Rimworld/rimworld_starscape.ogg
  Resources/Audio/ADT/Rimworld/rimworld_terramorfer.ogg
  Resources/Audio/ADT/Rimworld/rimworld_theselands.ogg
  Resources/Audio/ADT/Rimworld/rimworld_tribal.ogg
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/other.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Boxes/food_packs.yml
  Resources/Prototypes/ADT/Entities/Mobs/wild_animals.yml
  Resources/Prototypes/ADT/Entities/Structures/Machines/non_electrical_machines.yml
  Resources/Prototypes/ADT/Recipes/Construction/Graph/bonfire.yml
  Resources/Prototypes/ADT/Recipes/Construction/furniture.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml
  Resources/Prototypes/Entities/Structures/Decoration/bonfire.yml
  Resources/Prototypes/NES/Ivents/frostpunk.yml
  Resources/Textures/ADT/Mobs/Animals/wild_pig.rsi/dead.png
  Resources/Textures/ADT/Mobs/Animals/wild_pig.rsi/meta.json
  Resources/Textures/ADT/Mobs/Animals/wild_pig.rsi/pig.png
  Resources/Textures/ADT/Objects/Decoration/forerunners_computer.rsi/icon.png
  Resources/Textures/ADT/Objects/Decoration/forerunners_computer.rsi/meta.json
  Resources/Textures/ADT/Objects/Decoration/forerunners_sphere.rsi/icon.png
  Resources/Textures/ADT/Objects/Decoration/forerunners_sphere.rsi/meta.json
  Resources/Textures/ADT/Objects/Storage/rimworld_mre.rsi/icon.png
  Resources/Textures/ADT/Objects/Storage/rimworld_mre.rsi/meta.json
  Resources/Textures/ADT/Structures/Doors/forerunners_door.rsi/closed.png
  Resources/Textures/ADT/Structures/Doors/forerunners_door.rsi/closing.png
  Resources/Textures/ADT/Structures/Doors/forerunners_door.rsi/meta.json
  Resources/Textures/ADT/Structures/Doors/forerunners_door.rsi/open.png
  Resources/Textures/ADT/Structures/Doors/forerunners_door.rsi/opening.png
  Resources/Textures/ADT/Structures/Machines/food_furnance.rsi/meta.json
  Resources/Textures/ADT/Structures/Machines/food_furnance.rsi/mw-o.png
  Resources/Textures/ADT/Structures/Machines/food_furnance.rsi/mw.png
  Resources/Textures/ADT/Structures/Machines/food_furnance.rsi/mw0.png
  Resources/Textures/ADT/Structures/Machines/food_furnance.rsi/mw_running_unlit.png
  Resources/Textures/ADT/Structures/Machines/food_furnance.rsi/mw_unlit.png
  Resources/Textures/ADT/Structures/Machines/food_furnance.rsi/mwb.png
  Resources/Textures/ADT/Structures/Machines/food_furnance.rsi/mwbloody.png
  Resources/Textures/ADT/Structures/Machines/food_furnance.rsi/mwbloody0.png
  Resources/Textures/ADT/Structures/Machines/food_furnance.rsi/mwbloody1.png
  Resources/Textures/ADT/Structures/Machines/food_furnance.rsi/mwbloodyo.png
  Resources/Textures/ADT/Structures/Machines/food_furnance.rsi/mwo.png
  Resources/Textures/ADT/Structures/Machines/furnance.rsi/icon.png
  Resources/Textures/ADT/Structures/Machines/furnance.rsi/meta.json
  Resources/Textures/ADT/Structures/Machines/water_well.rsi/icon.png
  Resources/Textures/ADT/Structures/Machines/water_well.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#519 Update operator centcomm
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/Misc/new_recipes_book.ftl
  Resources/Maps/centcomm.yml
  Resources/Prototypes/ADT/Entities/Mobs/player/humanoid.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/SrpOperatorCenCommBook.yml
  Resources/Prototypes/ADT/Guidebook/srp.yml
  Resources/ServerInfo/ADT/SrpOperatorCentComm.xml
  Resources/Textures/ADT/Objects/Misc/srp_operatorcentcomm_book.rsi/icon.png
  Resources/Textures/ADT/Objects/Misc/srp_operatorcentcomm_book.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#, Changes: Map, Status: Needs Review

#521 Добавил заготовки скафандра, слот очков для Агоста.
  Resources/Locale/ru-RU/ADT/Clothing/Hardsuits/Hardsuits.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Head/head_helmet_security_modern.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/Hardsuits/security_modern.yml
  Resources/Prototypes/InventoryTemplates/aghost_inventory_template.yml
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern.rsi/off-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern.rsi/off-inhand-left.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern.rsi/off-inhand-right.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern.rsi/on-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern.rsi/on-inhand-left.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern.rsi/on-inhand-right.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_b.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_b.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_b.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_b.rsi/off-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_b.rsi/off-inhand-left.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_b.rsi/off-inhand-right.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_b.rsi/on-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_b.rsi/on-inhand-left.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_b.rsi/on-inhand-right.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_g.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_g.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_g.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_g.rsi/off-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_g.rsi/off-inhand-left.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_g.rsi/off-inhand-right.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_g.rsi/on-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_g.rsi/on-inhand-left.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_g.rsi/on-inhand-right.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_p.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_p.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_p.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_p.rsi/off-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_p.rsi/off-inhand-left.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_p.rsi/off-inhand-right.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_p.rsi/on-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_p.rsi/on-inhand-left.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/head_helmet_security_modern_p.rsi/on-inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern_b.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern_b.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern_b.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern_b.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern_b.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern_g.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern_g.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern_g.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern_g.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern_g.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern_p.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern_p.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern_p.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern_p.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/security_modern_p.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#528 описание КЗ немного съехало
  Resources/ServerInfo/ADT/srp/KorporateZakonMedium.xml
Labels: No C#

#518 Коллективный разум
  Content.Client/ADT/CollectiveMind/CollectiveMindSystem.cs
  Content.Client/Chat/Managers/ChatManager.cs
  Content.Client/Chat/Managers/IChatManager.cs
  Content.Client/Input/ContentContexts.cs
  Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs
  Content.Client/UserInterface/Systems/Chat/ChatUIController.cs
  Content.Client/UserInterface/Systems/Chat/Controls/ChannelFilterPopup.xaml.cs
  Content.Client/UserInterface/Systems/Chat/Controls/ChannelSelectorPopup.cs
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSystem.cs
  Content.Server/ADT/CollectiveMind/CollectiveMindCommand.cs
  Content.Server/Chat/Systems/ChatSystem.cs
  Content.Shared/ADT/Changeling/Components/ChangelingComponent.cs
  Content.Shared/ADT/CollectiveMind/CollectiveMindComponent.cs
  Content.Shared/Chat/ChatChannel.cs
  Content.Shared/Chat/ChatSelectChannel.cs
  Content.Shared/Chat/SharedChatSystem.cs
  Content.Shared/Input/ContentKeyFunctions.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/collectivemind/collective-mind.ftl
  Resources/Locale/ru-RU/ADT/collectivemind/options-menu.ftl
  Resources/Locale/ru-RU/ADT/collectivemind/radio.ftl
  Resources/Locale/ru-RU/ADT/collectivemind/rank.ftl
  Resources/Prototypes/ADT/CollectiveMind/channels.yml
  Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
  Resources/Prototypes/Entities/Mobs/NPCs/carp.yml
  Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
  Resources/Prototypes/Entities/Mobs/Player/dragon.yml
  Resources/Prototypes/Entities/Mobs/Species/diona.yml
  Resources/Prototypes/Entities/Objects/Fun/pai.yml
  Resources/keybinds.yml
Labels: Changes: Localization, Changes: UI

#530 пару фиксов перед мехами
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Fills/lavalend.ftl
  Resources/Prototypes/ADT/Fills/Crates/ADTrewards.yml
  Resources/Prototypes/Entities/Structures/Walls/asteroid.yml
  Resources/Prototypes/Procedural/salvage_loot.yml
  Resources/Prototypes/Procedural/salvage_rewards.yml
Labels: Changes: Localization, No C#

#525 Накинул время на гост-роль ПЦк.
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
Labels: No C#

#527 Ивент Cult of the Lamb
  Content.Server/Atmos/EntitySystems/FirestarterSystem.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/Misc/misc.ftl
  Resources/Locale/ru-RU/ADT/Objects/Mobs/humanoid.ftl
  Resources/Prototypes/ADT/Entities/Mobs/player/humanoid.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/BoneKnife.yml
  Resources/Textures/ADT/Objects/Misc/empity.rsi/icon.png
  Resources/Textures/ADT/Objects/Misc/empity.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization

#532 Переводы масок,фикс сумок
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/masks/masks.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Back/satchels.yml
Labels: Changes: Localization, No C#

#534 (заказ) кассета Wir sind des Geyers schwarzer
  Resources/Audio/BoomBox/Botho_Lucas_Chor_Wir_sind_des_Geyers_schwarzer_Haufen.ogg
  Resources/Locale/ru-RU/ADT/boombox/boombox.ftl
  Resources/Prototypes/ADT/Entities/Objects/Device/boombox.yml
Labels: Changes: Localization, No C#

#535 Банданы в одеждомате
  Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
Labels: No C#

#536 Дебафы
  Resources/Prototypes/ADT/Entities/Clothing/Back/backpacks.yml
  Resources/Prototypes/ADT/Entities/Clothing/Hands/gloves.yml
  Resources/Prototypes/ADT/Entities/Clothing/Masks/mask.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/Jumpsuit.yml
Labels: No C#

#537 новый КЗ
  Resources/Locale/ru-RU/ADT/guidebook/guides.ftl
  Resources/Prototypes/ADT/Entities/Objects/Misc/investigator_sjp.yml
  Resources/Prototypes/ADT/Guidebook/srp.yml
  Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
  Resources/ServerInfo/ADT/srp/KorporateZakon.xml
  Resources/ServerInfo/ADT/srp/KorporateZakon1XX.xml
  Resources/ServerInfo/ADT/srp/KorporateZakon2XX.xml
  Resources/ServerInfo/ADT/srp/KorporateZakon3XX.xml
  Resources/ServerInfo/ADT/srp/KorporateZakon4XX.xml
  Resources/ServerInfo/ADT/srp/KorporateZakon5XX.xml
  Resources/ServerInfo/ADT/srp/KorporateZakonCritical.xml
  Resources/ServerInfo/ADT/srp/KorporateZakonMedium.xml
  Resources/ServerInfo/ADT/srp/KorporateZakonMinor.xml
  Resources/ServerInfo/ADT/srp/KorporateZakonSerious.xml
  Resources/ServerInfo/ADT/srp/KorporateZakonSuperHeavy.xml
Labels: Changes: Localization, No C#

#543 Исправил баг на скафах!!!
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/Hardsuits/security_modern.yml
Labels: No C#
