Repository xtray85/space_station, pull requests merged in 2024-02, with the labels that each got.

#366 Робототехник как роль
  Resources/Locale/ru-RU/ADT/Roboticist/robo.flt
  Resources/Locale/ru-RU/job/job-description.ftl
  Resources/Locale/ru-RU/job/job-names.ftl
  Resources/Prototypes/ADT/Roboticist/job.yml
  Resources/Prototypes/ADT/Roboticist/pda.yml
  Resources/Prototypes/ADT/Roboticist/spawner.yml
  Resources/Prototypes/Entities/Objects/Devices/encryption_keys.yml
  Resources/Prototypes/Maps/adtpacked.yml
  Resources/Prototypes/Maps/aspid.yml
  Resources/Prototypes/Maps/atlas.yml
  Resources/Prototypes/Maps/bagel.yml
  Resources/Prototypes/Maps/box.yml
  Resources/Prototypes/Maps/cluster.yml
  Resources/Prototypes/Maps/core.yml
  Resources/Prototypes/Maps/europa.yml
  Resources/Prototypes/Maps/fland.yml
  Resources/Prototypes/Maps/gemini.yml
  Resources/Prototypes/Maps/marathon.yml
  Resources/Prototypes/Maps/meta.yml
  Resources/Prototypes/Maps/omega.yml
  Resources/Prototypes/Maps/origin.yml
  Resources/Prototypes/Maps/packed.yml
  Resources/Prototypes/Maps/reach.yml
  Resources/Prototypes/Maps/saltern.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Textures/Clothing/Uniforms/Jumpskirt/roboticist.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/roboticist.rsi/icon.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/roboticist.rsi/inhand-left.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/roboticist.rsi/inhand-right.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/roboticist.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/roboticist.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/roboticist.rsi/icon.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/roboticist.rsi/inhand-left.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/roboticist.rsi/inhand-right.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/roboticist.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#, Changes: Map

#368 Морфин
  Content.Client/GG/PainKillerSystem.cs
  Content.Client/UserInterface/Systems/DamageOverlays/DamageOverlayUiController.cs
  Content.Shared/Alert/AlertType.cs
  Content.Shared/Damage/Systems/SlowOnDamageSystem.cs
  Content.Shared/GG/PainkillerComponent.cs
  Resources/Locale/ru-RU/ADT/morphine.ftl
  Resources/Prototypes/Entities/Mobs/Species/base.yml
  Resources/Prototypes/GG/painkiller.yml
  Resources/Textures/GG/Interface/Alerts/painkiller.png
Labels: Changes: Localization

#373 Маленькие изменения защиты скафандров
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Labels: No C#

#374 borgi
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/Mobs/borgi.ftl
  Resources/Prototypes/ADT/Entities/Mobs/borgi.yml
  Resources/Textures/ADT/Mobs/Pets/borgi.rsi/borgi.png
  Resources/Textures/ADT/Mobs/Pets/borgi.rsi/borgi_dead.png
  Resources/Textures/ADT/Mobs/Pets/borgi.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#378 Фикс факций урсов
  Resources/Prototypes/ADT/Ursus/Entities/Mobs/Player/Ursus.yml
  Resources/Prototypes/ADT/Ursus/faction.yml
Labels: No C#

#380 Фикс фишек для казино
  Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs
  Resources/Locale/ru-RU/chat/managers/chat-manager.ftl
  Resources/Maps/Misc/planet_terminal.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/Cards/card_base.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/Cards/poker_chips.yml
  Resources/Prototypes/Reagents/medicine.yml
Labels: Changes: Localization

#381 Стазисная смерть генокрада
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSystem.Abilities.cs
  Content.Shared/ADT/Changeling/Components/ChangelingComponent.cs
  Content.Shared/ADT/Changeling/SharedChangeling.cs
  Content.Shared/CCVar/CCVars.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Actions/action_changeling.ftl
  Resources/Locale/ru-RU/game-ticking/preset-changeling.ftl
  Resources/Prototypes/ADT/changeling/changeling.yml
  Resources/Prototypes/ADT/changeling/ling_catalog.yml
Labels: DO NOT MERGE, Changes: Localization

#385 увеличение емкости СМЭС
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/power/smes.ftl
  Resources/Prototypes/ADT/Entities/Structures/Power/industrial.yml
  Resources/Prototypes/Entities/Structures/Power/smes.yml
Labels: Changes: Localization, No C#

#386 нерф джаги, ап обычных скафов, замена винтовки у обр и возвращение но…
  Resources/Prototypes/ADT/Catalog/uplink.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Textures/Objects/Misc/stock_parts.rsi/capacitor.png
  Resources/Textures/Objects/Misc/stock_parts.rsi/matter_bin.png
  Resources/Textures/Objects/Misc/stock_parts.rsi/micro_mani.png
  Resources/Textures/Structures/Power/substation.rsi/charging.png
  Resources/Textures/Structures/Power/substation.rsi/dead.png
  Resources/Textures/Structures/Power/substation.rsi/full.png
  Resources/Textures/Structures/Power/substation.rsi/screen.png
  Resources/Textures/Structures/Power/substation.rsi/substation.png
  Resources/Textures/Structures/Power/substation.rsi/substation_static.png
  Resources/Textures/Structures/Wallmounts/Lighting/light_tube.rsi/base.png
  Resources/Textures/Structures/Wallmounts/Lighting/light_tube.rsi/broken.png
  Resources/Textures/Structures/Wallmounts/Lighting/light_tube.rsi/burned.png
  Resources/Textures/Structures/Wallmounts/Lighting/light_tube.rsi/empty.png
  Resources/Textures/Structures/Wallmounts/Lighting/light_tube.rsi/glow.png
  Resources/Textures/Structures/Wallmounts/Lighting/light_tube.rsi/meta.json
Labels: Changes: Sprites, No C#

#393 Чуть потемней стало зрение симпл мобов
  Resources/Prototypes/Entities/Mobs/NPCs/simplemob.yml
Labels: No C#

#370 Киборг СБ, Мелкие фиксы
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Fun/ADTtoys.ftl
  Resources/Locale/ru-RU/ADT/paper/stamp-component.ftl
  Resources/Locale/ru-RU/ADT/paper/stamprubber.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/Hardsuits/USSP.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/damage_mod_set.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/equipment.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/job.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/ftl_point.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/paper.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Rifels/abakan.yml
  Resources/Prototypes/Entities/Mobs/Player/terminator.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/armblade.yml
  Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
  Resources/Textures/ADT/Clothing/Back/ertleader_cyb.rsi/equipped-BACKPACK.png
  Resources/Textures/ADT/Clothing/Back/ertleader_cyb.rsi/icon.png
  Resources/Textures/ADT/Clothing/Back/ertleader_cyb.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Back/ertleader_cyb.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Back/ertleader_cyb.rsi/meta.json
  Resources/Textures/ADT/Clothing/Neck/mantles/cybmantle_shoulder.rsi/equipped-NECK-unshaded.png
  Resources/Textures/ADT/Clothing/Neck/mantles/cybmantle_shoulder.rsi/equipped-NECK.png
  Resources/Textures/ADT/Clothing/Neck/mantles/cybmantle_shoulder.rsi/icon.png
  Resources/Textures/ADT/Clothing/Neck/mantles/cybmantle_shoulder.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/schrodinger_coat.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/schrodinger_coat.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/schrodinger_coat.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/schrodinger_coat.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/schrodinger_coat.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_riker.png
  Resources/Textures/ADT/Structures/Machines/printer.rsi/building.png
  Resources/Textures/ADT/Structures/Machines/printer.rsi/icon.png
  Resources/Textures/ADT/Structures/Machines/printer.rsi/idle.png
  Resources/Textures/ADT/Structures/Machines/printer.rsi/inserting.png
  Resources/Textures/ADT/Structures/Machines/printer.rsi/meta.json
  Resources/Textures/ADT/Structures/Machines/printer.rsi/panel.png
  Resources/Textures/Objects/Weapons/Guns/Projectiles/projectiles_tg.rsi/adtomnilaser.png
  Resources/Textures/Objects/Weapons/Guns/Projectiles/projectiles_tg.rsi/meta.json
Labels: DO NOT MERGE, Changes: Sprites, Changes: Localization, No C#

#379 Qupdate
  Resources/Audio/ADT/Weapons/Guns/Gunshots/50_deagle.ogg
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/Guns.ftl
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/sec_cyborg.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/Cards/card_jocker.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
  Resources/Prototypes/ADT/Tajaran/Entities/Mobs/Species/Tajaran.yml
  Resources/Prototypes/ADT/Vulpkanin/Entities/Mobs/Species/Vulpkanin.yml
  Resources/Prototypes/StatusIcon/antag.yml
  Resources/Textures/ADT/Objects/Weapons/Guns/Pistols/deser_eagle.rsi/base.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Pistols/deser_eagle.rsi/bolt-open.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Pistols/deser_eagle.rsi/equipped-BELT.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Pistols/deser_eagle.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Pistols/deser_eagle.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Pistols/deser_eagle.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Pistols/deser_eagle.rsi/mag-0.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Pistols/deser_eagle.rsi/meta.json
  Resources/Textures/Interface/Misc/job_icons.rsi/JobIconChangeling.png
  Resources/Textures/Interface/Misc/job_icons.rsi/meta.json
Labels: DO NOT MERGE, Changes: Sprites, Changes: Localization, No C#

#397 Фиксики
  Content.Server/ADT/Changeling/EntitySystems/ChangelingSystem.cs
  Resources/Locale/ru-RU/ADT/Clothing/USSP.ftl
  Resources/Locale/ru-RU/job/job-names.ftl
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/Hardsuits/USSP.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/job.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/sec_cyborg.yml
  Resources/Textures/ADT/Clothing/Head/Hardsuits/ussp_rd.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/ussp_rd.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/ussp_rd.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hardsuits/ussp_rd.rsi/off-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hardsuits/ussp_rd.rsi/on-equipped-HELMET.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/ussp_rd.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/ussp_rd.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/ussp_rd.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/ussp_rd.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/ussp_rd.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization

#395 Бумбокс
  Content.Client/ADT/BoomBox/UI/BoomBoxBoundUi.cs
  Content.Client/ADT/BoomBox/UI/BoomBoxWindow.xaml
  Content.Client/ADT/BoomBox/UI/BoomBoxWindow.xaml.cs
  Content.Server/ADT/BoomBoxTape/BoomBoxTapeComponent.cs
  Content.Server/ADT/Boombox/BoomBoxComponent.cs
  Content.Server/ADT/Boombox/BoomBoxSystem.cs
  Content.Server/Radio/Components/RadioMicrophoneComponent.cs
  Content.Shared/ADT/Boombox/SharedBoomBox.cs
  Resources/Audio/BoomBox/AssHole.ogg
  Resources/Audio/BoomBox/AssHoleMono.ogg
  Resources/Audio/BoomBox/Running-out-mono.ogg
  Resources/Audio/BoomBox/Running-out.ogg
  Resources/Audio/BoomBox/Tear-of-veil-mono.ogg
  Resources/Audio/BoomBox/Tear-of-veil.ogg
  Resources/Audio/BoomBox/The-End-of-The-Expedition-mono.ogg
  Resources/Audio/BoomBox/The-End-of-The-Expedition.ogg
  Resources/Audio/BoomBox/TheWizard-mono.ogg
  Resources/Audio/BoomBox/TheWizard.ogg
  Resources/Audio/BoomBox/TheWizardMono.ogg
  Resources/Audio/BoomBox/sources.txt
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/boombox/boombox.ftl
  Resources/Prototypes/ADT/Entities/Objects/Device/boombox.yml
  Resources/Prototypes/ADT/tags.yml
  Resources/Textures/Objects/Devices/boombox.rsi/boombox.png
  Resources/Textures/Objects/Devices/boombox.rsi/meta.json
  Resources/Textures/Objects/Devices/boomboxtape.rsi/meta.json
  Resources/Textures/Objects/Devices/boomboxtape.rsi/tape.png
Labels: Changes: Sprites, Changes: Localization, Changes: UI

#396 фикс.
  Resources/Prototypes/ADT/Novakid/Mobs/Species/novakid.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/ipc.yml
Labels: No C#

#399 фикс нюкеров и локализации
  Content.Server/GameTicking/Rules/Components/NukeopsRuleComponent.cs
  Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
  Content.Server/GameTicking/Rules/RevolutionaryRuleSystem.cs
  Content.Server/RoundEnd/RoundEndSystem.cs
  Content.Server/StationEvents/Events/LoneOpsSpawnRule.cs
  Resources/Locale/en-US/nukeops/nuke-ops.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Belt/belt.ftl
  Resources/Locale/ru-RU/ADT/prototypes/entities/structures/cryopod.ftl
  Resources/Locale/ru-RU/administration/ui/actions.ftl
  Resources/Locale/ru-RU/advertisements/vending/curadrobe.ftl
  Resources/Locale/ru-RU/disease/miasma.ftl
  Resources/Locale/ru-RU/nukeops/nuke-ops.ftl
  Resources/Locale/ru-RU/round-end/cryostorage.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/security.ftl
Labels: Changes: Localization

#404 Update .gitmodules
  .gitmodules
Labels: No C#

#400 фикс мини огнетушителя
  Resources/Prototypes/ADT/Entities/Objects/Misc/mini_fire_extinguisher.yml
Labels: No C#

#402 Орлуум
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/en-US/ADT/language/languages.ftl
  Resources/Locale/ru-RU/ADT/language/languages.ftl
  Resources/Locale/ru-RU/ADT/language/translator.ftl
  Resources/Prototypes/ADT/Drask/Mobs/Player/Drask.yml
  Resources/Prototypes/ADT/Entities/Objects/Device/Misc/translator_implants.yml
  Resources/Prototypes/ADT/Entities/Objects/Device/Misc/translators.yml
  Resources/Prototypes/ADT/Languages/languages.yml
  Resources/Prototypes/ADT/Recipes/Lathes/translators.yml
  Resources/Prototypes/ADT/Research/translators.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Labels: Changes: Localization, No C#

#409 Revert "remove racism (#23039)"
  Content.Server/StationEvents/Events/IonStormRule.cs
  Resources/Locale/en-US/station-events/events/ion-storm.ftl
  Resources/Prototypes/Datasets/ion_storm.yml
Labels: Changes: Localization

#410 Revert "Ports the /tg/ shotgun sprites (#22539)"
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
  Resources/Textures/Objects/Weapons/Guns/Shotguns/db_shotgun.rsi/equipped-BACKPACK.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/db_shotgun.rsi/icon.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/db_shotgun.rsi/inhand-left.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/db_shotgun.rsi/inhand-right.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/db_shotgun.rsi/meta.json
  Resources/Textures/Objects/Weapons/Guns/Shotguns/enforcer.rsi/bolt-open.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/enforcer.rsi/equipped-BACKPACK.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/enforcer.rsi/icon.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/enforcer.rsi/inhand-left.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/enforcer.rsi/inhand-right.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/enforcer.rsi/meta.json
  Resources/Textures/Objects/Weapons/Guns/Shotguns/improvised_shotgun.rsi/inhand-left.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/improvised_shotgun.rsi/inhand-right.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/improvised_shotgun.rsi/meta.json
  Resources/Textures/Objects/Weapons/Guns/Shotguns/inhands_64x.rsi/db-inhand-left.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/inhands_64x.rsi/db-inhand-right.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/inhands_64x.rsi/enforcer-inhand-left.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/inhands_64x.rsi/enforcer-inhand-right.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/inhands_64x.rsi/improvised-inhand-left.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/inhands_64x.rsi/improvised-inhand-right.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/inhands_64x.rsi/meta.json
  Resources/Textures/Objects/Weapons/Guns/Shotguns/inhands_64x.rsi/pump-inhand-left.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/inhands_64x.rsi/pump-inhand-right.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/inhands_64x.rsi/sawn-inhand-left.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/inhands_64x.rsi/sawn-inhand-right.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/pump.rsi/bolt-open.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/pump.rsi/equipped-BACKPACK.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/pump.rsi/icon.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/pump.rsi/inhand-left.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/pump.rsi/inhand-right.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/pump.rsi/meta.json
  Resources/Textures/Objects/Weapons/Guns/Shotguns/sawn.rsi/bolt-open.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/sawn.rsi/equipped-BACKPACK.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/sawn.rsi/icon.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/sawn.rsi/inhand-left.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/sawn.rsi/inhand-right.png
  Resources/Textures/Objects/Weapons/Guns/Shotguns/sawn.rsi/meta.json
  Resources/Textures/Structures/Wallmounts/shotgun_cabinet.rsi/cabinet-empty-open.png
  Resources/Textures/Structures/Wallmounts/shotgun_cabinet.rsi/cabinet-filled-closed.png
  Resources/Textures/Structures/Wallmounts/shotgun_cabinet.rsi/cabinet-filled-open.png
  Resources/Textures/Structures/Wallmounts/shotgun_cabinet.rsi/cabinet.png
  Resources/Textures/Structures/Wallmounts/shotgun_cabinet.rsi/meta.json
  Resources/Textures/Structures/Wallmounts/shotgun_cabinet.rsi/shotgun.png
Labels: Changes: Sprites, No C#

#411 Urss UPDATE
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Clothing/Head/hats.ftl
  Resources/Locale/ru-RU/ADT/Clothing/OuterClothing/furcoat.ftl
  Resources/Locale/ru-RU/ADT/Fun/ADTtoys.ftl
  Resources/Locale/ru-RU/ADT/Markings/vulpmarkings.ftl
  Resources/Locale/ru-RU/ADT/Ursus/custom.ftl
  Resources/Prototypes/ADT/Damage/ADTmodifiers.yml
  Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/hats.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/coats.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/sec_cyborg.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/moonshine_still.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/ADT/Ursus/Entities/Mobs/Customization/Markings/Ursus.yml
  Resources/Prototypes/ADT/Ursus/Entities/Mobs/Player/Ursus.yml
  Resources/Prototypes/ADT/Ursus/Entities/Mobs/Species/Ursus.yml
  Resources/Prototypes/ADT/Ursus/Species/Ursus.yml
  Resources/Prototypes/ADT/Vulpkanin/Entities/Mobs/Customization/Markings/Vulpkanin.yml
  Resources/Prototypes/ADT/Vulpkanin/Entities/Mobs/Customization/Markings/Vulpkanin_hair.yml
  Resources/Prototypes/ADT/Vulpkanin/Species/Vulpkanin.yml
  Resources/Prototypes/Corvax/Roles/Jobs/Command/iaa.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/gauze.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/kobalt.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/reptilian.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Customization/ears.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Customization/snouts.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Customization/tails.yml
  Resources/Textures/ADT/Clothing/Head/Hats/urs_hat.rsi/equipped-HELMET-urs.png
  Resources/Textures/ADT/Clothing/Head/Hats/urs_hat.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/urs_hat.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/urs_hat.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/urs_coat.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/urs_coat.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/urs_coat.rsi/meta.json
  Resources/Textures/ADT/Mobs/Ursus/custom.rsi/foot_left.png
  Resources/Textures/ADT/Mobs/Ursus/custom.rsi/foot_right.png
  Resources/Textures/ADT/Mobs/Ursus/custom.rsi/hand_left.png
  Resources/Textures/ADT/Mobs/Ursus/custom.rsi/hand_right.png
  Resources/Textures/ADT/Mobs/Ursus/custom.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_ursus.png
  Resources/Textures/Mobs/Customization/vulpkanin_head.rsi/ear_back.png
  Resources/Textures/Mobs/Customization/vulpkanin_head.rsi/meta.json
  Resources/Textures/Mobs/Customization/vulpkanin_tail.rsi/meta.json
  Resources/Textures/Mobs/Customization/vulpkanin_tail.rsi/tail_m.png
Labels: Changes: Sprites, Changes: Localization, No C#

#412 Черты роста, низкий и высокий
  Content.Server/ADT/SizeAttribute/SizeAttributeComponent.cs
  Content.Server/ADT/SizeAttribute/SizeAttributeSystem.cs
  Content.Server/ADT/SizeAttribute/SizeAttributeWhitelistComponent.cs
  Content.Server/Cloning/CloningSystem.cs
  Content.Shared/ADT/Cloning/ITransferredByCloning.cs
  Content.Shared/ADT/Item/PseudoItemComponent.cs
  Resources/Locale/ru-RU/ADT/traits/neutral.ftl
  Resources/Prototypes/ADT/Demon/Mobs/Player/demon.yml
  Resources/Prototypes/ADT/Drask/Mobs/Player/Drask.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/sec_cyborg.yml
  Resources/Prototypes/ADT/Felinid/Mobs/Player/felinid.yml
  Resources/Prototypes/ADT/Tajaran/Entities/Mobs/Player/Tajaran.yml
  Resources/Prototypes/ADT/Vulpkanin/Entities/Mobs/Player/Vulpkanin.yml
  Resources/Prototypes/Entities/Mobs/Player/terminator.yml
  Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
  Resources/Prototypes/Entities/Mobs/Species/slime.yml
  Resources/Prototypes/Entities/Mobs/base.yml
  Resources/Prototypes/Traits/neutral.yml
Labels: Changes: Localization

#416 Скафы под вульп
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Fun/ADTtoys.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/ADT/Vulpkanin/Entities/Mobs/Player/Vulpkanin.yml
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_koff.png
  Resources/Textures/Clothing/Head/Hardsuits/ERThelmets/ertengineer.rsi/meta.json
  Resources/Textures/Clothing/Head/Hardsuits/ERThelmets/ertengineer.rsi/off-equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/ERThelmets/ertengineer.rsi/on-equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/ERThelmets/ertjanitor.rsi/meta.json
  Resources/Textures/Clothing/Head/Hardsuits/ERThelmets/ertjanitor.rsi/off-equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/ERThelmets/ertjanitor.rsi/on-equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/ERThelmets/ertleader.rsi/meta.json
  Resources/Textures/Clothing/Head/Hardsuits/ERThelmets/ertleader.rsi/off-equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/ERThelmets/ertleader.rsi/on-equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/ERThelmets/ertmedical.rsi/meta.json
  Resources/Textures/Clothing/Head/Hardsuits/ERThelmets/ertmedical.rsi/off-equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/ERThelmets/ertmedical.rsi/on-equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/ERThelmets/ertsecurity.rsi/meta.json
  Resources/Textures/Clothing/Head/Hardsuits/ERThelmets/ertsecurity.rsi/off-equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/ERThelmets/ertsecurity.rsi/on-equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/basic.rsi/equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/basic.rsi/meta.json
  Resources/Textures/Clothing/Head/Hardsuits/brigmedic.rsi/meta.json
  Resources/Textures/Clothing/Head/Hardsuits/brigmedic.rsi/off-equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/brigmedic.rsi/on-equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/capspace.rsi/meta.json
  Resources/Textures/Clothing/Head/Hardsuits/capspace.rsi/off-equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/capspace.rsi/on-equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/clown.rsi/meta.json
  Resources/Textures/Clothing/Head/Hardsuits/clown.rsi/off-equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/clown.rsi/on-equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/engineering.rsi/meta.json
  Resources/Textures/Clothing/Head/Hardsuits/engineering.rsi/off-equipped-HELMET-vulp.png
  Resources/Textures/Clothing/Head/Hardsuits/engineering.rsi/on-equipped-HELMET-vulp.png
  Resources/Textures/Objects/Specific/Mech/mecha.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#418 Update meta.json
  Resources/Textures/Objects/Specific/Mech/mecha.rsi/meta.json
Labels: No C#

#420 Торговцы
  Content.Server/ADT/StationEvents/Components/TraderSpawnRuleComponent.cs
  Content.Server/ADT/StationEvents/Events/TraderSpawnRule.cs
  Resources/Locale/ru-RU/ADT/Trader/trader.ftl
  Resources/Locale/ru-RU/ADT/access/access.ftl
  Resources/Maps/Shuttles/trader.yml
  Resources/Prototypes/ADT/Access/trader.yml
  Resources/Prototypes/ADT/Entities/Mobs/player/trader.yml
  Resources/Prototypes/ADT/Entities/Structures/Doors/access.yml
  Resources/Prototypes/ADT/StartingGear/trader.yml
  Resources/Prototypes/GameRules/events.yml
Labels: Changes: Localization

#426 обмотки для ног
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Clothing/boots.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Shoes/Boots.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
  Resources/Textures/ADT/Clothing/Shoes/Boots/black_footwraps.rsi/equipped-FEET-reptilian.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/blackhigh_footwraps.rsi/equipped-FEET-reptilian.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/brown_footwraps.rsi/equipped-FEET-reptilian.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/brown_footwraps.rsi/equipped-FEET.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/brown_footwraps.rsi/icon.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/brown_footwraps.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/brown_footwraps.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/brown_footwraps.rsi/meta.json
  Resources/Textures/ADT/Clothing/Shoes/Boots/brownhigh_footwraps.rsi/equipped-FEET-reptilian.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/brownhigh_footwraps.rsi/equipped-FEET.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/brownhigh_footwraps.rsi/icon.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/brownhigh_footwraps.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/brownhigh_footwraps.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/brownhigh_footwraps.rsi/meta.json
  Resources/Textures/ADT/Clothing/Shoes/Boots/white_footwraps.rsi/equipped-FEET-reptilian.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/whitehigh_footwraps.rsi/equipped-FEET-reptilian.png
Labels: Changes: Sprites, Changes: Localization, No C#

#428 Понижаем накал на сменах
  Content.Client/Corvax/TTS/TTSSystem.cs
  Content.Shared/CCVar/CCVars.cs
  Resources/Audio/BoomBox/barotrauma.ogg
  Resources/Audio/BoomBox/borat.ogg
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/access/access.ftl
  Resources/Locale/ru-RU/escape-menu/ui/options-menu.ftl
  Resources/Prototypes/ADT/Entities/Objects/Device/boombox.yml
  Resources/Prototypes/ADT/Roles/Jobs/Magistrate/Magistrate.yml
  Resources/Prototypes/Corvax/Roles/Jobs/Command/iaa.yml
  Resources/Prototypes/Entities/Objects/Power/powercells.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Entities/Structures/Machines/research.yml
  Resources/Prototypes/Entities/Structures/Power/chargers.yml
  Resources/Prototypes/Entities/Structures/Shuttles/cannons.yml
  Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml
  Resources/Prototypes/secret_weights.yml
  Resources/Textures/Clothing/Head/Hats/brownfedora.rsi/equipped-HELMET.png
  Resources/Textures/Clothing/Head/Hats/brownfedora.rsi/icon.png
Labels: Changes: Sprites, Changes: Localization

#429 срочный фикс драсков
  Resources/Prototypes/Reagents/gases.yml
Labels: No C#

#437 ченджлоги хуня
  Resources/Prototypes/ADT/Felinid/Mobs/Player/felinid.yml
  Resources/Prototypes/ADT/Novakid/Mobs/Player/novakid.yml
  Resources/Prototypes/ADT/Tajaran/Entities/Mobs/Player/Tajaran.yml
  Resources/Prototypes/ADT/Ursus/Entities/Mobs/Player/Ursus.yml
  Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
  Resources/Prototypes/Entities/Mobs/Player/kobalt.yml
  Resources/Prototypes/Entities/Mobs/Species/base.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/ipc.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/shadowkin.yml
  Resources/Prototypes/SimpleStation14/Species/ipc.yml
Labels: No C#
