Repository xtray85/space_station, pull requests merged in 2024-01, with the labels that each got.

#270 Felinid
  Resources/Audio/ADT/Felinid/attributions.yml
  Resources/Audio/ADT/Felinid/cat_growl1.ogg
  Resources/Audio/ADT/Felinid/cat_hiss1.ogg
  Resources/Audio/ADT/Felinid/cat_hiss2.ogg
  Resources/Audio/ADT/Felinid/cat_meow1.ogg
  Resources/Audio/ADT/Felinid/cat_meow2.ogg
  Resources/Audio/ADT/Felinid/cat_meow3.ogg
  Resources/Audio/ADT/Felinid/cat_mew1.ogg
  Resources/Audio/ADT/Felinid/cat_mew2.ogg
  Resources/Audio/ADT/Felinid/cat_purr1.ogg
  Resources/Audio/ADT/Felinid/cat_scream1.ogg
  Resources/Audio/ADT/Felinid/cat_scream2.ogg
  Resources/Audio/ADT/Felinid/cat_scream3.ogg
  Resources/Audio/ADT/Felinid/cat_wilhelm.ogg
  Resources/Prototypes/ADT/Damage/ADTmodifiers.yml
  Resources/Prototypes/ADT/Felinid/Body/Prototypes/felinid.yml
  Resources/Prototypes/ADT/Felinid/Mobs/Player/felinid.yml
  Resources/Prototypes/ADT/Felinid/Mobs/Species/felinid.yml
  Resources/Prototypes/ADT/Felinid/Sound/sound_collections.yml
  Resources/Prototypes/ADT/Felinid/Sound/speech_emote_sounds.yml
  Resources/Prototypes/ADT/Felinid/Sound/speech_emotes.yml
  Resources/Prototypes/ADT/Felinid/Species/felinid.yml
Labels: No C#

#269 Котики
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Fun/ADTtoys.ftl
  Resources/Locale/ru-RU/ADT/Objects/Misc/EvidanceBag.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/EvidenceBag.yml
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_dekus.png
  Resources/Textures/ADT/Objects/Misc/Evidance.rsi/meta.json
  Resources/Textures/ADT/Objects/Misc/Evidance.rsi/place_number.png
  Resources/Textures/ADT/Objects/Misc/Evidance.rsi/place_number2.png
  Resources/Textures/ADT/Objects/Misc/pill_ex.rsi/extezi_ent.png
  Resources/Textures/ADT/Objects/Misc/pill_ex.rsi/meta.json
  Resources/Textures/ADT/Objects/Misc/pill_ex.rsi/trava_ent.png
Labels: Changes: Sprites, Changes: Localization, No C#

#272 Новые компоненты для фелинидов.
  Content.Server/ADT/Abilities/Felinid/CoughingUpHairballComponent.cs
  Content.Server/ADT/Abilities/Felinid/FelinidComponent.cs
  Content.Server/ADT/Abilities/Felinid/FelinidFoodComponent.cs
  Content.Server/ADT/Abilities/Felinid/FelinidSystem.cs
  Content.Server/ADT/Abilities/Felinid/HairballComponent.cs
  Content.Server/Clothing/MaskSystem.cs
  Content.Shared/ADT/Psionics/Events.cs
  Content.Shared/ADT/Psionics/PsychokinesisComponent.cs
  Resources/Audio/ADT/Felinid/hairball.ogg
  Resources/Audio/ADT/Felinid/license.txt
  Resources/Locale/ru-RU/ADT/Felinid/abilities/felinid.ftl
  Resources/Prototypes/ADT/Felinid/Mobs/Species/felinid.yml
  Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
  Resources/Prototypes/Entities/Mobs/NPCs/regalrat.yml
  Resources/Textures/ADT/Icons/verbiconfangs.png
  Resources/Textures/ADT/Objects/Specific/felinid.rsi/icon.png
  Resources/Textures/ADT/Objects/Specific/felinid.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization

#273 киборг горничная
  Resources/Locale/ru-RU/ADT/Tallrobot/tallrobotjani.ftl
  Resources/Prototypes/ADT/Tallrobot/tallrobotjani.yml
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/tallrobotjani.rsi/mekajani.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/tallrobotjani.rsi/mekajanie.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/tallrobotjani.rsi/mekajanier.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/tallrobotjani.rsi/mekajanirest.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/tallrobotjani.rsi/mekajanitipped.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/tallrobotjani.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#281 Upstream
  Resources/Maps/Salvage/cargo-1.yml
  Resources/Maps/Salvage/medium-crashed-shuttle.yml
  Resources/Maps/Salvage/medium-dock.yml
  Resources/Maps/Shuttles/corvax_emergency.yml
  Resources/Maps/gammaarmory.yml
  Resources/Prototypes/Recipes/Construction/Graphs/structures/window.yml
  Resources/Prototypes/Research/civilianservices.yml
  Resources/Prototypes/lobbyscreens.yml
  Resources/Textures/LobbyScreens/revolution.png
  Resources/Textures/LobbyScreens/revolution.yml
Labels: No C#, Changes: Map

#274 Фиксы
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/accent/archaic.ftl
  Resources/Prototypes/Entities/Mobs/Player/terminator.yml
Labels: DO NOT MERGE, Changes: Localization, No C#

#275 Борги
  Resources/Locale/ru-RU/ADT/Tallrobot/tallrobot.ftl
  Resources/Locale/ru-RU/ADT/Tallrobot/tallrobotjani.ftl
  Resources/Prototypes/ADT/Tallrobot/base.yml
  Resources/Prototypes/ADT/Tallrobot/fmeka/fmekacargo.yml
  Resources/Prototypes/ADT/Tallrobot/fmeka/fmekaeng.yml
  Resources/Prototypes/ADT/Tallrobot/fmeka/fmekajani.yml
  Resources/Prototypes/ADT/Tallrobot/meka/mekajani.yml
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekacargo.rsi/fmekacargo-rest.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekacargo.rsi/fmekacargo-tipped.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekacargo.rsi/fmekacargo-wreck.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekacargo.rsi/fmekacargo.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekacargo.rsi/fmekacargoe.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekacargo.rsi/fmekacargoer.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekacargo.rsi/meta.json
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekaeng.rsi/fmekaeng-rest.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekaeng.rsi/fmekaeng-tipped.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekaeng.rsi/fmekaeng-wreck.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekaeng.rsi/fmekaeng.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekaeng.rsi/fmekaenge.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekaeng.rsi/fmekaenger.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekaeng.rsi/meta.json
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekajani.rsi/fmekajani-rest.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekajani.rsi/fmekajani-tipped.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekajani.rsi/fmekajani-wreck.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekajani.rsi/fmekajani.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekajani.rsi/fmekajanie.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekajani.rsi/fmekajanier.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/fmekajani.rsi/meta.json
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/mekajani.rsi/mekajani.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/mekajani.rsi/mekajanie.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/mekajani.rsi/mekajanier.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/mekajani.rsi/mekajanirest.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/mekajani.rsi/mekajanitipped.png
  Resources/Textures/ADT/Mobs/Silicon/Bots/tallrobot/mekajani.rsi/meta.json
Labels: DO NOT MERGE, Changes: Sprites, Changes: Localization, No C#

#276 Переводы.
  Resources/Locale/ru-RU/ADT/prototypes/entities/mobs/npcs/regalrat.ftl
  Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/ipc.yml
  Resources/ServerInfo/Guidebook/Antagonist/MinorAntagonists.xml
  Resources/ServerInfo/Guidebook/Antagonist/Nuclear Operatives.xml
  Resources/ServerInfo/Guidebook/Antagonist/Revolutionaries.xml
  Resources/ServerInfo/Guidebook/Glossary.xml
  Resources/ServerInfo/Guidebook/Jobs.xml
  Resources/ServerInfo/Guidebook/SpaceStation14.xml
  Resources/ServerInfo/Guidebook/Survival.xml
Labels: DO NOT MERGE, Changes: Localization, No C#

#284 Рельсы нюке
  Resources/Locale/ru-RU/ADT/starwarssynd.ftl
  Resources/Prototypes/ADT/Catalog/nukiestarwars.yml
  Resources/Prototypes/Store/categories.yml
  Resources/Prototypes/Store/presets.yml
Labels: Changes: Localization, No C#

#285 Update starwarssynd.ftl
  Resources/Locale/ru-RU/ADT/starwarssynd.ftl
Labels: Changes: Localization, No C#

#286 Метание ножей теперь не безопасно
  Resources/Prototypes/Entities/Objects/Weapons/Melee/knife.yml
Labels: No C#

#282 Рыба теперь есть в игре
  Resources/Locale/ru-RU/ADT/Fills/cargo.ftl
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Food/fish.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Cargo/cargo_food.yml
  Resources/Prototypes/ADT/Catalog/Fills/Crates/food.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/meat.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/sashimisafe.yml
  Resources/Prototypes/ADT/Recipes/Construction/Graph/fish.yml
  Resources/Prototypes/ADT/Recipes/Cooking/fishrecipes.yml
  Resources/Prototypes/ADT/tags.yml
  Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/chefvend.yml
  Resources/Textures/ADT/Objects/Consumable/Food/fish.rsi/fish.png
  Resources/Textures/ADT/Objects/Consumable/Food/fish.rsi/fishcooked.png
  Resources/Textures/ADT/Objects/Consumable/Food/fish.rsi/fishcutlet.png
  Resources/Textures/ADT/Objects/Consumable/Food/fish.rsi/fishcutletcooked.png
  Resources/Textures/ADT/Objects/Consumable/Food/fish.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#287 Взрывающиеся коробки для пиццы
  Resources/Locale/ru-RU/ADT/Catalog/store/uplink.ftl
  Resources/Locale/ru-RU/ADT/Objects/specific/explosivepizzabox.ftl
  Resources/Prototypes/ADT/Catalog/uplink.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Throwable/grenades.yml
  Resources/Textures/ADT/Objects/Weapons/Grenades/explosivepizzabox.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Grenades/explosivepizzabox.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#288 New sounds for cyborg
  Resources/Audio/ADT/Footsteps/boots1.ogg
  Resources/Audio/ADT/Footsteps/boots2.ogg
  Resources/Audio/ADT/Footsteps/boots3.ogg
  Resources/Audio/ADT/Footsteps/borg_deathsound.ogg
  Resources/Audio/ADT/Footsteps/combine/die1.ogg
  Resources/Audio/ADT/Footsteps/combine/die2.ogg
  Resources/Audio/ADT/Footsteps/combine/die3.ogg
  Resources/Audio/ADT/Footsteps/combine/die4.ogg
  Resources/Audio/ADT/Footsteps/gear1.ogg
  Resources/Audio/ADT/Footsteps/gear2.ogg
  Resources/Audio/ADT/Footsteps/gear3.ogg
  Resources/Audio/ADT/Footsteps/gear4.ogg
  Resources/Audio/ADT/Footsteps/gear5.ogg
  Resources/Audio/ADT/Footsteps/gear6.ogg
  Resources/Audio/ADT/Footsteps/off.ogg
  Resources/Audio/ADT/Footsteps/off1.ogg
  Resources/Audio/ADT/Footsteps/off2.ogg
  Resources/Audio/ADT/Footsteps/off3.ogg
  Resources/Audio/ADT/Footsteps/say/off1.ogg
  Resources/Audio/ADT/Footsteps/say/off2.ogg
  Resources/Audio/ADT/Footsteps/say/off3.ogg
  Resources/Audio/ADT/Footsteps/say/off4.ogg
  Resources/Locale/ru-RU/ADT/Objects/Mobs/cyborg_sec.ftl
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/equipment.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/sec_cyborg.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/sounds.yml
Labels: Changes: Localization, No C#

#290 фикс материал арбитража
  Resources/Locale/ru-RU/guidebook/chemistry/core.ftl
  Resources/Prototypes/ADT/Demon/Mobs/Species/demon.yml
  Resources/Prototypes/Entities/Structures/Storage/Closets/base_structureclosets.yml
Labels: Changes: Localization, No C#

#294 Фиксы КПБ
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/base.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/silicon_base.yml
  Resources/Prototypes/SimpleStation14/InventoryTemplates/ipc_inventory_template.yml
Labels: No C#

#302 Еще фиксы
  Resources/Maps/Salvage/ADT/medical_3.yml
  Resources/Maps/bagel.yml
  Resources/Maps/core.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Labels: No C#, Changes: Map

#303 Фикс ошибки
  Resources/Prototypes/ADT/Tajaran/Species/Tajaran.yml
Labels: No C#

#304 Cyb update 2
  Resources/Locale/ru-RU/ADT/Objects/Mobs/cyborg_sec.ftl
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/base.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/cyb_pda.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/damage_mod_set.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/equipment.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/identification_cards.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/inventory.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/job.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/laws.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/name_dataset.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/projectiles.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/sec_cyborg.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/species.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Rifels/fmfal.yml
  Resources/Prototypes/Entities/Mobs/Player/human.yml
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Textures/ADT/Mobs/Silicon/Cyborg/advanced.rsi/equipped-FEET.png
  Resources/Textures/ADT/Mobs/Silicon/Cyborg/advanced.rsi/icon-on.png
  Resources/Textures/ADT/Mobs/Silicon/Cyborg/advanced.rsi/icon.png
  Resources/Textures/ADT/Mobs/Silicon/Cyborg/advanced.rsi/inhand-left.png
  Resources/Textures/ADT/Mobs/Silicon/Cyborg/advanced.rsi/inhand-right.png
  Resources/Textures/ADT/Mobs/Silicon/Cyborg/advanced.rsi/meta.json
  Resources/Textures/ADT/Mobs/Silicon/Cyborg/advanced.rsi/on-equipped-FEET.png
  Resources/Textures/ADT/Mobs/Silicon/Cyborg/advanced.rsi/on-inhand-left.png
  Resources/Textures/ADT/Mobs/Silicon/Cyborg/advanced.rsi/on-inhand-right.png
  Resources/Textures/Objects/Misc/bureaucracy.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#305 Добавлены 5 новый целей станции
  Resources/Locale/ru-RU/corvax/station-goal/station-goal-component.ftl
  Resources/Prototypes/Corvax/Objectives/goals.yml
Labels: Changes: Localization, No C#

#306 Бафф синдиборга и обычных киборгов
  Resources/Prototypes/ADT/Damage/ADTmodifiers.yml
  Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
Labels: No C#

#310 Очень мелкий фикс
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/damage_mod_set.yml
Labels: No C#

#278 Новые наборы Синди
  Resources/Locale/ru-RU/ADT/syndicate.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Syndicate.yml
  Resources/Prototypes/ADT/Catalog/uplink.yml
  Resources/Prototypes/ADT/Entities/Structures/syndie.yml
Labels: Changes: Localization, No C#

#314 Add Dev maps
  Resources/Maps/Dev/Gooseke/ANKSSSP/1.yml
  Resources/Maps/Dev/Gooseke/DKSSSP/1.yml
  Resources/Maps/Dev/Gooseke/DKSSSP/2.yml
  Resources/Maps/Dev/Gooseke/DKSSSP/3.yml
  Resources/Maps/Dev/Gooseke/DKSSSP/4.yml
  Resources/Maps/Dev/Gooseke/TYKSSSP/1.yml
  Resources/Maps/Dev/Gooseke/TYKSSSP/3.yml
  Resources/Maps/Dev/Gooseke/VOJD/1.yml
  Resources/Maps/Dev/Gooseke/VOJD/2.yml
Labels: No C#

#312 Перевод гайдов и их обновление/корректировка
  Resources/Prototypes/ADT/Felinid/Species/felinid.yml
  Resources/ServerInfo/Guidebook/Antagonist/Antagonists.xml
  Resources/ServerInfo/Guidebook/Antagonist/MinorAntagonists.xml
  Resources/ServerInfo/Guidebook/Antagonist/Traitors.xml
  Resources/ServerInfo/Guidebook/Chemicals.xml
  Resources/ServerInfo/Guidebook/Controls/Controls.xml
  Resources/ServerInfo/Guidebook/Controls/Radio.xml
  Resources/ServerInfo/Guidebook/Glossary.xml
  Resources/ServerInfo/Guidebook/Security/Defusal.xml
  Resources/ServerInfo/Guidebook/Security/Forensics.xml
  Resources/ServerInfo/Guidebook/Security/Security.xml
  Resources/ServerInfo/Guidebook/Service/Bartender.xml
  Resources/ServerInfo/Guidebook/Service/Botany.xml
Labels: No C#

#315 Update felinid.yml
  Resources/Prototypes/ADT/Felinid/Species/felinid.yml
Labels: DO NOT MERGE, No C#

#319 Исправил анимацию для X-02
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Battery/battery_gun.yml
Labels: No C#

#311 добавление именной гитары
  Resources/Locale/ru-RU/ADT/Objects/Fan/rock_gitar.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/rock-guitar.yml
  Resources/Textures/ADT/Objects/Fun/Rock_guitar.rsi/icon.png
  Resources/Textures/ADT/Objects/Fun/Rock_guitar.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Fun/Rock_guitar.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Fun/Rock_guitar.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#320 Личный сет
  Resources/Locale/ru-RU/ADT/Catalog/fills/items/pyotr_briefcase.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Neck/cloak.ftl
  Resources/Locale/ru-RU/ADT/Clothing/Uniform/jumpsuits.ftl
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Guns/Guns.ftl
  Resources/Prototypes/ADT/Entities/Objects/Misc/schrodinger.yml
  Resources/Textures/ADT/Clothing/Neck/mantles/mantle_centcomm.rsi/equipped-NECK.png
  Resources/Textures/ADT/Clothing/Neck/mantles/mantle_centcomm.rsi/icon.png
  Resources/Textures/ADT/Clothing/Neck/mantles/mantle_centcomm.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Guns/Revolvers/decard_gold.rsi/base.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Revolvers/decard_gold.rsi/equipped-BELT.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Revolvers/decard_gold.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Revolvers/decard_gold.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Revolvers/decard_gold.rsi/mag-unshaded-0.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Revolvers/decard_gold.rsi/mag-unshaded-1.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Revolvers/decard_gold.rsi/mag-unshaded-2.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Revolvers/decard_gold.rsi/mag-unshaded-3.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Revolvers/decard_gold.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#321 Небольшой респрайт
  Resources/Locale/ru-RU/ADT/Clothing/OuterClothing/furcoat.ftl
  Resources/Prototypes/ADT/Entities/Objects/Misc/schrodinger.yml
  Resources/Prototypes/ADT/Vulpkanin/Body/Organs/Vulpkanin.yml
  Resources/Textures/ADT/Clothing/Neck/mantles/mantle_centcomm.rsi/equipped-NECK.png
  Resources/Textures/ADT/Clothing/Neck/mantles/mantle_centcomm.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/schrodinger_coat.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/schrodinger_coat.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/schrodinger_coat.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/schrodinger_coat.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Coats/schrodinger_coat.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Guns/Revolvers/decard_gold.rsi/base.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Revolvers/decard_gold.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Revolvers/decard_gold.rsi/inhand-right.png
Labels: Changes: Sprites, Changes: Localization, No C#

#318 Flippo lighter
  Resources/Locale/ru-RU/ADT/Objects/Misc/flippolighter.ftl
  Resources/Prototypes/ADT/Entities/Objects/Tools/FlippoLighter.yml
  Resources/Textures/ADT/Objects/Tools/flippolighter_aidan.rsi/cheap_icon_base.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_aidan.rsi/icon_map.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_aidan.rsi/inhand-left-flame.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_aidan.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_aidan.rsi/inhand-right-flame.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_aidan.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_aidan.rsi/lighter_flame.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_aidan.rsi/meta.json
  Resources/Textures/ADT/Objects/Tools/flippolighter_aidan.rsi/zippo-inhand-left-flame.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_aidan.rsi/zippo-inhand-left.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_aidan.rsi/zippo-inhand-right-flame.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_aidan.rsi/zippo-inhand-right.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_aidan.rsi/zippo_icon_base.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_aidan.rsi/zippo_open.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_aidan.rsi/zippo_top.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_johan.rsi/cheap_icon_base.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_johan.rsi/icon_map.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_johan.rsi/inhand-left-flame.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_johan.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_johan.rsi/inhand-right-flame.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_johan.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_johan.rsi/lighter_flame.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_johan.rsi/meta.json
  Resources/Textures/ADT/Objects/Tools/flippolighter_johan.rsi/zippo-inhand-left-flame.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_johan.rsi/zippo-inhand-left.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_johan.rsi/zippo-inhand-right-flame.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_johan.rsi/zippo-inhand-right.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_johan.rsi/zippo_icon_base.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_johan.rsi/zippo_open.png
  Resources/Textures/ADT/Objects/Tools/flippolighter_johan.rsi/zippo_top.png
Labels: Changes: Sprites, Changes: Localization, No C#

#324 Update
  Content.Server/ADT/ShuttleDroneCentCom/CentComShuttleComponent.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Smokeables/Cigars/case.ftl
  Resources/Maps/Dev/Atorigate1/NT-Shuttel_map.yml
  Resources/Maps/Dev/Schrodinger71/centcomm_adt.yml
  Resources/Maps/centcomm.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/Hardsuits/paramedic.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/schrodinger.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Battery/battery_gun.yml
  Resources/Prototypes/ADT/Entities/Structures/Machines/centcommeConsoleShuttle.yml
  Resources/Prototypes/ADT/Felinid/Mobs/Species/felinid.yml
  Resources/Prototypes/Entities/Objects/Fun/pai.yml
  Resources/Prototypes/Entities/Objects/Weapons/Throwable/bola.yml
  Resources/Prototypes/Entities/Stations/base.yml
  Resources/Prototypes/tags.yml
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/paramedic_hardsuit.rsi/equipped-OUTERCLOTHING-PAI.png
  Resources/Textures/ADT/Clothing/OuterClothing/Hardsuits/paramedic_hardsuit.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/BlueShield.rsi/base.png
  Resources/Textures/ADT/Objects/Weapons/Guns/Battery/BlueShield.rsi/mag-unshaded-0.png
Labels: Changes: Sprites, Changes: Localization, Changes: Map

#325 КПБ народу (спонсорскому)
  Content.Shared/Preferences/HumanoidCharacterProfile.cs
  Resources/Audio/ADT/IPC/attributions.yml
  Resources/Audio/ADT/IPC/borg_deathsound.ogg
  Resources/Audio/ADT/IPC/buzz-sigh.ogg
  Resources/Audio/ADT/IPC/buzz-two.ogg
  Resources/Audio/ADT/IPC/ping.ogg
  Resources/Audio/ADT/IPC/signal.ogg
  Resources/Audio/ADT/IPC/synth_no.ogg
  Resources/Audio/ADT/IPC/synth_scream.ogg
  Resources/Audio/ADT/IPC/synth_yes.ogg
  Resources/Locale/ru-RU/SimpleStation14/prototypes/entities/structures/machines/silicon_chargers.ftl
  Resources/Prototypes/ADT/IPC/sound_collections.yml
  Resources/Prototypes/ADT/IPC/speech_emote_sounds.yml
  Resources/Prototypes/ADT/IPC/speech_emotes.yml
  Resources/Prototypes/ADT/Research/industrialcharger.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Customization/screens.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/ipc.yml
  Resources/Prototypes/SimpleStation14/InventoryTemplates/ipc_inventory_template.yml
  Resources/Prototypes/SimpleStation14/Recipes/Lathes/electronics.yml
  Resources/Prototypes/SimpleStation14/Species/ipc.yml
Labels: Changes: Localization

#328 fix upst
  Resources/Maps/aspid.yml
  Resources/Maps/gemini.yml
  Resources/Maps/reach.yml
  Resources/Prototypes/Corvax/Maps/Pools/default.yml
  Resources/Prototypes/Entities/Clothing/Eyes/hud.yml
Labels: No C#, Changes: Map

#330 Update ipc.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/ipc.yml
Labels: No C#

#331 (Около)Финальные фиксы и переводы КПБ
  Resources/Locale/ru-RU/ipc/markings.ftl
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/ipc.yml
  Resources/Textures/SimpleStation14/Interface/Alerts/charge.rsi/charge-empty.png
  Resources/Textures/SimpleStation14/Interface/Alerts/charge.rsi/charge0.png
  Resources/Textures/SimpleStation14/Interface/Alerts/charge.rsi/charge1.png
  Resources/Textures/SimpleStation14/Interface/Alerts/charge.rsi/charge2.png
  Resources/Textures/SimpleStation14/Interface/Alerts/charge.rsi/charge3.png
  Resources/Textures/SimpleStation14/Interface/Alerts/charge.rsi/charge4.png
  Resources/Textures/SimpleStation14/Interface/Alerts/charge.rsi/meta.json
  Resources/Textures/SimpleStation14/Mobs/Customization/ipc_screens.rsi/ipc_screen_breakout.png
  Resources/Textures/SimpleStation14/Mobs/Customization/ipc_screens.rsi/ipc_screen_eight.png
  Resources/Textures/SimpleStation14/Mobs/Customization/ipc_screens.rsi/ipc_screen_heart.png
Labels: Changes: Sprites, Changes: Localization, No C#

#329 СЩ и давление
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Guns/Battery/battery_gun.yml
  Resources/Prototypes/ADT/Roles/Jobs/OfficerBlueShield/backpack.yml
  Resources/Prototypes/Catalog/Fills/Items/belt.yml
  Resources/Prototypes/Entities/Mobs/Species/base.yml
Labels: No C#

#334 fix yml
  Resources/Audio/Effects/bang.ogg
  Resources/Audio/Effects/woodhit.ogg
  Resources/Audio/Weapons/tap.ogg
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
Labels: No C#

#335 Добавлены новые виды вредной еды
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Drinks/cans.ftl
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Food/snacks.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Drinks/cans.yml
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/snacks.yml
  Resources/Textures/ADT/Objects/Consumable/Drinks/nostop.rsi/icon-open.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/nostop.rsi/icon.png
  Resources/Textures/ADT/Objects/Consumable/Drinks/nostop.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Chips/chips.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Chips/chips.rsi/onion-and-sourcream.png
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Chips/chips.rsi/shrimp.png
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Chips/chips.rsi/space.png
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Chips/chips.rsi/spicy.png
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Chips/trash.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Chips/trash.rsi/onion-and-sourcream-trash.png
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Chips/trash.rsi/shrimp-trash.png
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Chips/trash.rsi/space-trash.png
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Chips/trash.rsi/spicy-trash.png
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Dried/meat.rsi/beef.png
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Dried/meat.rsi/chicken.png
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Dried/meat.rsi/horse.png
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Dried/meat.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Dried/meat.rsi/pig.png
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Dried/trash.rsi/beef-trash.png
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Dried/trash.rsi/chicken-trash.png
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Dried/trash.rsi/horse-trash.png
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Dried/trash.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Food/Snacks/Dried/trash.rsi/pig-trash.png
Labels: Changes: Sprites, Changes: Localization, No C#

#332 Добавлены шоколадные батончики
  Resources/Locale/ru-RU/ADT/Objects/Consumable/Food/chocolate.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/chocolate.yml
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/bars.rsi/bar-choco.png
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/bars.rsi/bar-coconut.png
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/bars.rsi/bar-energy.png
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/bars.rsi/bar-nuts.png
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/bars.rsi/bar-pink.png
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/bars.rsi/bar-two.png
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/bars.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/packing.rsi/choco-packed.png
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/packing.rsi/coconut-packed.png
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/packing.rsi/energy-packed.png
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/packing.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/packing.rsi/nuts-packed.png
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/packing.rsi/pink-packed.png
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/packing.rsi/two-packed.png
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/trash.rsi/choco-trash.png
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/trash.rsi/coconut-trash.png
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/trash.rsi/energy-trash.png
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/trash.rsi/meta.json
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/trash.rsi/nuts-trash.png
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/trash.rsi/pink-trash.png
  Resources/Textures/ADT/Objects/Consumable/Food/Chocolate/trash.rsi/two-trash.png
Labels: Changes: Sprites, Changes: Localization, No C#

#333 add last name novakid
  Resources/Prototypes/ADT/Novakid/Names/last_novakid.yml
Labels: No C#

#340 срочный fix
  Resources/Maps/centcomm.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/schrodinger.yml
  Resources/Prototypes/ADT/Entities/Structures/Machines/centcommeConsoleShuttle.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Customization/screens.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/silicon_base.yml
Labels: No C#, Changes: Map

#343 Fix update
  Resources/Maps/Dev/Schrodinger71/centcomm_adt.yml
  Resources/Maps/centcomm.yml
  Resources/Prototypes/ADT/Entities/Structures/Machines/centcommeConsoleShuttle.yml
Labels: No C#, Changes: Map

#344 Звуки по просьбе
  Resources/Audio/ADT/Fun/Ban_DEF.ogg
  Resources/Audio/ADT/Fun/Ban_MAT.ogg
  Resources/Audio/ADT/Fun/Screamer.ogg
  Resources/Audio/ADT/Fun/nefertiti.ogg
Labels: No C#

#346 new update
  Resources/Audio/ADT/Fun/danci_krono.ogg
  Resources/Maps/centcomm.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/centdrobe.yml
  Resources/Prototypes/Entities/Structures/Machines/fax_machine.yml
  Resources/ServerInfo/ADT/srp/KorporateZakonSerious.xml
  Resources/ServerInfo/ADT/srp/SrpCommandCaptain.xml
  Resources/Textures/ADT/Clothing/Neck/mantles/mantle_centcomm.rsi/equipped-NECK.png
  Resources/Textures/ADT/Clothing/Neck/mantles/mantle_centcomm.rsi/icon.png
  Resources/Textures/Clothing/Head/Hardsuits/deathsquad.rsi/meta.json
Labels: Changes: Sprites, No C#, Changes: Map

#347 Новый данж
  Resources/Maps/Dungeon/bunker.yml
  Resources/Prototypes/Procedural/Themes/bunker.yml
  Resources/Prototypes/Procedural/dungeon_configs.yml
  Resources/Prototypes/Procedural/salvage_mods.yml
Labels: No C#

#348 фикс от визардов
  Resources/clientCommandPerms.yml
Labels: No C#

#353 Починка чистобота
  Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml
Labels: No C#

#352 Разделение инструментов
  Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
Labels: No C#

#351 Revert ,,Limited Chem. dispenser''
  Content.Client/Chemistry/UI/ReagentDispenserBoundUserInterface.cs
  Content.Client/Chemistry/UI/ReagentDispenserWindow.xaml
  Content.Client/Chemistry/UI/ReagentDispenserWindow.xaml.cs
  Content.IntegrationTests/Tests/Chemistry/DispenserTest.cs
  Content.Server/Chemistry/Components/ReagentDispenserComponent.cs
  Content.Server/Chemistry/EntitySystems/ReagentDispenserSystem.cs
  Content.Shared/Chemistry/Dispenser/ReagentDispenserInventoryPrototype.cs
  Content.Shared/Chemistry/SharedReagentDispenser.cs
  Content.Shared/Containers/ItemSlot/ItemSlotsComponent.cs
  Resources/Prototypes/Catalog/ReagentDispensers/beverage.yml
  Resources/Prototypes/Catalog/ReagentDispensers/chemical.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
  Resources/Prototypes/Entities/Objects/Devices/Circuitboards/Machine/production.yml
  Resources/Prototypes/Entities/Objects/Specific/chemical-containers.yml
  Resources/Prototypes/Entities/Structures/Dispensers/base_structuredispensers.yml
  Resources/Prototypes/Entities/Structures/Dispensers/booze.yml
  Resources/Prototypes/Entities/Structures/Dispensers/chem.yml
  Resources/Prototypes/Entities/Structures/Dispensers/soda.yml
  Resources/Prototypes/tags.yml
Labels: Changes: UI

#355 локализация исследования технологий
  Resources/Locale/ru-RU/research/components/research-console-component.ftl
  Resources/Locale/ru-RU/research/technologies.ftl
Labels: Changes: Localization, No C#

#356 Add new button in adminpanel
  Content.Client/Administration/UI/Tabs/RoundTab.xaml
  Resources/Prototypes/ADT/Entities/Objects/Misc/schrodinger.yml
Labels: DO NOT MERGE, No C#, Changes: UI

#358 Добавлены новые сдерживающие поля
  Resources/Locale/ru-RU/ADT/Catalog/store/uplink.ftl
  Resources/Locale/ru-RU/ADT/Objects/Device/holoprojectors.ftl
  Resources/Prototypes/ADT/Catalog/uplink.yml
  Resources/Prototypes/ADT/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/ADT/Entities/Objects/Device/holoprojectors.yml
  Resources/Prototypes/ADT/Entities/Structures/Holographic/projections.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
  Resources/Textures/ADT/Objects/Device/Holoprojector/field.rsi/icon.png
  Resources/Textures/ADT/Objects/Device/Holoprojector/field.rsi/meta.json
  Resources/Textures/ADT/Structures/Holo/field.rsi/icon.png
  Resources/Textures/ADT/Structures/Holo/field.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#359 нормальные спрайты шлюзов цк, удивительно.
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/airlocks.yml
Labels: No C#

#357 Translate Changeling
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Actions/action_changeling.ftl
  Resources/Locale/ru-RU/administration/antag.ftl
  Resources/Locale/ru-RU/alerts/alerts.ftl
  Resources/Locale/ru-RU/game-ticking/preset-changeling.ftl
  Resources/Locale/ru-RU/interaction/interaction-popup-component.ftl
  Resources/Locale/ru-RU/objectives/conditions/changeling.ftl
  Resources/Locale/ru-RU/prototypes/roles/antags.ftl
  Resources/Locale/ru-RU/store/currency.ftl
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/identification_cards.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/weapon_polymorphUSSP.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/EvidenceBag.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/pyotr_sabre.yml
  Resources/Prototypes/ADT/Felinid/Mobs/Player/felinid.yml
  Resources/Prototypes/ADT/Tajaran/Entities/Mobs/Player/Tajaran.yml
  Resources/Prototypes/ADT/Tajaran/Voice/sound_collections.yml
  Resources/Prototypes/ADT/Tajaran/Voice/speech_emote_sounds.yml
  Resources/Prototypes/ADT/Tajaran/Voice/speech_emotes.yml
  Resources/Prototypes/ADT/changeling/changeling.yml
  Resources/Prototypes/ADT/changeling/ling_catalog.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/armblade.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/ipc.yml
  Resources/ServerInfo/Guidebook/Antagonist/Traitors.xml
Labels: Changes: Localization, No C#

#361 Ретекстур плюшки Умы.
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_uma.png
Labels: Changes: Sprites, No C#

#364 Камни.
  Resources/Locale/ru-RU/ADT/cargo/other.ftl
  Resources/Prototypes/Entities/Structures/Walls/asteroid.yml
Labels: Changes: Localization, No C#
