Repository xtray85/space_station, pull requests merged in 2024-06, with the labels that each got.

#741 Issue
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/Entities/Objects/Fun/toys.yml
  Resources/Textures/ADT/Objects/Fun/toys.rsi/holoplush.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/magicplush.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/ntb-inhand-left.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/ntb-inhand-right.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/ntb.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plusie_mio.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/rainbowcarpplush.png
  Resources/Textures/Objects/Fun/toys.rsi/meta.json
Labels: Changes: Sprites, No C#

#739 Новая заставка png во время загрузки клиента
  Resources/Textures/Logo/new_logo.png
  Resources/manifest.yml
Labels: No C#

#733 Chief engineer's gas mask
  Resources/Locale/ru-RU/ADT/Clothing/Mask/mask.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Masks/mask.yml
  Resources/Prototypes/ADT/Objectives/stealTargetGroups.yml
  Resources/Prototypes/ADT/Objectives/thief.yml
  Resources/Prototypes/ADT/Recipes/Construction/Graph/clothing/Clothing.yml
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Objectives/objectiveGroups.yml
  Resources/Textures/ADT/Clothing/Mask/gasCE.rsi/equipped-MASK.png
  Resources/Textures/ADT/Clothing/Mask/gasCE.rsi/icon.png
  Resources/Textures/ADT/Clothing/Mask/gasCE.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Mask/gasCE.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Mask/gasCE.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#742 конечное дополнение к концу конца сервисного апдейта™
  Resources/Locale/ru-RU/ADT/ghost/roles/ghost-role.ftl
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/Baked/cake.yml
  Resources/Textures/ADT/Objects/Consumable/Food/muffins.rsi/justkekc.png
  Resources/Textures/ADT/Objects/Consumable/Food/muffins.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#744 Возвращаем крафт мех фабрикатора
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Labels: No C#

#745 Revert "Возвращаем крафт мех фабрикатора"
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Labels: No C#

#737 Локализация аплинка и мелочей
  Resources/Locale/ru-RU/animals/rat-king/rat-king.ftl
  Resources/Locale/ru-RU/damage/damage-force-say.ftl
  Resources/Locale/ru-RU/paper/stamp-component.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/backpacks/duffelbag.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/hands/colored.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/snap_pops.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/toys.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/materials/shards.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/materials/sheets/glass.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/paper.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/tools/decoys.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/throwable/grenades.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/doors/airlocks/access.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/doors/airlocks/airlocks.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/doors/airlocks/assembly.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/doors/airlocks/clockwork.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/doors/windoors/assembly.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/doors/windoors/clockwork.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/doors/windoors/windoor.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/computers/computers.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/screen.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/walls/girders.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/walls/grille.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/windows/clockwork.ftl
  Resources/Locale/ru-RU/store/categories.ftl
  Resources/Locale/ru-RU/store/uplink-catalog.ftl
Labels: Changes: Localization, No C#, Status: Needs Review

#748 New plushie
  Resources/Locale/ru-RU/ADT/Fun/ADTtoys.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Textures/ADT/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/ADT/Objects/Fun/toys.rsi/plushie_pochita.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/pochita-inhand-left.png
  Resources/Textures/ADT/Objects/Fun/toys.rsi/pochita-inhand-right.png
  global.json
Labels: Changes: Sprites, Changes: Localization, No C#

#747 addded Mindshield for centcom and ert
  Resources/Prototypes/ADT/Entities/Mobs/player/humanoid.yml
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Roles/Jobs/Command/centcom_official.yml
  Resources/Prototypes/Roles/Jobs/Fun/emergencyresponseteam.yml
Labels: No C#

#753 Book
  Resources/Locale/en-US/ss14-ru/prototypes/entities/objects/misc/authorbooks.ftl
  Resources/Locale/ru-RU/paper/book-authorbooks.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/authorbooks.ftl
  Resources/Prototypes/ADT/Entities/Objects/Misc/books.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/secretbook.yml
Labels: Changes: Localization, No C#

#752 fixed goal paper
  Content.Server/Corvax/StationGoal/StationGoalPaperSystem.cs
  Resources/Locale/ru-RU/corvax/station-goal/station-goal-component.ftl
  Resources/Prototypes/Corvax/Entities/Objects/Misc/paper.yml
Labels: Changes: Localization

#756 Fix carpets
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/carpets.ftl
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Recipes/Lathes/clothing.yml
Labels: Changes: Localization, No C#

#762 fixed eating beret CE
  Resources/Prototypes/ADT/Entities/Clothing/Head/hats.yml
Labels: No C#

#766 fixed the error with opened clockworck airlock
  Resources/Textures/Structures/Doors/Airlocks/Glass/clockwork_pinion.rsi/assembly.png
  Resources/Textures/Structures/Doors/Airlocks/Glass/clockwork_pinion.rsi/bolted_open_unlit.png
  Resources/Textures/Structures/Doors/Airlocks/Glass/clockwork_pinion.rsi/closed.png
  Resources/Textures/Structures/Doors/Airlocks/Glass/clockwork_pinion.rsi/closing.png
  Resources/Textures/Structures/Doors/Airlocks/Glass/clockwork_pinion.rsi/emergency_open_unlit.png
  Resources/Textures/Structures/Doors/Airlocks/Glass/clockwork_pinion.rsi/meta.json
  Resources/Textures/Structures/Doors/Airlocks/Glass/clockwork_pinion.rsi/open_unlit.png
  Resources/Textures/Structures/Doors/Airlocks/Glass/clockwork_pinion.rsi/opening.png
  Resources/Textures/Structures/Doors/Airlocks/Glass/clockwork_pinion.rsi/panel_closed.png
Labels: Changes: Sprites, No C#, Status: Needs Review

#765 added new posters
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
  Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/posters.yml
  Resources/Textures/ADT/Objects/Decoration/poster_syndicate.rsi/error.png
  Resources/Textures/ADT/Objects/Decoration/poster_syndicate.rsi/gasattack.png
  Resources/Textures/ADT/Objects/Decoration/poster_syndicate.rsi/meta.json
  Resources/Textures/ADT/Objects/Decoration/poster_syndicate.rsi/nobad.png
  Resources/Textures/ADT/Objects/Decoration/poster_syndicate.rsi/nogood.png
Labels: Changes: Sprites, Changes: Localization, No C#, Status: Needs Review

#760 Добавление гемофилии
  Content.Server/ADT/Hemophilia/HemophiliaSystem.cs
  Content.Server/Body/Components/BloodstreamComponent.cs
  Content.Shared/ADT/hemophilia/HemophiliaComponent.cs
  Resources/Locale/en-US/ADT/traits/traits.ftl
  Resources/Locale/ru-RU/ADT/traits/disabilities.ftl
  Resources/Prototypes/ADT/Traits/neutral.yml
Labels: Changes: Localization

#771 Перевод
  Resources/Locale/ru-RU/ADT/Clothing/boots.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/objects/specific/ADTcargo_pallet.ftl
Labels: Changes: Localization, No C#
