Repository xtray85/space_station, pull requests merged in 2024-04, with the labels that each got.

#542 Фиксы просьб баг-репорта
  Resources/Prototypes/ADT/changeling/mobs.yml
  Resources/Prototypes/Entities/Objects/Misc/candy_bowl.yml
  Resources/ServerInfo/ADT/NewRecipes.xml
  Resources/ServerInfo/ADT/Pathologist.xml
Labels: No C#, Status: Needs Review

#547 Добавление набора одежды "Возмездия"
  Resources/Locale/ru-RU/ADT/Clothing/kivchikset.ftl
  Resources/Prototypes/ADT/Entities/Clothing/KivchikSet/kivchikset.yml
  Resources/Textures/ADT/Clothing/Back/kivchikset_satchel.rsi/equipped-BACKPACK.png
  Resources/Textures/ADT/Clothing/Back/kivchikset_satchel.rsi/icon.png
  Resources/Textures/ADT/Clothing/Back/kivchikset_satchel.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Back/kivchikset_satchel.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Back/kivchikset_satchel.rsi/meta.json
  Resources/Textures/ADT/Clothing/Hands/Gloves/kivchikset_gloves.rsi/equipped-HAND.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/kivchikset_gloves.rsi/icon.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/kivchikset_gloves.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/kivchikset_gloves.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/kivchikset_gloves.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hats/kivchikset_beret.rsi/equipped-HELMET-hamster.png
  Resources/Textures/ADT/Clothing/Head/Hats/kivchikset_beret.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/kivchikset_beret.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/kivchikset_beret.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Head/Hats/kivchikset_beret.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Head/Hats/kivchikset_beret.rsi/meta.json
  Resources/Textures/ADT/Clothing/Neck/Cloaks/kivchikset_cloak.rsi/equipped-NECK.png
  Resources/Textures/ADT/Clothing/Neck/Cloaks/kivchikset_cloak.rsi/icon.png
  Resources/Textures/ADT/Clothing/Neck/Cloaks/kivchikset_cloak.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Neck/Cloaks/kivchikset_cloak.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Neck/Cloaks/kivchikset_cloak.rsi/meta.json
  Resources/Textures/ADT/Clothing/Shoes/Boots/kivchikset_boots.rsi/equipped-FEET.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/kivchikset_boots.rsi/icon.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/kivchikset_boots.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/kivchikset_boots.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Shoes/Boots/kivchikset_boots.rsi/meta.json
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/kivchikset_skirt.rsi/equipped-INNERCLOTHING-monkey.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/kivchikset_skirt.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/kivchikset_skirt.rsi/icon.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/kivchikset_skirt.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/kivchikset_skirt.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Uniforms/Jumpskirt/kivchikset_skirt.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#551 (BugFix) Исправление появления при сборке/спавне дрона, левой руки киборга
  Resources/Prototypes/Body/Prototypes/drone.yml
Labels: No C#

#553 Наручники смотрителя, небольшой баг фикс
  Resources/Locale/ru-RU/ADT/Objects/Misc/misc.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/handcuffs.ftl
  Resources/Prototypes/ADT/Entities/Objects/Misc/warden_handcuffs.yml
  Resources/Prototypes/Catalog/Fills/Lockers/security.yml
  Resources/Prototypes/Entities/Clothing/Masks/specific.yml
  Resources/Prototypes/Entities/Objects/Consumable/Food/snacks.yml
  Resources/Textures/ADT/Objects/Misc/warden_handcuffs.rsi/body-overlay-2.png
  Resources/Textures/ADT/Objects/Misc/warden_handcuffs.rsi/body-overlay-4.png
  Resources/Textures/ADT/Objects/Misc/warden_handcuffs.rsi/equipped-BELT.png
  Resources/Textures/ADT/Objects/Misc/warden_handcuffs.rsi/handcuff.png
  Resources/Textures/ADT/Objects/Misc/warden_handcuffs.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Misc/warden_handcuffs.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Misc/warden_handcuffs.rsi/meta.json
  Resources/Textures/Mobs/Customization/Tajaran/tajaran_head.rsi/muzzle.png
  Resources/Textures/Mobs/Customization/Tajaran/tajaran_head.rsi/muzzleinears.png
Labels: Changes: Sprites, Changes: Localization, No C#

#550 (заказ) Ксено британцы
  Resources/Locale/ru-RU/ADT/Objects/Mobs/xenos.ftl
  Resources/Prototypes/ADT/Entities/Mobs/xeno.yml
  Resources/Textures/ADT/Mobs/Aliens/ADTbritish.rsi/crit.png
  Resources/Textures/ADT/Mobs/Aliens/ADTbritish.rsi/dead.png
  Resources/Textures/ADT/Mobs/Aliens/ADTbritish.rsi/meta.json
  Resources/Textures/ADT/Mobs/Aliens/ADTbritish.rsi/running.png
  Resources/Textures/ADT/Mobs/Aliens/ADTbritish.rsi/sleeping.png
  Resources/Textures/ADT/Mobs/Aliens/ADTburrower.rsi/crit.png
  Resources/Textures/ADT/Mobs/Aliens/ADTburrower.rsi/dead.png
  Resources/Textures/ADT/Mobs/Aliens/ADTburrower.rsi/meta.json
  Resources/Textures/ADT/Mobs/Aliens/ADTburrower.rsi/running.png
  Resources/Textures/ADT/Mobs/Aliens/ADTdrone.rsi/crit.png
  Resources/Textures/ADT/Mobs/Aliens/ADTdrone.rsi/dead.png
  Resources/Textures/ADT/Mobs/Aliens/ADTdrone.rsi/meta.json
  Resources/Textures/ADT/Mobs/Aliens/ADTdrone.rsi/running.png
  Resources/Textures/ADT/Mobs/Aliens/ADTqueen.rsi/crit.png
  Resources/Textures/ADT/Mobs/Aliens/ADTqueen.rsi/dead.png
  Resources/Textures/ADT/Mobs/Aliens/ADTqueen.rsi/meta.json
  Resources/Textures/ADT/Mobs/Aliens/ADTqueen.rsi/running.png
  Resources/Textures/ADT/Mobs/Aliens/ADTrevager.rsi/crit.png
  Resources/Textures/ADT/Mobs/Aliens/ADTrevager.rsi/dead.png
  Resources/Textures/ADT/Mobs/Aliens/ADTrevager.rsi/meta.json
  Resources/Textures/ADT/Mobs/Aliens/ADTrevager.rsi/running.png
  Resources/Textures/ADT/Mobs/Aliens/ADTrouny.rsi/crit.png
  Resources/Textures/ADT/Mobs/Aliens/ADTrouny.rsi/dead.png
  Resources/Textures/ADT/Mobs/Aliens/ADTrouny.rsi/meta.json
  Resources/Textures/ADT/Mobs/Aliens/ADTrouny.rsi/running.png
  Resources/Textures/ADT/Mobs/Aliens/ADTrunner.rsi/crit.png
  Resources/Textures/ADT/Mobs/Aliens/ADTrunner.rsi/dead.png
  Resources/Textures/ADT/Mobs/Aliens/ADTrunner.rsi/meta.json
  Resources/Textures/ADT/Mobs/Aliens/ADTrunner.rsi/running.png
  Resources/Textures/ADT/Mobs/Aliens/ADTspitter.rsi/crit.png
  Resources/Textures/ADT/Mobs/Aliens/ADTspitter.rsi/dead.png
  Resources/Textures/ADT/Mobs/Aliens/ADTspitter.rsi/meta.json
  Resources/Textures/ADT/Mobs/Aliens/ADTspitter.rsi/running.png
Labels: Changes: Sprites, Changes: Localization, No C#

#560 (заказ) Невидимая стена
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/walls/walls.ftl
  Resources/Prototypes/ADT/Entities/Structures/ADTWallInvisible.yml
  Resources/Textures/ADT/Structures/ADTinvisible.rsi/icon.png
  Resources/Textures/ADT/Structures/ADTinvisible.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#562 Апдейт вульпикса
  Resources/Prototypes/ADT/Entities/Objects/Consumable/Food/vulpix.yml
  Resources/Prototypes/ADT/Recipes/Cooking/vulpix_recipe.yml
  Resources/ServerInfo/ADT/NewRecipes.xml
Labels: No C#

#561 ДНК замок для ядерщиков
  Content.Server/ADT/DNALocker/DNALockComponent.cs
  Content.Server/ADT/DNALocker/DNALockerSystem.cs
  Resources/Audio/ADT/dna-lock.ogg
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/syndicate.ftl
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
Labels: Changes: Localization

#523 [Можно мёрджить] Дроны-антагонисты
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_Body.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_Core.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_IPC.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_InventoryTemplate.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_Spawner.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_StartingGear.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_Turret.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/OLD_DroneAntag.yml
  Resources/Prototypes/ADT/KD/Channels/Channels/DroneAntagChannel.yml
  Resources/Prototypes/ADT/KD/Channels/keys/DroneAntagKey.yml
  Resources/Prototypes/name_identifier_groups.yml
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-charger.rsi/chargedrone.png
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-charger.rsi/chargeshell.png
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-charger.rsi/l_hand.png
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-charger.rsi/meta.json
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-charger.rsi/r_hand.png
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-core-advanced.rsi/drone-core-advanced.png
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-core-advanced.rsi/meta.json
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-core-basic.rsi/drone-core-basic.png
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-core-basic.rsi/meta.json
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-core-command.rsi/drone-core-command.png
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-core-command.rsi/meta.json
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-core-elite.rsi/drone-core-elite.png
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-core-elite.rsi/meta.json
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-engineer.rsi/engdrone.png
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-engineer.rsi/engshell.png
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-engineer.rsi/l_hand.png
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-engineer.rsi/meta.json
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-engineer.rsi/r_hand.png
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-ipc-soldier.rsi/ipc_full.png
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-ipc-soldier.rsi/ipc_icon.png
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-ipc-soldier.rsi/meta.json
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-miner.rsi/l_hand.png
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-miner.rsi/meta.json
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-miner.rsi/minedrone.png
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-miner.rsi/mineshell.png
  Resources/Textures/ADT/Mobs/Silicon/AntagDrones/drone-miner.rsi/r_hand.png
Labels: Changes: Sprites, No C#

#559 New component [LevitationAct] Пишем акшен для Джунгарика.(Готово)
  Content.Server/ADT/ComponentalActions/EntitySystems/ComponentalActions.Abilities.cs
  Content.Server/ADT/ComponentalActions/EntitySystems/ComponentalActions.cs
  Content.Shared/ADT/ComponentalActions/Components/LevitationActComponent.cs
  Content.Shared/ADT/ComponentalActions/SharedComponentalActions.cs
  Content.Shared/Alert/AlertType.cs
  Resources/Locale/ru-RU/ADT/Actions/action.ftl
  Resources/Locale/ru-RU/ADT/alerts.ftl
  Resources/Prototypes/ADT/Actions/componental_actions.yml
  Resources/Prototypes/ADT/Alerts/alerts.yml
  Resources/Textures/ADT/Interface/alerts.rsi/levitation.png
  Resources/Textures/ADT/Interface/alerts.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, Status: Needs Review

#564 Помощь Эшли
  Resources/Locale/ru-RU/ss14-ru/prototypes/adt/entities/objects/fun/toys.ftl
  Resources/Prototypes/ADT/Entities/Objects/Fun/toys.yml
  Resources/Textures/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/Objects/Fun/toys.rsi/plusie_mio.png
Labels: Changes: Sprites, Changes: Localization, No C#, Status: Needs Review

#563 Нерф торгоматов / Переводы
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/hats.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/soft.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/shoes/boots.ftl
  Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/coffee.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/theater.yml
Labels: Changes: Localization, No C#

#566 Небольшие фиксы дронов-антагов Джунгарика
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_IPC.yml
  Resources/Prototypes/ADT/KD/Channels/Channels/DroneAntagChannel.yml
Labels: No C#

#570 New component [ActiveGateway], активированный врата.
  Content.Server/ADT/ActiveGateway/ActiveGatewayComponent.cs
  Content.Server/ADT/ActiveGateway/ActiveGatewaySystem.cs
  Resources/Locale/ru-RU/ADT/prototypes/entities/structures/gateway.ftl
  Resources/Prototypes/ADT/Entities/Structures/Machines/gateway.yml
Labels: Changes: Localization

#571 Knife overhaul
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/AstraKnife.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/BoneKnife.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/knife.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml
Labels: No C#

#572 [Предложка] Встроенный фонарик для КПБ + время для психолога (180 минут)
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/Roles/Jobs/Wildcards/psychologist.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/ipc.yml
Labels: No C#

#568 Фикс и добавления дронам-антагам
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_IPC.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_InventoryTemplate.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_Spawner.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_StartingGear.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_Turret.yml
Labels: No C#

#574 Фиксы апстрима
  Resources/Prototypes/ADT/Entities/Clothing/Back/backpacks.yml
  Resources/Prototypes/ADT/Entities/Clothing/Back/duffels.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Reagents/Consumable/Drink/alcohol.yml
  Resources/Prototypes/Reagents/Consumable/Drink/drinks.yml
  Resources/Prototypes/Research/biochemical.yml
  Resources/Prototypes/Research/civilianservices.yml
  Resources/Prototypes/tags.yml
Labels: No C#

#577 Фиксики апстрима2
  Resources/Prototypes/ADT/Catalog/uplink.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_IPC.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_InventoryTemplate.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_Spawner.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_StartingGear.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_Turret.yml
  Resources/Prototypes/ADT/Entities/Clothing/FriskisSet/raven.yml
  Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/halloween.yml
  Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/hats.yml
  Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/orientalears.yml
  Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/wedding_hats.yml
  Resources/Prototypes/ADT/Entities/Clothing/Uniforms/USSP.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/Cards/card_base.yml
  Resources/Prototypes/ADT/Entities/Objects/Fun/Cards/poker_chips.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/printerdocument.yml
  Resources/Prototypes/ADT/Entities/Objects/Tools/Tools.yml
  Resources/Prototypes/ADT/Entities/Structures/Machines/vending_machines.yml
  Resources/Prototypes/ADT/Entities/Structures/Wallmount/Signs/posters.yml
  Resources/Prototypes/ADT/Tardis/tardis.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Mobs/Player/silicon.yml
  Resources/Prototypes/Entities/Mobs/Species/vox.yml
  Resources/Prototypes/Entities/Structures/Furniture/dresser.yml
  Resources/Prototypes/Entities/Structures/Power/Generation/Singularity/emitter.yml
  Resources/Prototypes/Entities/Structures/Wallmounts/Signs/posters.yml
  Resources/Prototypes/Entities/World/Debris/asteroids.yml
  Resources/Prototypes/NES/Entities/Structures/Shuttles/railguns.yml
  Resources/Prototypes/Procedural/biome_ore_templates.yml
  Resources/Prototypes/Procedural/dungeon_configs.yml
  Resources/Prototypes/Procedural/salvage_mods.yml
  Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
  Resources/Prototypes/StatusEffects/job.yml
  Resources/Prototypes/StatusIcon/antag.yml
  Resources/Prototypes/typing_indicator.yml
  Resources/Textures/ADT/Structures/Wallmounts/posters.rsi/meta.json
  Resources/Textures/ADT/Structures/Wallmounts/posters.rsi/poster_adtfearthem_contraband.png
  Resources/Textures/ADT/Structures/Wallmounts/posters.rsi/poster_adtgreatfood_legit.png
  Resources/Textures/ADT/Structures/Wallmounts/posters.rsi/poster_adtlustardeco_contraband.png
  Resources/Textures/ADT/Structures/Wallmounts/posters.rsi/poster_adtlusttayaran_contraband.png
  Resources/Textures/ADT/Structures/Wallmounts/posters.rsi/poster_adtlustuma_contraband.png
  Resources/Textures/ADT/Structures/Wallmounts/posters.rsi/poster_adtoktoberfest2_legit.png
  Resources/Textures/ADT/Structures/Wallmounts/posters.rsi/poster_adtoktoberfest_legit.png
  Resources/Textures/ADT/Structures/Wallmounts/posters.rsi/poster_adtsilence_contraband.png
  Resources/Textures/ADT/Structures/Wallmounts/posters.rsi/poster_adtturnonsensors_legit.png
  Resources/Textures/ADT/Structures/Wallmounts/posters.rsi/poster_efficiencydiagram_legit.png
  Resources/Textures/ADT/Structures/Wallmounts/posters.rsi/quadro_electronics.png
  Resources/Textures/Effects/speech.rsi/meta.json
  Resources/Textures/LobbyScreens/doomed.png
  Resources/Textures/LobbyScreens/skellyvstherev.png
  Resources/Textures/LobbyScreens/susstation.png
  Resources/Textures/Objects/Fun/toys.rsi/meta.json
Labels: Changes: Sprites, No C#

#583 Продолжаем фиксы апстрима
  Resources/Maps/ADTMaps/adt_packed.yml
  Resources/Maps/HalloweenMaps/halloween_aspid.yml
  Resources/Maps/HalloweenMaps/halloween_bagel.yml
  Resources/Maps/HalloweenMaps/halloween_box.yml
  Resources/Maps/HalloweenMaps/halloween_cluster.yml
  Resources/Maps/HalloweenMaps/halloween_kettle.yml
  Resources/Prototypes/Recipes/Lathes/misc.yml
Labels: No C#

#575 Переводы админ команд.
  Resources/Locale/ru-RU/robust-toolbox/commands.ftl
Labels: Changes: Localization, No C#

#580 Сделал манула с его спавнером
  Resources/Changelog/ChangelogADT.yml
Labels: No C#

#586 Добавление питомца, фикс принтера
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/Mobs/animals.ftl
  Resources/Locale/ru-RU/ADT/paper/doc-printer.ftl
  Resources/Prototypes/ADT/Entities/Mobs/Daniel/daniel.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/printerdocument.yml
  Resources/Textures/ADT/Mobs/Animals/daniel.rsi/daniel.png
  Resources/Textures/ADT/Mobs/Animals/daniel.rsi/daniel_dead.png
  Resources/Textures/ADT/Mobs/Animals/daniel.rsi/daniel_rest.png
  Resources/Textures/ADT/Mobs/Animals/daniel.rsi/daniel_sit.png
  Resources/Textures/ADT/Mobs/Animals/daniel.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#589 Чейнджлог для ножей
  Resources/Changelog/ChangelogADT.yml
Labels: No C#

#587 Дополнение к ПР про манула
  Resources/Locale/ru-RU/ADT/Animals/capibara/manul.ftl
  Resources/Locale/ru-RU/ADT/Spawners.ftl
  Resources/Prototypes/ADT/Entities/Markers/Spawners/manul.yml
  Resources/Prototypes/ADT/Entities/Mobs/manul.yml
  Resources/Textures/ADT/Mobs/Animals/manul.rsi/manul.png
  Resources/Textures/ADT/Mobs/Animals/manul.rsi/manul_dead.png
  Resources/Textures/ADT/Mobs/Animals/manul.rsi/manul_state.png
  Resources/Textures/ADT/Mobs/Animals/manul.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#590 Респрайт крашеров
  Resources/Changelog/ChangelogADT.yml
  Resources/Textures/Objects/Weapons/Melee/crusher.rsi/icon-lit.png
  Resources/Textures/Objects/Weapons/Melee/crusher.rsi/icon-uncharged.png
  Resources/Textures/Objects/Weapons/Melee/crusher.rsi/icon.png
  Resources/Textures/Objects/Weapons/Melee/crusher.rsi/inhand-left.png
  Resources/Textures/Objects/Weapons/Melee/crusher.rsi/inhand-right.png
  Resources/Textures/Objects/Weapons/Melee/crusher.rsi/meta.json
  Resources/Textures/Objects/Weapons/Melee/crusher.rsi/wielded-inhand-left.png
  Resources/Textures/Objects/Weapons/Melee/crusher.rsi/wielded-inhand-right.png
  Resources/Textures/Objects/Weapons/Melee/crusher_dagger.rsi/icon-lit.png
  Resources/Textures/Objects/Weapons/Melee/crusher_dagger.rsi/icon.png
  Resources/Textures/Objects/Weapons/Melee/crusher_dagger.rsi/inhand-left.png
  Resources/Textures/Objects/Weapons/Melee/crusher_dagger.rsi/inhand-right.png
  Resources/Textures/Objects/Weapons/Melee/crusher_dagger.rsi/meta.json
  Resources/Textures/Objects/Weapons/Melee/crusher_glaive.rsi/icon-lit.png
  Resources/Textures/Objects/Weapons/Melee/crusher_glaive.rsi/icon-uncharged.png
  Resources/Textures/Objects/Weapons/Melee/crusher_glaive.rsi/icon.png
  Resources/Textures/Objects/Weapons/Melee/crusher_glaive.rsi/inhand-left.png
  Resources/Textures/Objects/Weapons/Melee/crusher_glaive.rsi/inhand-right.png
  Resources/Textures/Objects/Weapons/Melee/crusher_glaive.rsi/meta.json
  Resources/Textures/Objects/Weapons/Melee/crusher_glaive.rsi/wielded-inhand-left.png
  Resources/Textures/Objects/Weapons/Melee/crusher_glaive.rsi/wielded-inhand-right.png
Labels: DO NOT MERGE, Changes: Sprites, No C#

#585 trader minor update
  Resources/Maps/traderpost.yml
  Resources/Prototypes/ADT/Entities/Mobs/player/trader.yml
  Resources/Prototypes/GameRules/events.yml
Labels: DO NOT MERGE, No C#, Changes: Map

#594 Изменение названий дронов-антагов
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_IPC.yml
  Resources/Prototypes/name_identifier_groups.yml
Labels: No C#

#601 Протокинетические перчачки
  Content.Shared/Weapons/Ranged/Systems/SharedGunSystem.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Clothing/Hands/gloves.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Hands/gloves.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/salvage.yml
  Resources/Prototypes/Procedural/salvage_loot.yml
  Resources/Textures/ADT/Clothing/Hands/Gloves/crusher_gauntlets.rsi/equipped-HAND.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/crusher_gauntlets.rsi/icon-lit.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/crusher_gauntlets.rsi/icon-uncharged.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/crusher_gauntlets.rsi/icon.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/crusher_gauntlets.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/crusher_gauntlets.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Hands/Gloves/crusher_gauntlets.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization

#599 белье СИ
  Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
Labels: No C#

#603 фиксы текстур тайлов шаттлов и бронированной двери
  Resources/Textures/Structures/Doors/Airlocks/highsec/highsec.rsi/closing_unlit.png
  Resources/Textures/Structures/Doors/Airlocks/highsec/highsec.rsi/opening_unlit.png
  Resources/Textures/Tiles/shuttleblack.png
  Resources/Textures/Tiles/shuttleblue.png
  Resources/Textures/Tiles/shuttlegrey.png
  Resources/Textures/Tiles/shuttleorange.png
  Resources/Textures/Tiles/shuttlepurple.png
  Resources/Textures/Tiles/shuttlered.png
Labels: Changes: Sprites, No C#

#604 Нормальный фикс дронов-антагов (от последней обновы мастера)
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_IPC.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_StartingGear.yml
Labels: No C#

#608 Создание крафта пробирки в Медицинском ТехФабе и его добавление туда
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Recipes/Lathes/chemistry.yml
Labels: No C#

#612 Возможная починка света
  Resources/Prototypes/Entities/Structures/Power/smes.yml
Labels: No C#

#615 Фикс цены набора
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/info/playtime-stats.ftl
  Resources/Locale/ru-RU/lobby/lobby-gui.ftl
  Resources/Locale/ru-RU/preferences/ui/character-setup-gui.ftl
  Resources/Locale/ru-RU/station-laws/laws.ftl
  Resources/Maps/centcomm.yml
  Resources/Prototypes/ADT/Drones/Drone-Antags/DroneAntag_IPC.yml
  Resources/Prototypes/ADT/Entities/Mobs/SecurityCyborg/base.yml
  Resources/Prototypes/Catalog/Cargo/cargo_medical.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/satchel.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_flasks.yml
  Resources/Prototypes/Entities/Structures/Machines/vending_machines.yml
  Resources/Prototypes/Objectives/objectiveGroups.yml
  Resources/Prototypes/SimpleStation14/Entities/Mobs/Player/silicon_base.yml
  Resources/Textures/ADT/Structures/Furniture/church_bench.rsi/bench_left.png
  Resources/Textures/ADT/Structures/Furniture/church_bench.rsi/bench_right.png
Labels: Changes: Sprites, Changes: Localization, No C#, Changes: Map

#609 Добавление нового департамента: Синтетики
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/job/department-desc.ftl
  Resources/Locale/ru-RU/ADT/job/department.ftl
  Resources/Prototypes/ADT/Roles/Jobs/Borgs/EngiBorg.yml
  Resources/Prototypes/ADT/Roles/Jobs/Borgs/JanitorBorg.yml
  Resources/Prototypes/ADT/Roles/Jobs/Borgs/MedicalBorg.yml
  Resources/Prototypes/ADT/Roles/Jobs/Borgs/ServiseBrog.yml
  Resources/Prototypes/ADT/Roles/Jobs/Borgs/SupplyBorg.yml
  Resources/Prototypes/ADT/Roles/Jobs/departments.yml
Labels: Changes: Localization, No C#

#616 Реворк и респрайт Вархаммера и небольшой твик Глефы
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Objects/Weapons/Melee/knifess.ftl
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/warhammer.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml
  Resources/Textures/ADT/Objects/Weapons/Melee/warhammer.rsi/icon-lit.png
  Resources/Textures/ADT/Objects/Weapons/Melee/warhammer.rsi/icon-uncharged.png
  Resources/Textures/ADT/Objects/Weapons/Melee/warhammer.rsi/icon.png
  Resources/Textures/ADT/Objects/Weapons/Melee/warhammer.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/warhammer.rsi/inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Melee/warhammer.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Melee/warhammer.rsi/wielded-inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/warhammer.rsi/wielded-inhand-right.png
Labels: Changes: Sprites, Changes: Localization, No C#

#618 Revert "Minimalist Action Bar (#21352)" Пётр, ЭТО ТЕСТИТЬ НА ДЕВЕ ДЛЯ НАЧАЛА
  Content.Client/Input/ContentContexts.cs
  Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs
  Content.Client/UserInterface/Screens/DefaultGameScreen.xaml
  Content.Client/UserInterface/Screens/DefaultGameScreen.xaml.cs
  Content.Client/UserInterface/Screens/SeparatedChatGameScreen.xaml.cs
  Content.Client/UserInterface/Systems/Actions/ActionUIController.cs
  Content.Client/UserInterface/Systems/Actions/Controls/ActionButton.cs
  Content.Client/UserInterface/Systems/Actions/Controls/ActionButtonContainer.cs
  Content.Client/UserInterface/Systems/Actions/Widgets/ActionsBar.xaml
  Content.Client/UserInterface/Systems/Actions/Widgets/ActionsBar.xaml.cs
  Content.Client/UserInterface/Systems/Hotbar/Widgets/HotbarGui.xaml
  Content.Client/UserInterface/Systems/Inventory/Widgets/InventoryGui.xaml
  Content.Shared/Input/ContentKeyFunctions.cs
  Resources/Changelog/ChangelogADT.yml
  Resources/keybinds.yml
Labels: Changes: UI, Status: Needs Review

#622 fix
  Resources/Maps/atlas.yml
Labels: No C#, Changes: Map

#607 перевод GuideBook'a про расы
  Resources/ServerInfo/Guidebook/Mobs/Arachnid.xml
  Resources/ServerInfo/Guidebook/Mobs/Diona.xml
  Resources/ServerInfo/Guidebook/Mobs/Dwarf.xml
  Resources/ServerInfo/Guidebook/Mobs/Human.xml
  Resources/ServerInfo/Guidebook/Mobs/Moth.xml
  Resources/ServerInfo/Guidebook/Mobs/Reptilian.xml
  Resources/ServerInfo/Guidebook/Mobs/SlimePerson.xml
  Resources/ServerInfo/Guidebook/Mobs/Species.xml
Labels: No C#

#625 Изменил размер портсигар
  Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigars/case.yml
Labels: No C#

#627 Добавил текстуру подсветки для закрытого `Airlock`
  Resources/Textures/Structures/Doors/Airlocks/Standard/hatch_maint.rsi/meta.json
  Resources/Textures/Structures/Doors/Airlocks/Standard/hatch_maint.rsi/open_unlit.png
Labels: Changes: Sprites, No C#

#630 cargoConsoleMenu localization. addition to 6e38b992
  Resources/Prototypes/ADT/Catalog/Cargo/cargo_adt.yml
  Resources/Prototypes/ADT/Catalog/Fills/Cargo/cargo_armory.yml
  Resources/Prototypes/ADT/Catalog/Fills/Cargo/cargo_food.yml
  Resources/Prototypes/ADT/Catalog/Fills/Cargo/cargo_fun.yml
  Resources/Prototypes/ADT/Catalog/Fills/Cargo/cargo_service.yml
  Resources/Prototypes/ADT/KD/Cargo/GravityForCargo.yml
  Resources/Prototypes/ADT/KD/Cargo/RingBox.yml
  Resources/Prototypes/Catalog/Cargo/cargo_cargo.yml
  Resources/Prototypes/Catalog/Cargo/cargo_engineering.yml
  Resources/Prototypes/Catalog/Cargo/cargo_food.yml
  Resources/Prototypes/Catalog/Cargo/cargo_livestock.yml
  Resources/Prototypes/Catalog/Cargo/cargo_materials.yml
  Resources/Prototypes/Catalog/Cargo/cargo_security.yml
  Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
  Resources/Prototypes/Corvax/Catalog/Cargo/cargo_food.yml
Labels: No C#

#617 Changeling game presets
  Resources/Locale/ru-RU/game-ticking/preset-changeling.ftl
  Resources/Prototypes/game_presets.yml
  Resources/Prototypes/secret_weights.yml
Labels: Changes: Localization, No C#

#626 Правки звуков Кодов оповещения, правка карты ЦентКомм
  Resources/Audio/Misc/notice1.ogg
  Resources/Audio/Misc/notice2.ogg
  Resources/Audio/Misc/notice2_2.ogg
  Resources/Maps/centcomm.yml
  Resources/Prototypes/AlertLevels/alert_levels.yml
Labels: No C#, Changes: Map

#636 [ЗАКАЗ] Добавление вещей от отдела википедии
  Resources/Locale/ru-RU/ADT/Clothing/wiki_items.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Eyes/eyepatch_tretyakova.yml
  Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/flower_crown_blue.yml
  Resources/Prototypes/ADT/Entities/Clothing/Neck/unrobust_scarf.yml
  Resources/Prototypes/ADT/Entities/Clothing/Underwear/socks_liexer.yml
  Resources/Textures/ADT/Clothing/Eyes/Misc/eyepatch_tretyakova.rsi/equipped-EYES.png
  Resources/Textures/ADT/Clothing/Eyes/Misc/eyepatch_tretyakova.rsi/icon.png
  Resources/Textures/ADT/Clothing/Eyes/Misc/eyepatch_tretyakova.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Hats/flower_crown_blue.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/flower_crown_blue.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/flower_crown_blue.rsi/meta.json
  Resources/Textures/ADT/Clothing/Neck/unrobust_scarf.rsi/equipped-NECK.png
  Resources/Textures/ADT/Clothing/Neck/unrobust_scarf.rsi/icon.png
  Resources/Textures/ADT/Clothing/Neck/unrobust_scarf.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Neck/unrobust_scarf.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Neck/unrobust_scarf.rsi/meta.json
  Resources/Textures/ADT/Clothing/Underwear/Socks/socks_liexer.rsi/equipped-SOCKS.png
  Resources/Textures/ADT/Clothing/Underwear/Socks/socks_liexer.rsi/icon.png
  Resources/Textures/ADT/Clothing/Underwear/Socks/socks_liexer.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#

#633 мелкий фикс перевода
  Resources/Audio/Announcements/war.ogg
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/kudzu.ftl
  Resources/Prototypes/Maps/Pools/default.yml
Labels: Changes: Localization, No C#

#639 пончо, пончо, пончо!
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/misc.ftl
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/SindiPoncho.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/syndiedrobe.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/theater.yml
  Resources/Textures/ADT/Clothing/OuterClothing/Misc/poncho_sindi.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Misc/poncho_sindi.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Misc/poncho_sindi.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/OuterClothing/Misc/poncho_sindi.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/OuterClothing/Misc/poncho_sindi.rsi/meta.json
  Resources/Textures/Clothing/OuterClothing/Misc/classicponcho.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Clothing/OuterClothing/Misc/classicponcho.rsi/icon.png
Labels: Changes: Sprites, Changes: Localization, No C#

#645 Просто тёмный берет в одеждомат.
  Resources/Changelog/ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/Clothing/Head/hats.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Head/Hats/hats.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
  Resources/Textures/ADT/Clothing/Head/Hats/beret_black.rsi/equipped-HELMET-hamster.png
  Resources/Textures/ADT/Clothing/Head/Hats/beret_black.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/beret_black.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/beret_black.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Head/Hats/beret_black.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Head/Hats/beret_black.rsi/meta.json
Labels: Changes: Sprites, Changes: Localization, No C#, Status: Needs Review

#647 Novakid Rebalance
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/ADT/Novakid/Mobs/Species/novakid.yml
Labels: No C#

#657 Убрал возможность стать генокрадом
  Resources/Changelog/ChangelogADT.yml
  Resources/Prototypes/ADT/changeling/mobs.yml
Labels: No C#
